### ISSUE TITLE
Possible bug in escaping/unescaping text

### ISSUE THREAD

**Issue by rj33** [strophe/strophejs#103]
I was having a look at the new xmlunescape function recently added, and this led me to notice that there might be a bug in the escaping code in getText:
getText: function (elem)
{
if (!elem) { return null; }
var str = "";
if (elem.childNodes.length === 0 && elem.nodeType ==
Strophe.ElementType.TEXT) {
str += elem.nodeValue;
}
for (var i = 0; i < elem.childNodes.length; i++) {
if (elem.childNodes[i].nodeType == Strophe.ElementType.TEXT) {
str += elem.childNodes[i].nodeValue;
}
}
return Strophe.xmlescape(str);
},

That xmlescape has been there for a while, but I'm wondering if that should perhaps have been an unescape, rather than escape, and should be calling the new xmlunescape function?

The code seems to use xmlescape when creating TEXT nodes (and attribute values) in serialise (and the other code that uses createXMLNode will be doing escaping for free), so I would have thought when we extract text back out of them, we should be unescaping rather than escaping, but perhaps I'm misreading the code?

I also wonder if the following code for escaping attribute values in serialise should just be calling the xmlescape function?:
for (i = 0; i < elem.attributes.length; i++) {
if(elem.attributes[i].nodeName != "_realname") {
result += " " + elem.attributes[i].nodeName.toLowerCase() +
"='" + elem.attributes[i].value
.replace(/&/g, "&")
.replace(/\'/g, "'")
.replace(/>/g, ">")
.replace(/</g, "<") + "'";
}
}
Strictly speaking, we don't need to escape " as we are enclosing in an apostrophe pair (a bit hard to tell with my browser font), but just in case, and for reducing code duplication it probably makes sense to just use the xmlescape function here, as I don't think it is worth the near duplication just to remove one replace call in the chain.

(sorry I accidentally initially lodged this against the old metajack repo).

**Comment by rj33** [comment]
After having a further look at this, perhaps getText is like this by design, and is expected to be used to extract safe strings for injecting into HTML. It seems the elem extraction probably already unescapes anyway, so this is probably just putting the escaping back in. In any case, even if that isn't the case, some people may be relying on the escaping to be there on getText to avoid XSS problems, so probably not a good idea to change this anyway. 

Feel free to close, although the attribute escaping is probably worth changing to use the xmlescape function (sorry I just noticed the pasted code in my above report had escaping issues making it looks like the replace chain is replacing the html characters with the same chars - see repo for unmangled code).

**Comment by jcbrand** [comment]
@rj33 Just a tip. On github, if you enclose pasted code with three backticks, for examply:  \`\`\` alert('hello'); \`\`\`, then it renders nicely. Otherwise it's more difficult to read the code examples you pasted above.

I'll close this issue now.
