### ISSUE TITLE
Websockets support broken for MongooseIM

### ISSUE THREAD

**Issue by mweibel** [strophe/strophejs#104]
MongooseIM sends just `features` instead of `stream:features` (this is according to RFC 7395 correct) and therefore after the successful authentication the `bind` and `session` stanzas aren't being sent because it doesn't detect that there were features already sent over the wire.

Example log:

```
SENT: <open xmlns='urn:ietf:params:xml:ns:xmpp-framing' to='localhost' version='1.0'/>
RECV: <open from='localhost' id='1234567' xmlns='urn:ietf:params:xml:ns:xmpp-framing' xml:lang='en' version='1.0'/>
RECV: <features xmlns='http://etherx.jabber.org/streams'><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism></mechanisms><amp xmlns='http://jabber.org/feature/amp'/><sm xmlns='urn:xmpp:sm:3'/></features>
SENT: <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>SOMEFOOL</auth>
RECV: <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>
SENT: <open xmlns='urn:ietf:params:xml:ns:xmpp-framing' to='localhost' version='1.0'/>
RECV: <open from='localhost' id='12345678' xmlns='urn:ietf:params:xml:ns:xmpp-framing' xml:lang='en' version='1.0'/>
RECV: <features xmlns='http://etherx.jabber.org/streams'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/><session xmlns='urn:ietf:params:xml:ns:xmpp-session'/><amp xmlns='http://jabber.org/feature/amp'/><sm xmlns='urn:xmpp:sm:3'/></features>
```

Problem lies within the `_sasl_success_cb` method which [attaches the handler to `stream:features` and not to `features`](https://github.com/strophe/strophejs/blob/master/src/core.js#L2599).

**Comment by Gordin** [comment]
How is this correct according to RFC?
It reads
```
   Note that for stream features and errors, there is no parent context
   element providing the "stream" namespace prefix as in [RFC6120], and
   thus the stream prefix MUST be declared or use an unprefixed form:

   <stream:features xmlns:stream="http://etherx.jabber.org/streams">
     <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/>
   </stream:features>

   -- OR --

   <error xmlns="http://etherx.jabber.org/streams">
     <host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/>
   </error>
```
Sounds to me like the stream: is required?

**Comment by mweibel** [comment]
TBH I wasn't quite sure, but I read it as:
Either use the `stream:` prefix or use the **unprefixed** form. IMO this means to me that it is possible to use either form, which is also shown in the example (even though the example is IMHO not the best because it shows two different stanzas).

**Comment by Gordin** [comment]
Well, you can't just leave out the namespace in an XML document, pretty sure if you want to start a stream you need the stream ^^
But looking at their code it also seems to me like mongooseIM is trying to do the correct thing (sending stream:features) at least in their current HEAD version:
https://github.com/esl/MongooseIM/search?l=erlang&p=1&q=features&utf8=%E2%9C%93
https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_c2s.erl
If it's just sending features that seems like a bug in mongooseIM to me.

**Comment by mweibel** [comment]
Well the NS is still there, just as a `xmlns` and not as a prefix of the node name. 
For normal (sockets/bosh) XMPP connections, MongooseIM indeed sends `stream:features` but for [websockets they explicitely remove it](https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_websockets.erl#L323). 
Would be interesting to hear one of the RFC authors or so about this, so I'll send this question to the mailinglist :)

**Comment by mweibel** [comment]
Ok, it seems that MongooseIM is doing it correctly. Question is: how do we fix that? Setting two listeners instead of one is not really beautiful :/

**Comment by Gordin** [comment]
I don't think the way handlers work there is no better way than using 2 handlers. I implemented this in https://github.com/strophe/strophejs/commit/755fbefa4375caa02d9414e45a402b3124010aa2. I tested with Prosody and the current release for MongooseIM and it seems to work. Would be nice if you could test this again with your setup.
Just reopen this if it's still broken for you.
