### ISSUE TITLE
Strophe JS login error

### ISSUE THREAD

**Issue by ozgurm** [strophe/strophejs#107]
Hello,

My issue is about login in /strophejs-1.2.0/examples/basic.html page.

I setup XMPP server (OpenFire 3.9.3) and client as strophejs-1.2.0.
However in basic.html page, I am getting these result:

    Strophe is connecting.
    SENT: body rid='2645484719' xmlns='http://jabber.org/protocol/httpbind' to='ozgur' xml:lang='en' wait='60' hold='1' content='text/xml; charset=utf-8' ver='1.6' xmpp:version='1.0'  xmlns:xmpp='urn:xmpp:xbosh'/
    RECV: body xmlns='http://jabber.org/protocol/httpbind' xmlns:stream='http://etherx.jabber.org/streams' from='guveny-ozgur' authid='771730f7' sid='771730f7' secure='true' requests='2' inactivity='30' polling='5' wait='60' hold='1' ack='2645484719' maxpause='300' ver='1.6'stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'<mechanism>DIGEST-MD5</mechanism><mechanism>JIVE-SHAREDSECRET</mechanism><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>CRAM-MD5</mechanism></mechanisms><compression xmlns='http://jabber.org/features/compress'><method>zlib</method></compression><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/session xmlns='urn:ietf:params:xml:ns:xmpp-session'//stream:features>/body
    SENT: <body rid='2645484720' xmlns='http://jabber.org/protocol/httpbind' sid='771730f7'><auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='ANONYMOUS'/></body>
    SENT: <body rid='2645484720' xmlns='http://jabber.org/protocol/httpbind' sid='771730f7'><auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='ANONYMOUS'/></body>
    SENT: <body rid='2645484720' xmlns='http://jabber.org/protocol/httpbind' sid='771730f7'auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='ANONYMOUS'//body

    While posting response is:
    POST http://192.168.0.75:7070/http-bind/ 500 (Task org.jivesoftware.openfire.http.HttpSessionManager$HttpPacketSender@16d8641 rejected from java.util.concurrent.ThreadPoolExecutor@b54b06[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0])strophe.js:4611 sendFuncstrophe.js:4623 Strophe.Bosh._processRequeststrophe.js:4775 Strophe.Bosh._throttledRequestHandlerstrophe.js:4403 Strophe.Bosh._onIdlestrophe.js:3533 Strophe.Connection._onIdle

Thanks

**Comment by Gordin** [comment]
I'm not really sure what happens here, I just tried Openfire myself and can't get a connection either. Seems the HTTP binding module in Openfire has some problems. Connecting to the Openfire server via another BOSH proxy like node-xmpp-bosh works just fine.
Looks like Openfire does not send CORS headers, so your browser will not connect unless the domain you use for testing and Openfire are the same (including the Port).

Maybe someone with experience with Openfire can tell you how to set it this up, I don't think there is anything that can be fixed in Strophe here.
