### ISSUE TITLE
Handling send message on http errors

### ISSUE THREAD

**Issue by kabilan-baskaran** [strophe/strophejs#108]
Hi Jack,

I have few doubts on handling send message when http error occurs. Our project based on Mobile technology /Phonegap .

When i send a new message ,if no internet connection found at that time, your code will save the message automatically when a http error occurs. But, Is there any callback which can indicate that message gone as error  ?

I can clearly see when a XHR goes as wrong, you are throwing error to  "_hitError" function with the status. But i can't differentiate the XHR as Message/Presence/other XHRs.

Because right now ,we don't have server acknowledgement for send messages .So we blindly depend on strophe & we don't know strophe sends a message correctly or not.

It will be good if we a have callback on Success & Error for message XHR itself.

Note: The automatic resend might not be applicable for us in different scenario (where the user can close the app immediatly after sending a message,disconnect from the internet for the whole day .....)

I am waiting for your valuable feedback.

Thanks,
Kabilan

**Comment by jcbrand** [comment]
Since Strophe.js has been deemed stable (version 1.0 I guess) and it's been moved here, I don't think @metajack is very much involved in development anymore.

> It will be good if we a have callback on Success & Error for message XHR itself.

I suggest you make a pull request for that and then we can take a closer look at what you're proposing.

**Comment by kabilan-baskaran** [comment]
Hi @jcbrand ,

Thanks for your comments .Yes, i agree with you.

My question is simple,i need a callback on http success & error.I can see that strophe handling it very well but without acknowledging to the end user. The below function in strophe knows the status for each xhr. 

"if (reqStatus == 200)" - This condition checks the success response & sending the xhr object to "func".
       1. What is "func" in here & where it's refering to?  
       2. Can i add my handler(functions,codes) inside of this condition (Or) simply add a handler from my file/code to check this case?Because i don't want to disturb Strophe codes .
       3 . Is there any other way to detect a message sent to the server or not ? like single tick in whatsapp
       4.How do you handle this scenrios in converse.js ? 
       5.How do you diiferentiate the xhr is for message or not ?

current implementation by me: 
        Getting the xhr object on success & sending it to my function to check the xhr is message or not.
If message then mark the particular message as sent (singletick) by matching the message ID's.Is that make sense ? 

 /** PrivateFunction: _onRequestStateChange
     *  _Private_ handler for Strophe.Request state changes.
     *
     *  This function is called when the XMLHttpRequest readyState changes.
     *  It contains a lot of error handling logic for the many ways that
     *  requests can fail, and calls the request callback when requests
     *  succeed.
     *
     *  Parameters:
     *    (Function) func - The handler for the request.
     *    (Strophe.Request) req - The request that is changing readyState.
     */
    _onRequestStateChange: function (func, req)
    {
        Strophe.debug("request id " + req.id +
                      "." + req.sends + " state changed to " +
                      req.xhr.readyState);

        if (req.abort) {
            req.abort = false;
            return;
        }

        // request complete
        var reqStatus;
        if (req.xhr.readyState == 4) {
            reqStatus = 0;
            try {
                reqStatus = req.xhr.status;
            } catch (e) {
                // ignore errors from undefined status attribute.  works
                // around a browser bug
            }

            if (typeof(reqStatus) == "undefined") {
                reqStatus = 0;
            }

            if (this.disconnecting) {
                if (reqStatus >= 400) {
                    this._hitError(reqStatus);
                    return;
                }
            }

            var reqIs0 = (this._requests[0] == req);
            var reqIs1 = (this._requests[1] == req);

            if ((reqStatus > 0 && reqStatus < 500) || req.sends > 5) {
                // remove from internal queue
                this._removeRequest(req);
                Strophe.debug("request id " +
                              req.id +
                              " should now be removed");
            }

            // request succeeded
            if (reqStatus == 200) {
                // if request 1 finished, or request 0 finished and request
                // 1 is over Strophe.SECONDARY_TIMEOUT seconds old, we need to
                // restart the other - both will be in the first spot, as the
                // completed request has been removed from the queue already
                if (reqIs1 ||
                    (reqIs0 && this._requests.length > 0 &&
                     this._requests[0].age() > Math.floor(Strophe.SECONDARY_TIMEOUT * this.wait))) {
                    this._restartRequest(0);
                }
                // call handler
                Strophe.debug("request id " +
                              req.id + "." +
                              req.sends + " got 200");
                func(req);
                this.errors = 0;
            } else {
                Strophe.error("request id " +
                              req.id + "." +
                              req.sends + " error " + reqStatus +
                              " happened");
                if (reqStatus === 0 ||
                    (reqStatus >= 400 && reqStatus < 600) ||
                    reqStatus >= 12000) {
                    this._hitError(reqStatus);
                    if (reqStatus >= 400 && reqStatus < 500) {
                        this._conn._changeConnectStatus(Strophe.Status.DISCONNECTING,
                                                  null);
                        this._conn._doDisconnect();
                    }
                }
            }

            if (!((reqStatus > 0 && reqStatus < 500) ||
                  req.sends > 5)) {
                this._throttledRequestHandler();
            }
        }
    }

**Comment by Rom4eg** [comment]
check pull request https://github.com/strophe/strophejs/pull/114

**Comment by Gilead** [comment]
+1

My current workaround is rather crude but works: I put a custom property in all sent stanzas, capture the RID in raw output listener (simple regex), map to the internal message ID and store the mapping locally. The raw input listener captures acked RIDs and maps them back to sent message IDs. This way I know if a message has actually been received by the server and can update the app status accordingly.

**Comment by rafaeleyng** [comment]
I'm trying to do something similar to you, @Gilead, but I was using xmlInput instead of rawInput. Do you have some reason for using one instead of the other?

**Comment by serpaulius** [comment]
+1
Hi,
Is it really that difficult to know, if a message was sent successfully? I thought this is is one of the fundamental things one needs to implement in any messaging service/app.

I have a similar issue. I have a Cordova/Ionic3 app, which uses Strophe to connect to eJabberd server.
Here's a simple situation: internet connection disappears, and I am sending a message (Connection.send), while connection is still "available" (Connection.connected = true)'. After a while, disconnect event appears, and.. that's it, I have lost a "sent" message without any appropriate errors.

Isn't there any way to know if message was successfully delivered to server, if there are no callbacks nor server responses on sent message?

**Comment by jcbrand** [comment]
You can try XEP-0184 Message Delivery Receipts: https://xmpp.org/extensions/xep-0184.html
