### ISSUE TITLE
Compatibility with React Native

### ISSUE THREAD

**Issue by teseo** [strophe/strophejs#115]
Hello,

I was wondering wether this strophe could be used in a react native application or it is meant to work only for browsers?

Anybody has used it with a react native app?

Regards!

**Comment by jcbrand** [comment]
I guess no response means nobody's used it with react native yet. Closing.

**Comment by MattFoley** [comment]
It's been over a year, should this be re-opened?

**Comment by MattFoley** [comment]
I think you guys should reopen this, there looks to be only a few small issues stopping this from running on a React Native environment.

Here's an example project, the issue being that "document" does not exist in a React Native environment.

https://github.com/MattFoley/react-native-strophe-demo/tree/master

**Comment by cgupta** [comment]
We have made some changes to support React Native. Shall we go ahead submit the Pull request?

**Comment by jcbrand** [comment]
@cgupta Yes please!

**Comment by ggozad** [comment]
Please submit a PR so that we do not duplicate work unnecessarily. Also if possible avoid rn-hackify and use https://github.com/philikon/ReactNativify instead which is far less intrusive. /cc @MattFoley

**Comment by cgupta-logmein** [comment]
We have been able to create global like this at the start of the app so that both objects are available within RN context. This has helped resolve any issue. However, we have old fork of Strohphe and need to see if our changes will work with the latest version and shim we have created.
global.document = jsdom.jsdom();
global.DOMParser = document.defaultView.DOMParser;

**Comment by atburghardt** [comment]
I found a working solution: Im using a ReactNative WebView running parallel and not Visible to my ReactNativeApp, similar to this Crypto (but with ReactNativeWebview! not React Native WebView Javascript Bridge, check the Crypto Example: https://github.com/saulshanabrook/react-native-webview-crypto )

In the WebView you can use Strophe, you just need to write a Wrapper for the Communication between RN and Strophe in the WebView.

I'll try to make gitRepo with a working Basic Version

**Comment by trevorwhealy** [comment]
@atburghardt that would be really interesting - looking forward to it!

**Comment by trevorwhealy** [comment]
By the way, this would be an incredible package to bring to React Native, I'm hoping that @cgupta / @cgupta-logmein could please share a little more insight on the polyfill / mock approach to unblock the `document` is not defined errors.

**Comment by cgupta-logmein** [comment]
Here is the sample code:

You need to use XMLDOM and other object at global level to support the features.

const xmlDom = require('xmldom');
const base64 = require('base-64');
const fetchPolyfill = require('whatwg-fetch');

export default function () {
    global.DOMParser = xmlDom.DOMParser;
    global.document = new DOMParser().parseFromString('<xml></xml>', 'text/xml');
    global.atob = base64.decode;
    global.btoa = base64.encode;

    if (!global.fetch) {
        global.fetch = fetchPolyfill.fetch;
        global.Headers = fetchPolyfill.Headers;
        global.Request = fetchPolyfill.Request;
        global.Response = fetchPolyfill.Response;
    }
}

**Comment by cgupta-logmein** [comment]
index.android.js has polyfill first as provided above.
polyfill();

**Comment by atburghardt** [comment]
@cgupta-logmein , I'd like to use your solution, but can't make it work. 
Isn't this line
 `global.document = new DOMParser().parseFromString('<xml></xml>', 'text/xml');`
overwriting RNs global.document? My App crashes because of this. Could you please post some more details and/or explanation?

**Comment by joeytwiddle** [comment]
We have just started to get it working with a create-react-native-app and Expo. Our bootstrap is:

```js
// yarn add xmldom
window.DOMParser = require('xmldom').DOMParser;
window.document = new DOMParser().parseFromString("<?xml version='1.0'?>", 'text/xml');

require('./lib/strophejs-fixed/strophe.min.js');

const Strophe = window.Strophe;
```

We found we had to tweak one thing: For some reason, although it worked fine in the browser, when running under Expo we would get `responseText` but no `responseXML`. We solved that by simply parsing the `responseText` inside Strophe. Patch here: https://github.com/strophe/strophejs/pull/281

**Comment by joeytwiddle** [comment]
We also found that if we wanted to debug we could not require the unminified script `strophe.js` because it uses requirejs. The bundler produced the error:

    require() must have a single string literal argument

The solution was to open `strophe.js` and rename all occurrences of `require` with some other word, for example `rjsRequire`. Then we could include the unminified version just fine.

**Comment by flavio-dev** [comment]
@joeytwiddle @cgupta it looks like your solution breaks my RN. For instance in my case I instantly have this:
```Cannot read property 'scrollIntoView' of undefined```

I would like to test on the web view like crypto @atburghardt. Do you have an example somewhere?

Cheers

**Comment by joeytwiddle** [comment]
Sorry to hear that @flavio-dev. We aren't using scrollIntoView. Do you think it's the `DOMParser` or the `document`?

Assuming that you had a working `document` before, and we have replaced it with one that works for strophe but breaks for your app, then perhaps we can try to merge the missing functions into the new document:

```js
const originalDocument = window.document;
window.document = new DOMParser().parseFromString("<?xml version='1.0'?>", 'text/xml');
Object.setPrototypeOf(window.document, originalDocument);
```

That might not help with other DOM elements though. :frowning:
