### ISSUE TITLE
Allow attrs() to remove attributes

### ISSUE THREAD

**Issue by cburschka** [strophe/strophejs#116]
It might be kind of neat if calling `tree.attrs({y: null})` (or maybe `undefined`) would actually unset the attribute. As far as I can tell, this can currently only be done by calling `tree.node.removeAttribute('y')` directly, and therefore can't be chained with the rest of the XML builder stuff.

**Comment by Gordin** [comment]
That sounds reasonable. I just tried to implement this with undefined. It should now remove attributes that are explicitly set to ```undefined``` in the given object. Let me know if it works for you with the latest version from master.

**Comment by cburschka** [comment]
Thanks, this seems to work great! Maybe `xmlElement()` could ignore undefined values as well so that `Strophe.Builder(name, attrs)` is still equivalent to `Strophe.Builder(name).attrs(attrs)`, but since it's easy enough to call `attrs()` I don't know if that's important.

**Comment by jcbrand** [comment]
https://github.com/strophe/strophejs/commit/cc575bffeae10bff9e75dfb11b0bb7f440ac1979

**Comment by Gordin** [comment]
@cburschka I added this in https://github.com/strophe/strophejs/commit/c8ccfeea28b3479f25df70d4fe9649d29235c777. When an attribute is set to ```undefined``` in xmlElement it will not be added.
