### ISSUE TITLE
WebSocket use example 

### ISSUE THREAD

**Issue by rastkojokic** [strophe/strophejs#117]
Any chance you guys can provide some examples of using Strophejs WebSockets?

I am trying to set it up to connect with Ejabberd xmpp server.

Thanks in advance!

**Comment by rastkojokic** [comment]
Sorry, didn't see the response at previous issue... Closing this one...

**Comment by kuryaki** [comment]
Link to response ?

**Comment by emiliemarchand** [comment]
https://github.com/strophe/strophejs/issues/9#issuecomment-102452834
