### ISSUE TITLE
converse.logOut() with auto_reconnect = true causes reconnection retries

### ISSUE THREAD

**Issue by nevcos** [strophe/strophejs#120]
Calling converse.logOut() with auto_reconnect option with ```true``` value, causes reconnection retries.

Logout is calling disconnect:

```
        this.logOut = function () {
            converse.chatboxviews.closeAllChatBoxes(false);
            converse.clearSession();
            converse.connection.disconnect();
        };
```

And the DISCONNECTED status is catch by the onConnect callback, that tries to reconnect:

```
            } else if (status === Strophe.Status.DISCONNECTED) {
                if (converse.auto_reconnect) {
                    converse.reconnect();
                } else {
                    converse.renderLoginPanel();
                }
             }
```

Maybe conversejs could have a special "LOGING_OUT" state, where there's no reconnection attempts.

I'm using converse 0.9.3 (converse-no-locales-no-otr.js file) with Chrome 43 on Windows 7.

Thanks

**Comment by jcbrand** [comment]
Wrong project and issue tracker. This should go into [converse.js](https://github.com/jcbrand/converse.js).

**Comment by nevcos** [comment]
Sorry @jcbrand , big mistake.
Thanks

**Comment by jcbrand** [comment]
No worries @nevcos
