### ISSUE TITLE
nodeName comparisons in createHtml should be case insensitive

### ISSUE THREAD

**Issue by gerges** [strophe/strophejs#121]
Per https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeName nodeName is not always guaranteed to be lowercase (and is often uppercase).  Since white-listing (`Strophe.XHTML.tags` and `Strophe.XHTML.attributes`) are done as straight array lookups and string comparisons, they currently fail on Chrome. 

I believe the simplest fix would be to just set `tag = elem.nodeName.toLowerCase();` in https://github.com/strophe/strophejs/blob/master/strophe.js#L1235

http://jsbin.com/piworefoli/2/edit?js,console

**Comment by jcbrand** [comment]
Thanks. You're right. XHTML tags must be lower case, so we need to make sure that the received HTML tag is lower case.

**Comment by jcbrand** [comment]
The title is however wrong. The comparison should not be case insensitive, since XHTML tags must be lower case. Instead we must just ensure that XHTML tags are always lower case.
