### ISSUE TITLE
Problem on sending message twice when unload page

### ISSUE THREAD

**Issue by ThuanPhamQuoc** [strophe/strophejs#123]
BEFORE

            if (req.sends > 1) {
                // Using a cube of the retry number creates a nicely
                // expanding retry window
                var backoff = Math.min(Math.floor(Strophe.TIMEOUT * this.wait),
                                       Math.pow(req.sends, 3)) * 1000;
                setTimeout(sendFunc, backoff);
            } else {
                sendFunc();
            }

SHOULD BE CHANGE TO

            if (req.sends > 1) {
                // Using a cube of the retry number creates a nicely
                // expanding retry window
                var backoff = Math.min(Math.floor(Strophe.TIMEOUT * this.wait),
                                       Math.pow(req.sends, 3)) * 1000;
                setTimeout(sendFunc, backoff);
            } else if(req.sends == 0) {
                sendFunc();
            }

**Comment by jcbrand** [comment]
Please explain what the bug is here. What is the value of req.sends when two messages are sent out? I guess it's 1, right?
