### ISSUE TITLE
Strophe.Builder.c will swallow elements if given a blank string as a 'text' parameter

### ISSUE THREAD

**Issue by notnarb** [strophe/strophejs#124]
https://github.com/strophe/strophejs/blob/v1.2.1/src/core.js#L1121
This seems like odd behavior to me:
```
     *  This function moves the current element pointer to the child,
     *  unless text is provided.  If you need to add another child, it
     *  is necessary to use up() to go back to the parent in the tree.
```
is clearly specified but the code to check if 'text is provided' is
```javascript
if (!text) {
  this.node = child;
}
```
---
An example of how this might be an issue is if you were setting your presence like
```javascript
$pres.c('show', {}, var1)
    .c('status', {}, var2)
```
If var1 and var2 were blank strings (for example, if they were entered by a user), I would expect the following behavior
```xml
<presence>
  <show/>
  <status/>
</presence/>
```
but what happens instead is
```xml
<presence>
  <show>
    <status/>
  </show>
</presence>
```
because "" is falsey.

---
I would expect false or undefined to trigger the current behavior, but I don't think a blank string might be intentional.  I think either the documentation should be changed (e.g. "moves the element pointer to the child if text is falsey (including an empty string)") or an explicit check for the empty string should be added to the code.

My current workaround is 
```javascript
$pres().c('show',{},couldBeEmpty || true)
```
which makes an empty node that does not become the parent of subsequent nodes.

**Comment by jcbrand** [comment]
Thanks for the bug report. It's fixed now.
