### ISSUE TITLE
when xmpp<body>'s content is large.XML prase error  location:moz-nullprincipal:{b057e44e-6598-48bc-a86e-1c34f5bd1e90}

### ISSUE THREAD

**Issue by fisherstar** [strophe/strophejs#129]
Convert the image to Base64, and then put it in the <body> XMPP tag. If the image is larger, the browser will display an error.

XML prase error  location:moz-nullprincipal:{b057e44e-6598-48bc-a86e-1c34f5bd1e90}

**Comment by jcbrand** [comment]
That's a browser issue. Nothing to be done in strophe.js.
