### ISSUE TITLE
Strophe and eJabbdrd “unsubscribed” hander is not firing

### ISSUE THREAD

**Issue by qnimate** [strophe/strophejs#132]
am creating a chat app.

When user rejects a subscription request I am running this code
```
conn.send($pres({ to: from_id, type: "unsubscribed" }));
```
But for the other user this below handler is not firing
```
function unsubscribedStanza(stanza)
{
    var from_id = stanza.getAttribute("from");
    alert(from_id + " rejected your friend request");
}

conn.addHandler(unsubscribedStanza, null, "presence", "unsubscribed");
```
Please help. Thanks.

**Comment by jcbrand** [comment]
I don't see a bug in your code.

Override Strophe's `log` method so that it calls `console.log`.

Then check in on the receiving side in the browser's console whether the stanza is received at all.

**Comment by qnimate** [comment]
@jcbrand I checked in network tab. Stanza doesn't seems to be received.

**Comment by Gordin** [comment]
Then you are either sending the "unsubscribed" to the wrong JID or ejabberd does not deliver it correctly.
Are you sure that "from_id" is the correct JID you want to send the "unsubscribed" to?

**Comment by qnimate** [comment]
@Gordin I am sure because "unsubscribe" is working. Its just "unsubscribed" that not working.

Another question: Do you know how find whether a user is online or not. `presence` stanza handler include the full JID which is difficult to track.  Let me know. Thanks.

**Comment by Gordin** [comment]
If "unsubscribe" is working I guess you'll have to look into the ejabberd debug logs. Also, maybe look at tables 9.2 through 9.4 and make sure your users are actually in a state where the server is supposed to forward the "unsubscribed" stanza: http://xmpp.org/rfcs/rfc3921.html#rfc.section.9.2

You can use Strophe.getBareJidFromJid to get the bare JID to track users.
