### ISSUE TITLE
onRidChange function?

### ISSUE THREAD

**Issue by sualko** [strophe/strophejs#133]
Hey guys,

I am the developer of @jsxc and a long time ago I added the same functionality as in #119 with a hack to my fork 0ab9e6947fbf129ef9b92b7f7501910b39ee4110. The years have passed and with the glory of bower, I want to drop all dirty dependencies of my project.

Now I would like to use this upstream repo, but also stay with my fix, because I do not really trust in on-leave-page events. Are you interested in a pr, which adds a onRidChange function as an option which is called every time the rid is changed?

**Comment by Gordin** [comment]
Hm, I don't see any harm in having such a callback, could be useful if someone want's to take care of saving the session themselves.

**Comment by sualko** [comment]
> could be useful if someone want's to take care of saving the session themselves.

e.g. me :-).

I also store all my stuff in the localstorage, so this is one more use-case.

**Comment by jcbrand** [comment]
Sure, fine by me as well.
