### ISSUE TITLE
addHandler issue on message

### ISSUE THREAD

**Issue by darshanopenxcell** [strophe/strophejs#134]
Hi,

I am getting XML request but not getting message in addHandler message.

    connection.addHandler(onMessage, null, 'message', null, null, null);
    connection.send($pres().tree());

Message not come in this addHandler message function.
But i can see response from /http-bind/ like

     <body xmlns='http://jabber.org/protocol/httpbind'><message xmlns="jabber:client" to="xxx@xxxx.com" from="xxx@xxxx.com/78950f38" type="chat"><body>hello</body></message></body>

Please help me,
Thanks.

**Comment by jcbrand** [comment]
Only thing I can think of is to not pass in the last three `null` values.
For support questions, I think it's better to write to the mailing list, there are more people helping there: https://groups.google.com/forum/#!forum/strophe

**Comment by darshanopenxcell** [comment]
I was post there on 1 week ago but still not getting any reply.
https://groups.google.com/forum/#!forum/strophe



When i connect to server then it's working fine but when i am not doing any activity long time (20-30 minutes) then Strophejs not responding any more.

I can show XML message in console but Strophe js not getting that message.

**Comment by jcbrand** [comment]
That sounds like a different problem than what you originally wrote. Sounds like you're connection is dropping.
* You can try to use [XMPP PING](http://xmpp.org/extensions/xep-0199.html) to keep the connection alive.
* You can also use the **restore** method introduced in #119 to restore the session when you've noticed that the session has dropped.
