### ISSUE TITLE
chinese username can't login in

### ISSUE THREAD

**Issue by jimieweile** [strophe/strophejs#135]
======================
problem:
======================
1.chinese username can login sucessfully from spark
2.but failed when login from strophe
3.the error is "Failure.INCORRECT_ENCODING"
4.the code which throw the error:
    package org.jivesoftware.openfire.net;
    public class SASLAuthentication {
    .....line 295    
                            String value = doc.getTextTrim();
                            if (value.length() > 0) {
                                if (!BASE64_ENCODED.matcher(value).matches()) {
                                    authenticationFailed(session, Failure.INCORRECT_ENCODING);
                                    return Status.failed;
                                }

======================
the reason:
======================
1.when the username is chinese , the base64String in "String value" is not correct

======================
solution:
======================
1.add one line in at the begin of base64 funtion
    var obj = {
        /**
         * Encodes a string in base64
         * @param {String} input The string to encode in base64.
         */

        encode: function (input) {
        	input=utf16to8(input);

2.the function is copyed from internet:
    function utf16to8(str) {  
        var out, i, len, c;  
      
        out = "";  
        len = str.length;  
        for(i = 0; i < len; i++) {  
        c = str.charCodeAt(i);  
        if ((c >= 0x0000) && (c <= 0x007F)) {  
            out += str.charAt(i);  
        } else if (c > 0x07FF) {  
            out += String.fromCharCode(0xE0 | ((c >> 12) & 0x0F));  
            out += String.fromCharCode(0x80 | ((c >>  6) & 0x3F));  
            out += String.fromCharCode(0x80 | ((c >>  0) & 0x3F));  
        } else {  
            out += String.fromCharCode(0xC0 | ((c >>  6) & 0x1F));  
            out += String.fromCharCode(0x80 | ((c >>  0) & 0x3F));  
        }  
        }  
        return out;  
    } 

3. I modified one line of the function utf16toutf8():
        if ((c >= 0x0000) && (c <= 0x007F)) {  
   the orgin is 
        if ((c >= 0x0001) && (c <= 0x007F)) {  

4.because of the  char  "\u0000":
Strophe.SASLPlain.prototype.onChallenge = function(connection) {
  var auth_str = connection.authzid;
  auth_str = auth_str + "\u0000";
  auth_str = auth_str + connection.authcid;
  auth_str = auth_str + "\u0000";
  auth_str = auth_str + connection.pass;
  return auth_str;
};

**Comment by jcbrand** [comment]
Can you please make a pull request with your proposed change? Then we can try it out. Even better would be if you could also write a test for it.

**Comment by jimieweile** [comment]
1. I add one line to funciton encode() in strophe.js , and then I can login with chinese name.

        encode: function (input) {
        	input=utf16to8(input); //that is the line,the function utf16to8() is also coped below.


/** File: strophe.js
 *  A JavaScript library for XMPP BOSH/XMPP over Websocket.
 *
 *  This is the JavaScript version of the Strophe library.  Since JavaScript
 *  had no facilities for persistent TCP connections, this library uses
 *  Bidirectional-streams Over Synchronous HTTP (BOSH) to emulate
 *  a persistent, stateful, two-way connection to an XMPP server.  More
 *  information on BOSH can be found in XEP 124.
 *
 *  This version of Strophe also works with WebSockets.
 *  For more information on XMPP-over WebSocket see this RFC:
 *  http://tools.ietf.org/html/rfc7395
 */
    function utf16to8(str) {  
        var out, i, len, c;  
      
        out = "";  
        len = str.length;  
        for(i = 0; i < len; i++) {  
        c = str.charCodeAt(i);  
        if ((c >= 0x0000) && (c <= 0x007F)) {  
            out += str.charAt(i);  
        } else if (c > 0x07FF) {  
            out += String.fromCharCode(0xE0 | ((c >> 12) & 0x0F));  
            out += String.fromCharCode(0x80 | ((c >>  6) & 0x3F));  
            out += String.fromCharCode(0x80 | ((c >>  0) & 0x3F));  
        } else {  
            out += String.fromCharCode(0xC0 | ((c >>  6) & 0x1F));  
            out += String.fromCharCode(0x80 | ((c >>  0) & 0x3F));  
        }  
        }  
        return out;  
    }  


/* All of the Strophe globals are defined in this special function below so
 * that references to the globals become closures.  This will ensure that
 * on page reload, these references will still be available to callbacks
 * that are still executing.
 */

/* jshint ignore:start */
(function (callback) {
/* jshint ignore:end */

// This code was written by Tyler Akins and has been placed in the
// public domain.  It would be nice if you leftbas this header intact.
// Base64 code from Tyler Akins -- http://rumkin.com

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        define('strophe-base64', function () {
            return factory();
        });
    } else {
        // Browser globals
        root.Base64 = factory();
    }
}(this, function () {
    var keyStr = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";

    var obj = {
        /**
         * Encodes a string in base64
         * @param {String} input The string to encode in base64.
         */

        encode: function (input) {
        	input=utf16to8(input);

        	
            var output = "";
            var chr1, chr2, chr3;
            var enc1, enc2, enc3, enc4;
            var i = 0;

**Comment by jimieweile** [comment]
I just understand the "make a pull request " , I will try it .

**Comment by jcbrand** [comment]
Thanks @jimieweile, I see the pull request in #136. Closing this ticket now.
