### ISSUE TITLE
ejabberd consolidates messages.

### ISSUE THREAD

**Issue by paradisaeidae** [strophe/strophejs#139]
So when Strophe.isTagEqual( stanza, "message" ) is called on an inbound message/s....
Strophe.forEachChild(messagez, 'body',function(elem).... sees only one message.

**Comment by jcbrand** [comment]
Pretty lazy bug report. Please give an example how we can replicate what you're reporting or otherwise I'm closing the ticket.

**Comment by paradisaeidae** [comment]
Fair comment.Will elaborate.                                                                                                                                                                                                                                                                                                                                        MarkT                                                                                                                                                                                                                 From: JC BrandSent: Friday, 21 August 2015 21:54To: strophe/strophejsReply To: strophe/strophejsCc: MarkTSubject: Re: [strophejs] ejabberd consolidates messages. (#139)Pretty lazy bug report. Please give an example how we can replicate what you're reporting or otherwise I'm closing the ticket.

—Reply to this email directly or view it on GitHub.

**Comment by paradisaeidae** [comment]
Strophe is used to seeing this:
<body xmlns='http://jabber.org/protocol/httpbind'>
 <message xmlns='jabber:client' from='jid@ejdHost.com/29757' to='anonymousJid@ejdHost/aResource' xml:lang='en' type='chat'>
 <body>Modifications made</body></message>
</body>

Ejabberd optimistically consolidates messages.
Not sure if this is configurable in ejabberd.
Looking into it.

So if ejabberd sees numerous inbound with source/dest ==, within an (unknown) period it will combine them:
<body xmlns='http://jabber.org/protocol/httpbind'>
 <message xmlns='jabber:client' from='jid@ejdHost.com/29757' to='anonymousJid@ejdHost/aResource' xml:lang='en' type='chat'>
 <body>aFile file saved.</body></message>
 <message xmlns='jabber:client' from='jid@ejdHost.com/29757' to='anonymousJid@ejdHost/aResource' xml:lang='en' type='chat'>
 <body>aFile retreived.</body></message>
 <message xmlns='jabber:client' from='jid@ejdHost.com/29757' to='anonymousJid@ejdHost/aResource' xml:lang='en' type='chat'>
 <body>aMessage=20a30318c8287dc57e9fc175120a0883</body></message>
</body>

MarkT

**Comment by paradisaeidae** [comment]
Strophe is used to seeing this:
'<body xmlns='http://jabber.org/protocol/httpbind'>
 <message xmlns='jabber:client' from='jid@ejdHost.com/29757' to='anonymousJid@ejdHost/aResource' xml:lang='en' type='chat'>
 <body>Modifications made</body></message>
</body>'

Ejabberd optimistically consolidates messages.
Not sure if this is configurable in ejabberd.
Looking into it.

So if ejabberd sees numerous inbound with source/dest ==, within an (unknown) period it will combine them:
'<body xmlns='http://jabber.org/protocol/httpbind'>
 <message xmlns='jabber:client' from='jid@ejdHost.com/29757' to='anonymousJid@ejdHost/aResource' xml:lang='en' type='chat'>
 <body>aFile file saved.</body></message>
 <message xmlns='jabber:client' from='jid@ejdHost.com/29757' to='anonymousJid@ejdHost/aResource' xml:lang='en' type='chat'>
 <body>aFile retreived.</body></message>
 <message xmlns='jabber:client' from='jid@ejdHost.com/29757' to='anonymousJid@ejdHost/aResource' xml:lang='en' type='chat'>
 <body>aMessage=20a30318c8287dc57e9fc175120a0883</body></message>
</body>'

MarkT

**Comment by jcbrand** [comment]
Looks like `Strophe.forEachChild(messagez, 'body',function(elem)` needs to be changed to `Strophe.forEachChild(messagez, 'message', function(elem)` (perhaps also the callback function's code, since `elem` is now one node deeper).

Have you already fixed this for yourself? If so, can you make a pull request?

**Comment by paradisaeidae** [comment]
Have not fixed here.
Using workaround.
Do not have mock built for testing.
On my list.

**Comment by jcbrand** [comment]
I did a grep, and `Strophe.forEachChild(messagez, 'body',function(elem)....` doesn't appear in the Strophe source code.

You're most likely looking at 3rd party code which uses strophe.js, and not strophe.js itself. I'm therefore closing this ticket.

**Comment by paradisaeidae** [comment]
Pretty lazy grepping.

**Comment by jcbrand** [comment]
Ok, show me then where in the strophe.js source code that line is.

**Comment by paradisaeidae** [comment]
messagez is a codified plural of the processing of messages.
Spelt with a 'z' to suggest an area to be changed.
So won't find with a grep.
'Strophe.forEachChild(' will be found with grepping.
I have to timeslice this query/investigation with other tasks.
Strophe is a well regarded piece of work.
So understanding where the change is to be made might take some time.
As side-effects are not welcome.
Cheers!
