### ISSUE TITLE
Is it possible to detect a user's connection status??

### ISSUE THREAD

**Issue by clarklight2** [strophe/strophejs#140]
I am wondering if it is possible to detect a user's connection to see if specific user's connection is disconnected etc. 

Because i am trying to detect a user(receiver's) status before i send out a message and if the receiver is disconnected, then i will also trigger another script.

**Comment by Gordin** [comment]
The server should take care of keeping track of connection states of the users. When you receive a <presence> stanza from a user you can assume he is connected until you receive a <presence> stanza with type='unavailable'

**Comment by clarklight2** [comment]
@Gordin thanks for the reply, sorry i am new to strophe. Just want to understand this more clearly, so if my presence is online and if i lost internet connection, and another user check my presence it will return type='unavailable' to the user that is checking my presence??

 As i have set the "if user idle for over 30seconds" it will disconnect the user if there is no ping back.

**Comment by Gordin** [comment]
Well, you never "check" for a users presence, you just listen for presence stanzas. The XMPP server you are connected to will send you presence stanzas that indicate the status of other users whenever anything changes. So when you lose your connection the server you are connected to will inform all other users that are subscribed to your presence about it. (After some timeout for connections on that server has passed of course)

**Comment by clarklight2** [comment]
Thanks for the reply, so i can't actively "listen" in to a specific user's current presence on demand? Because that is the function that i am trying to achieve.

 As what i am trying to achieve is when on a one to one message, when i(a user) send a message out, i also check the "message receiver's" connection status(to see if they are connected or not), if they are not connected, then it will trigger another script. 

I was looking at the Ping plugin, and it said it can ping a client, wasnt sure if it is possible to ping a client on demand and see if they are connected or not.

**Comment by Gordin** [comment]
Yes, you will have to send out a presence stanza of your to your server though to indicate that your current connection is supposed to be "online", then your server will inform you about all changes from contacts. (If you connect without sending a presence afterwards you will not appear online to anyone and your server will consider you as kind of inactive and don't send presences to you)

To check wether a message has been received or not you could try the "receipts" plugin, it's designed to do just that https://github.com/metajack/strophejs-plugins/blob/master/receipts/strophe.receipts.js
(Both parties will have to support the receipt protocol though, so it might not work when you send messages to other clients that do not support this)

You can use http://xmpp.org/extensions/xep-0199.html#e2e to do client-to-client pings, but usually you shouldn't need to do that when you just listen for presences of other clients.
