### ISSUE TITLE
Connection "reset()" function removes all the auto initialized plugin system handlers

### ISSUE THREAD

**Issue by OpenSiteMobile** [strophe/strophejs#141]
Came across this problem using Candy Chat. Their script calls _connection.reset() before each _connection.connect() call. Their solution is to re-register their system handlers each time, but I don't think they use the latest Strophe script(s) either. I'm trying to use it with the latest version of the Strophe plugins and script (f5ba40bc51848b3bdfa720c8470d2011b80f1113). Either way, the code for:
```
_connection._changeConnectStatus(Strophe.Status.REDIRECT, "Received see-other-uri, resetting connection");
```
...won't work because it to will remove any of the auto initialized Strophe plugin system handlers.

Not sure what is the best way to go about fixing this. I'm guessing the "see-other-uri" stuff isn't used much, so maybe the answer is just don't use it (error instead), or just don't use _connection.reset().

**Comment by jcbrand** [comment]
In this case, I don't see the point of resetting the connection, since it's just the URI that needs to change.

**Comment by OpenSiteMobile** [comment]
Yeah, that was my first inclination. I guess it just depends on when? If authentication is done or not, or if handlers have been removed which will be needed for the redirect connection. It doesn't seem to be a pressing issue, but just one to be aware of.
