### ISSUE TITLE
Chinese jid can not login

### ISSUE THREAD

**Issue by cqian59420** [strophe/strophejs#147]
I use the chinese jid,but failed to login,

<body xmlns='http://jabber.org/protocol/httpbind'><failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
<not-authorized/></failure></body>

**Comment by jcbrand** [comment]
Please try with this pull request: https://github.com/strophe/strophejs/pull/136

**Comment by mathiasfriman** [comment]
I can confirm that this patch allows Jitsi-Meet to authenticate with LDAP using SASL with a username or password that contain non-ASCII characters like (in my case) swedish åäö and ÅÄÖ, which was previously not possible.

**Comment by mathiasfriman** [comment]
Ping @cqian59420 and @jcbrand, regardless if this works with Chinese characters I suggest that this patch should be applied since it solves other problems like the one mentioned above. :)

**Comment by jcbrand** [comment]
@mathiasfriman The patch makes the tests fail. Also, it's not exactly clear what it does and why it works. I can see that it converts utf-16 to utf-8, but the overall context is not clear to me. For example why it's necessary and under which circumstances it should be used. I've written about it on the pull request.
