### ISSUE TITLE
Is it possible to get a users muc affiliation using the muc plugin.

### ISSUE THREAD

**Issue by patrickcorrigan** [strophe/strophejs#151]
Ideally I would like to be able to get a list of the owners of the muc. Is there a way to get a users affiliation? Thank you very much.

**Comment by jcbrand** [comment]
Note, this is the core strophe.js repository and issue tracker. You really want to ask this on the strophejs-plugins repo: https://github.com/strophe/strophejs-plugins

In any case, I think you can use the `queryOccupants` method (see [here](https://github.com/strophe/strophejs-plugins/blob/master/muc/strophe.muc.js#L319)) to get a list of occupants and then check on the `affiliation` property on each occupent.

**Comment by patrickcorrigan** [comment]
My apologies jcbrand. I will do thank you. With regards to the queryOccupants method. I have used it but do not get any affiliation information. This could be due to the way my xmpp server is configured. I do however get affiliation on presence messages. Thank you very much for your help.

**Comment by jcbrand** [comment]
Did you check the `affiliation` property? If that doesn't work then I don't know whether it's possible. Perhaps not.

**Comment by patrickcorrigan** [comment]
There is none as far as I can tell. This is the xml response I get from the queryOccupants method. Unless I'm missing something or using it incorrectly.

```
<iq xmlns="jabber:client" from="musica@conference.xmpp.getmusicahere.com" to="patrick@xmpp.getmusicahere.com/11820775871444307634471141" id="1:sendIQ" type="result">
    <query xmlns="http://jabber.org/protocol/disco#items">
        <item jid="musica@conference.xmpp.getmusicahere.com/pat" name="pat"/>
        <item jid="musica@conference.xmpp.getmusicahere.com/jim" name="jim"/>
    </query>
</iq>
```

**Comment by jcbrand** [comment]
Yeah, then looks like you unfortunately can't query for it. I don't use this plugin personally.
