### ISSUE TITLE
Strophe 1.2.3 is not available on npm

### ISSUE THREAD

**Issue by Kyos** [strophe/strophejs#152]
Strophe v1.2.3 has been released two month ago and it's still not available on npm. 
Could you please publish it ? 

Thanks by advance.

**Comment by jcbrand** [comment]
Ping @flosse

**Comment by flosse** [comment]
Hm... I downloaded `v1.2.3` and it contains a `package.json` with `v1.2.2` and the following JS file is included:

    sha256sum strophe.js
    97ba27ed1614a31934773288c01cccef10139f792bdcbcbc454b80e41a336860  strophe.js

In https://github.com/flosse/strophejs-npm there is the same. Can somone publish the hash of the real `v1.2.3`?

**Comment by jcbrand** [comment]
The package.json *was* updated... See here: https://github.com/strophe/strophejs/commit/a11ebefa3db1b6712d51d0d309b9f68f8e391d1b

**Comment by aksonov** [comment]
@jcbrand Did you done 'npm publish'? I still see only 1.2.2 version

**Comment by jcbrand** [comment]
I was hoping @flosse would do it, since he has done it before and has the NPM account credentials. I guess I can release it under my own NPM account credentials. I'll put it on my TODO list.

**Comment by flosse** [comment]
@jcbrand can you publish the **sha256sum** of the correct `strophe.js`? Thx.

**Comment by jcbrand** [comment]
hi @flosse, I'm not exactly sure what you need.

Here's what I did:
```
jc@nix-14:45:~/strophejs (master)$ git checkout v1.2.3
jc@nix-14:45:~/strophejs ((HEAD detached at v1.2.3))$ shasum strophe.js
c409ce27e879132b9da18f4a9a8a9bc780dc2b05  strophe.js
```

**Comment by flosse** [comment]
ok this is what I get:

```
$ git clone https://github.com/strophe/strophejs/ 
$ cd strophejs
$ git checkout v1.2.3
$ sha256sum strophe.js 
97ba27ed1614a31934773288c01cccef10139f792bdcbcbc454b80e41a336860  strophe.js
$ sha256sum package.json 
8aef03b9e36fa361f532cc274ee449da832722404395dc958ce77d0819b20d08  package.json
```
BTW: within `package.json` there is `"version": "1.2.2"`

**Comment by jcbrand** [comment]
Sorry, I used shasum incorrectly...
I get the same as you.
```
jc@nix-16:00:~/strophejs ((HEAD detached at v1.2.3))$ sha256sum strophe.js
97ba27ed1614a31934773288c01cccef10139f792bdcbcbc454b80e41a336860  strophe.js
```

I don't really see why that's so important though, since there is a tag. About the pinning in the package.json, that's regrettable. Could you make a branch of the v1.2.3 tag and add one commit to fix that?

**Comment by flosse** [comment]
> I don't really see why that's so important though

because I don't want to publish a wrong version again :)
So now you can install via npm v1.2.3 that is equal to 1.2.2

**Comment by jcbrand** [comment]
Thanks @flosse!
