### ISSUE TITLE
Handling of custom ports

### ISSUE THREAD

**Issue by acidicX** [strophe/strophejs#154]
Hi there,

I have a jabber account on a server with a non-standard port. XMPP over BOSH with custom ports is possible: https://xmpp.org/extensions/xep-0206.html (route='xmpp:example.com:9999'). 

When Strophe.Connection.connect is called with the user "test@example.com:9999", Strophe parses the domain as "example.com:9999" but returns the error: 
````BOSH-Connection failed: host-unknown.````
Therefore, I cannot get any connection to my server.

According to [RFC 3920](https://www.ietf.org/rfc/rfc3920.txt), host-unknown means:
````the value of the 'to' attribute provided by the initiating entity in the stream header does not correspond to a hostname that is hosted by the server.````

I guess that means that Strophe does not parse the domain without the port (for the "to" field in the request body) and neither adds a route if a custom port is specified?

**Comment by jcbrand** [comment]
Why do you specify the port in the user's JID?

You should be specifying the port when setting up the connection:
`var conn = new Strophe.Connection('example.com:9999')`

**Comment by jcbrand** [comment]
Actually, scratch that.. I see you want to use the `route` parameter. You can pass that in when you call `connect`.

See here: https://github.com/strophe/strophejs/blob/master/strophe.js#L2341

**Comment by acidicX** [comment]
Ah, the route parameter of connect is the connect attribute of the XML body. Thanks, somehow I didn't realize that. You say I 'want to use' route; is there another way to add a custom port (of the **jabber server**, not the BOSH server)?

**Comment by jcbrand** [comment]
Not sure about alternatives, but I think 'route' is the right way.

**Comment by acidicX** [comment]
OK, I've tried with the route parameter now - still not working.
Two requests are created, and then it just seems to time out. No ERROR, CONNFAIL or AUTHFAIL. Where should I look to debug this further?

**Comment by jcbrand** [comment]
- Step through the code in the browser's debugger console to see what happens.
- Look for 404 or other errors in networking tab of browser's console.
- Check the log output of your XMPP server.
