### ISSUE TITLE
Is there anyway to check the use is exist or not on xmpp server

### ISSUE THREAD

**Issue by kevinsir** [strophe/strophejs#157]
When I add a friend, I want to make sure  the  jid of  user which I input  is exist ,if not, I will let me know.
Om, I know a way to query the database will do it. however, is there anyway do it  by xmpp server?

**Comment by jcbrand** [comment]
I'm not aware of a way to do this with core strophe.js.

One potential way might be to use a bot with admin rights and then do queries via [XEP-0133: Service Administration](http://xmpp.org/extensions/xep-0133.html#intro).

You can read here for more info that approach: https://www.ejabberd.im/node/3348

**Comment by kevinsir** [comment]
Thannks  very much for your help! https://www.ejabberd.im/node/3348 this is very userful! I have the same problom with him.Openfire server is right and ejabberd is wrong. 
However, I do not know how to use  a bot with admin rights. Does anyone who not  as admin can use?
