### ISSUE TITLE
Stream management

### ISSUE THREAD

**Issue by jiseruk** [strophe/strophejs#159]
is there any plan to add support for Stream management? I would like to use websockets, and restore the state of the conversations (with muc rooms) after page reloads.
Now I'm using bosh ant the restore() call, but I would like to try websockets.
I'm using ejabberd 15.04 as xmpp server.

Thanks!

**Comment by jcbrand** [comment]
I'm not sure whether it's best that stream management go into core strophe or that it's rather written as a plugin.

The XEP is still in the draft stage, so for now it's probably best to write it as a plugin.

Pull requests welcome ;)
