### ISSUE TITLE
Strophe for Google talk in phonegap app

### ISSUE THREAD

**Issue by LlamaloX** [strophe/strophejs#160]
First of all, sorry if my question is stupid. I am new to all of this.

I have a phonegap app (HTML5+JS+CSS) and I want to know if there is a way using strophe.js to have google talk in the app so the user using the app can talk with another one.

Thanks

**Comment by robobit** [comment]
I don't know about google talk, but for sure you can use Strophe.js in a phone gap app. I'm currently building a Cordova/Ionic app which uses Strophe.js to talk to my backend (ejabberd).

**Comment by LlamaloX** [comment]
Thanks. 

What would be the difference with google talk?

**Comment by robobit** [comment]
I'm just not familiar with google talk. If it is using xmpp then it should be essentially the same.

**Comment by LlamaloX** [comment]
It does use xmpp. Which steps should I follow?
