### ISSUE TITLE
Cannot use webpack with strophejs

### ISSUE THREAD

**Issue by arsonik** [strophe/strophejs#166]
Hi !

I installed strophe using "npm install strophe"
I'm importing it in a js file like this "import strophe from 'strophe'"
But i'am getting an error when I run : "node_modules/.bin/webpack"

```
Hash: 3f72e5786186f989a9f6
Version: webpack 1.12.9
Time: 4354ms
    + 33 hidden modules

ERROR in ./~/strophe/strophe.js
Module not found: Error: Cannot resolve module 'strophe-polyfill' in [...]/node_modules/strophe
 @ ./~/strophe/strophe.js 629:8-636:10
```

other npm modules : "babel-core babel-loader babel-preset-es2015 node-libs-browser webpack json-loader"

Any help ?

Cheers

**Comment by 1st8** [comment]
I am trying to do the same and getting the same error.

```es6
import * as Strophe from 'strophe';
```

```
ERROR in ./~/strophe/strophe.js
Module not found: Error: Cannot resolve module 'strophe-polyfill' in /some_project_path/node_modules/strophe
 @ ./~/strophe/strophe.js 629:8-636:10
```

**Comment by bgaillard** [comment]
Hi guys, i'm trying to use Strophe with Webpack but i have the following error.

```
Module not found: Error: Cannot resolve module 'strophe'
```

I'm new to Webpack, could you share your Webpack config to help me configure my project ? 

Also, I suppose I'll then encounter the same `strophe-polyfill` error as you, did you found any workaround ? 

Thanks, 

Baptiste

**Comment by bgaillard** [comment]
Hi again, don't know if its the right way to do it but it works in my case, so here is how I've configured Strophe with Webpack in my project. 

In my `index.html` file I have this.

```html
<!-- Strophe.js library and plugins -->
<script src="strophe.js"></script>
<script src="strophe.muc.js"></script>
<script src="strophe.roster.js"></script>
```

Inside `webpack.config.js` I've declared an `external` like this.

```javascript
externals : {
    strophe : "Strophe"
}
```

Then in my source code I use Strophe with the following imports and instructions.

```javascript
var Strophe = require('strophe'), 
    $build  = (name?  : string, attrs? : any) => { return new Strophe.Builder(name,       attrs); },
    $iq     = (attrs? : any                 ) => { return new Strophe.Builder("iq",       attrs); },
    $msg    = (attrs? : any                 ) => { return new Strophe.Builder("message",  attrs); },
    $pres   = (attrs? : any                 ) => { return new Strophe.Builder("presence", attrs); };
```

I'm using Angular 2 with Typescript, the equalivalent instructions in plain JS are the following.

```javascript
var Strophe = require('strophe'), 
    $build  = function(name, attrs) { return new Strophe.Builder(name, attrs); },
    $iq     = function(attrs) { return new Strophe.Builder("iq", attrs); },
    $msg    = function(attrs) { return new Strophe.Builder("message", attrs); },
    $pres   = function(attrs) { return new Strophe.Builder("presence", attrs); };
```

I know this is not a very clean Webpack integration, but it works, hope this helps.

**Comment by arsonik** [comment]
I'm using gulp with webpack and the workaround I've found is :
```
gulp.task('js', function() {
    return gulp.src(src + '/index.js')
        .pipe(plugin.webpack({
            module: {
                noParse: /strophe/,                
            },
        }))
```

**Comment by jcbrand** [comment]
Is there anything we should change in the Strophe code to make it webpack compatible? I don't use webpack at all and have no experience with it.

**Comment by bobnino** [comment]
Which file do i change in gulp arsonik ??
