### ISSUE TITLE
Any chance of putting node-strophe under strophe github and maintained?

### ISSUE THREAD

**Issue by wyattbiker** [strophe/strophejs#167]
I don't think they are actively supported. There are issues some issues with websocket support and jsdom installation.

**Comment by jcbrand** [comment]
Can you give a link to node-strophe?

**Comment by wyattbiker** [comment]
https://github.com/Iperity/node-strophe    They are not interested in upgrading it to work with websockets. 

For anyone who needs it, my workaround is to use eval(), but works like a charm.  Here is what I did at the moment to make it work with nodejs.

Download built **strophe.js** from github.
Make the following changes in **strophe.js**

Changed the signatures to make them global of the builder functions as follows:
```
global.$build=function(name, attrs) { return new Strophe.Builder(name, attrs); }
global.$msg=function(attrs) { return new Strophe.Builder("message", attrs); }
global.$iq=function(attrs) { return new Strophe.Builder("iq", attrs); }
global.$pres=function(attrs) { return new Strophe.Builder("presence", attrs); }
```
Changed  
```
var Strophe
```
to 
```
global.Strophe={};
```

Then in my node main application to load strophe I did the following to accomodate DOM/browser objects:
```
// Loadup strophe.js
var jsdom = require("jsdom").jsdom;
global.document = jsdom("<html><head></head><body></body></html>"),
global.WebSocket = require('websocket').w3cwebsocket;
global.window={}
global.DOMParser=require('xmldom').DOMParser;
window.DOMParser = DOMParser;
var openStropheFile='./assets/js/vendor/strophe.js';
eval(fs.readFileSync(openStropheFile)+'');

// Connect and use
var connection = new Strophe.Connection(BOSH_URL);

```

Seems to work fine in my tests, but it's not a node module. I cheated. Instead it's an eval().  Basically the concept is to eval strophe.js and provide it DOM/browser objects.  Also, jsdom is slow loading, so I may look for something else if possible (maybe cheerio?). Another caveat with jsdom the newer version is only available for node v4/v5. I have to manually download an older version.

It could be made into one by adding **module.exports** and using **require()** instead of **eval()**.
I hope you consider making it as a node module, this way it can be maintained as a single base.

Thanks

**Comment by mhofman** [comment]
[jsdom now supports the DOMParser API](https://github.com/tmpvar/jsdom/issues/1341) directly, so it may be possible to make strophe work in browser-less environment without modifying it as much?

**Comment by jcbrand** [comment]
> jsdom now supports the DOMParser API directly, so it may be possible to make strophe work in browser-less environment without modifying it as much?

A pull request for this would be very welcome. I'm not going to do this myself because I have no need for it. Closing this issue since I don't see much use in keeping it hanging around.
