### ISSUE TITLE
Wrong version tag

### ISSUE THREAD

**Issue by sualko** [strophe/strophejs#169]
Tag v1.2.3 points to e6dbb6ffb1aeb5731a038069fa3a83ed19d3791d (Strophe.VERSION = "1.2.2"), but I guess it should be a11ebefa3db1b6712d51d0d309b9f68f8e391d1b.

**Comment by sualko** [comment]
@jcbrand Can you fix that tag, because bower is using it to determine the correct (in this case wrong) commit.

**Comment by jcbrand** [comment]
Sorry, it's been on my TODO list for a while, will get to it asap.

**Comment by jcbrand** [comment]
@sualko: I've made a new release (1.2.4) and published it to NPM, hope that's ok with you.
https://www.npmjs.com/package/strophe.js

**Comment by sualko** [comment]
:+1:  Fine for me
