### ISSUE TITLE
Problems with iphone 5c 3g

### ISSUE THREAD

**Issue by AndreVicenteW** [strophe/strophejs#174]
The connecting is working fine on Android wi-fi and 3g, I can connect, send anda receive messages. In my iphone works only on wi-fi, when I put on 3g i can't connect. Somebody can help me? My project is a hibrid app using angularjs + ionic framework

**Comment by isfarax** [comment]
Hello,

Did you try to analyse the stanza, and have you looked at the error message you are receiving. We can determine what your issue is through the stanza analysis.

I would suspect that this has something to do with your encryption/SSL.

**Comment by AndreVicenteW** [comment]
It'snt a problem with strophe. I changed my chip and the connect was sussefull. Maybe is a APN configuration or something like that.

**Comment by isfarax** [comment]
The problem is not strophe, but the stanza analysis should tell you the issue you are having with your network.

Note that some XMPP Service providers use an encryption method that are not always compatible with certain networks, clients or countries - somehow there occurs authentication error.

**Comment by AndreVicenteW** [comment]
The error was because a was using the port 7070. I did a reverse proxy and everything went well. Thanks
