### ISSUE TITLE
Passing null as first paremeter of 'restore' does not work

### ISSUE THREAD

**Issue by bgaillard** [strophe/strophejs#175]
Hi, in the exemples of Strophe.js we call the `restore` method with a `jid` equals to `null`. 

https://github.com/strophe/strophejs/blob/master/examples/restore.js#L64
```javascript
try {
    connection.restore(null, onConnect);
} catch(e) {
    if (e.name !== "StropheSessionError") { throw(e); }
    $(button).show();
}
```

But in the source code of the `_restore` function the condition seems to be bad. 

https://github.com/strophe/strophejs/blob/master/strophe.js#L4483

```javascript
... || jid === "null" ...
```

So we have to update the sample to this. 
```javascript
connection.restore('null', onConnect);
```

Or change the source code of the `_restore` function to this. 
```javascript
... || jid === null ...
```

Is it correct ?

**Comment by jcbrand** [comment]
You're right, that was a bug. Thanks for reporting.

**Comment by bgaillard** [comment]
@jcbrand, great, thanks a lot for your reactivity on this !
