### ISSUE TITLE
How to send message to anonymous login user ?

### ISSUE THREAD

**Issue by Soo000** [strophe/strophejs#177]
Hi,
    IM Server is Openfire4.0.1

    I use jid which has no domain part (eg: lily/myroot) to connect openfire server, it's successful to connect. but how to send message to anonymous login user. My code as below:

   var jid = 'lily/myroom';
    var _conn = new Strophe.Connection("http://127.0.0.1:7070/http-bind/");
	_conn.connect(jid, '000000', function(status) {
		 if (status === Strophe.Status.CONNECTED) {
			alert("CONNECTED 5");			
		} else if (status === Strophe.Status.DISCONNECTED) {
			alert("DISCONNECTED 6");
		}
    });

**Comment by jcbrand** [comment]
I'm pretty sure that the user *does* have a domain, even if you don't specify it originally. It's probably configured in OpenFire. You'll need to determine what it is.
