### ISSUE TITLE
DOM Exception 11 on Cordova

### ISSUE THREAD

**Issue by blablapolicja** [strophe/strophejs#181]
hi, i'm using this library to make chat application based on Cordova
after turning on/off Airplane mode I got this exception: 
`DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.`

**Comment by robobit** [comment]
I'm doing the same thing (Cordava/Ionic based chat application). I don't see this problem.
Are you sure you are handling the connection callbacks properly? When you put your phone in Airplane mode the connection will break and Strophe will notify you with the callback. If you still try to use the connection object after that you could get exceptions.

**Comment by blablapolicja** [comment]
I use [reconnection plugin](https://github.com/zanchin/strophejs/blob/master/plugins/plugin.cm.js) to handle connection lost. it may cause the problem
