### ISSUE TITLE
How to create a persistence room ?

### ISSUE THREAD

**Issue by Soo000** [strophe/strophejs#187]
Hi  everyone,

    IM Server: openfire4.0.1
   
    I sent a create room stanza as below to a openfire server to create a group chat room. the group chat room can be created successful, but it's a temporary room when the owner quit, the room will be bestroied.
   How to set the room properites can change the room from temporary to persistence.

    <presence to='test02@conference.127.0.0.1/wangke'
          from='wangke@127.0.0.1/sitech_crmpd'
          xmlns='jabber:client'>
        <x xmlns='http://jabber.org/protocol/muc'/>
    </presence>

  Thanks a lot !

**Comment by Soo000** [comment]
<presence to='test02@conference.127.0.0.1/wangke'
          from='wangke@127.0.0.1/sitech_crmpd'
          xmlns='jabber:client'>
<x xmlns='http://jabber.org/protocol/muc'/>
</presence>

**Comment by cburschka** [comment]
Check out the room configuration protocol: http://xmpp.org/extensions/xep-0045.html#roomconfig.

Strophe doesn't have built-in support for this; you'll need to send the appropriate `<iq>` to the server, get back the form, and submit it with 'muc#roomconfig_persistentroom' set to 1.

**Comment by Soo000** [comment]
@cburschka, Thanks a lot, you are right !
