### ISSUE TITLE
Check sessionStorage is available before calling

### ISSUE THREAD

**Issue by dansullivan86** [strophe/strophejs#188]
Currently experiencing the following error:
TypeError: Cannot convert 'window.sessionStorage' to object

A quick skim of the code reveals a number of calls to window.sessionStorage that aren't wrapped in a try/catch or checking for support.

Our logs show this is mostly an issue in Opera mini, but I would imagine it could also cause issues in Safari private browsing mode.

**Comment by jcbrand** [comment]
Please make a pull request. You're able to produce the error and have an idea what the underlying issue is, so you're well positioned to do so.

**Comment by jcbrand** [comment]
Refs #180
