### ISSUE TITLE
Recover connection after CONFAIL

### ISSUE THREAD

**Issue by b-costa** [strophe/strophejs#196]
Hello,

Is there a configuration (or any other way) that force Strophe to reconnect after a connection fail (CONFAIL) event?

Thanks in advance,

Bruno Costa

**Comment by jcbrand** [comment]
Yes. I'll paste some examples from converse.js.

You can pass `keepalive: true` when you establish a new BOSH connection.
For example: https://github.com/jcbrand/converse.js/blob/master/src/converse-core.js#L1844

Then, you call `connection.restore()`. Strophe.js will then try to restore the dropped BOSH connection (by looking in the sessionStorage cache), and if there is no session to restore, it'll raise an Exception.

For example: https://github.com/jcbrand/converse.js/blob/master/src/converse-core.js#L1743

More info in the Strophe.js comments here:
https://github.com/strophe/strophejs/blob/527289f976e2ae4d20744fc5038638f0573bd908/strophe.js#L2203

**Comment by b-costa** [comment]
Hello,

Thanks for your help. Although, in my case this solution does not help. To my app recover after a connection fail (CONFAIL) event I had to create a new connection. 

When I have the Strophe.Status.CONNFAIL I do:

`try { 
     connection.restore(); 
} 
catch(e) {
     connection = new Strophe.Connection(boshUrl, {
            keepalive: true
     });
     connection.connect();
}`

but I always get the exception and create a new connection.

I'm no sure if this is the best way to solve this problem though. Any thoughts?

In my understanding, you solution is perfect to recover a connection, for example, after a reload.

Thanks in advance,

Bruno Costa

**Comment by jcbrand** [comment]
> I'm no sure if this is the best way to solve this problem though. Any thoughts?

Sorry, I don't have much more to say. Best thing you can do is to study the Strophe.js source code, or to step through it with the debugger, specifically the code where the BOSH tokens are stored in sessionStorage. If you always get an Exception, then it means the BOSH tokens aren't being stored in sessionStorage.
