### ISSUE TITLE
Requirejs in UMD breaks webpack

### ISSUE THREAD

**Issue by dansullivan86** [strophe/strophejs#199]
Since changing the UMD to use requirejs not require it is breaking webpack builds:

`if(typeof define === 'function' && define.amd){`
 `       var n_callback = callback;`
 `       requirejs(["strophe"],function(o){`
 `           n_callback(o.Strophe,o.$build,o.$msg,o.$iq,o.$pres);`
`        });`
`    }`

It seems strange to check for define and define.amd and then go on to use something completely different.  In this case webpack see's the define.amd and provides an AMD loader for us, however it obviously isn't providing us with requirejs.  

Is there a reason we don't use "define" in place of "requirejs" here?

**Comment by jcbrand** [comment]
[The relevant commit is here](https://github.com/strophe/strophejs/commit/4e4bcc132daf1a7ddbac09b5b3dd96033309d529).

> Is there a reason we don't use "define" in place of "requirejs" here?

Yes, a module is not being defined here, a module (`strophe`) is being loaded here (after it's been defined elsewhere).

> It seems strange to check for define and define.amd and then go on to use something completely different.

I agree. Can you change the condition to `typeof requirejs !== 'undefined'` and see whether that works?

**Comment by dansullivan86** [comment]
Using `typeof requirejs !== 'undefined'` doesn't work, giving `strophe.js:5603 Uncaught ReferenceError: Strophe is not defined`, I would guess because we check against `typeof define === 'function' && define.amd` everywhere else when deciding whether to create globals?

I have never used requirejs and don't know how it works at all....but some blind testing led me to
```
if (callback) {
    var n_callback;
    if(typeof requirejs !== 'undefined') {
        //For backwards compatability
        n_callback = callback;
        requirejs(["strophe"], function (o) {
            n_callback(o.Strophe, o.$build, o.$msg, o.$iq, o.$pres);
        });
    }else if(typeof define === 'function' && define.amd){
        //For backwards compatability
        n_callback = callback;
        define(["strophe"],function(o){
            n_callback(o.Strophe,o.$build,o.$msg,o.$iq,o.$pres);
        });
    }else{
        return callback(Strophe, $build, $msg, $iq, $pres);
    }
}
```

Which works in webpack and I would assume works in requirejs.

Also I'm probably overlooking something but I couldn't find the strophe module definition.

**Comment by jcbrand** [comment]
Concerning your example, I don't think the `define` call in the second clause of your if statement is correct. Actually, I think it subtly breaks things because `n_callback` then won't get called.

Instead, the module must be loaded, not defined. I however don't know what this would be in the context of webpack. Perhaps you can figure that out?

> Also I'm probably overlooking something but I couldn't find the strophe module definition.

See [src/wrapper.js](https://github.com/strophe/strophejs/blob/527289f976e2ae4d20744fc5038638f0573bd908/src/wrapper.js)

**Comment by dansullivan86** [comment]
The [webpack docs](https://webpack.github.io/docs/amd.html) say to use `require` as we did previously, I'm not sure what issue this was causing previously?

**Comment by jcbrand** [comment]
@ggozad made the change to enable compatibility with Node.js

More info here: https://github.com/strophe/strophejs/commit/4e4bcc132daf1a7ddbac09b5b3dd96033309d529

> The webpack docs say to use require as we did previously

The problem AFAIK was that Node.js also has a `require` method, which should not be called here. 
@ggozad, could you perhaps weigh in here?

**Comment by ggozad** [comment]
Hey!
The change of ``require`` to ``requirejs`` was to allow strophe to be used in mixed node/browser environments where ``require`` is a reserved node keyword, such as Electron. Strophe had requirejs support from the start which would be nice to keep as there are plenty of legacy apps that use it.

Why not do something like:
```
/* jshint ignore:start */
if (callback) {
    if(typeof define === 'function' && define.amd){
        //For backwards compatability
        var n_callback = callback;
        if (typeof requirejs ==='function') {
            requirejs(["strophe"],function(o){
                n_callback(o.Strophe,o.$build,o.$msg,o.$iq,o.$pres);
            });
        } else {
             // Do whatever webpack wants here.
        }
    }else{
        return callback(Strophe, $build, $msg, $iq, $pres);
    }
}
```

**Comment by dansullivan86** [comment]
Wouldn't a normal node environment fail the `typeof define === 'function' && define.amd` check? So never get to the require line anyway?

**Comment by ggozad** [comment]
@dansullivan86 Like I said, not in say electron apps that use a combo of node/browser libs.

**Comment by jcbrand** [comment]
So looks like `// Do whatever webpack wants here.` should then just be 
```
requirejs(["strophe"],function(o){
                n_callback(o.Strophe,o.$build,o.$msg,o.$iq,o.$pres);
```

**Comment by ggozad** [comment]
@jcbrand I guess so if @dansullivan86 can confirm it works for him.

**Comment by dansullivan86** [comment]
webpack needs 
```
require(["strophe"],function(o){
                n_callback(o.Strophe,o.$build,o.$msg,o.$iq,o.$pres);
```

@ggozad are you using requirejs with electron then?

**Comment by ggozad** [comment]
@dansullivan86 I do in order to support a legacy app that uses requirejs. I think what you wrote is exactly what @jcbrand suggested, so I guess we can go with that.
