### ISSUE TITLE
404 error when we try to send messsage

### ISSUE THREAD

**Issue by vijayaa** [strophe/strophejs#202]
i am using ejabberd 16.02 . Sometimes i am getting 404 error when i try to send message. When i check server logs it shows as `no session associated with sid`

**Comment by jcbrand** [comment]
That means your BOSH session has expired, perhaps because there was no request from the client to the server within the timeout period. You can use [XMPP Ping](http://xmpp.org/extensions/xep-0199.html) to try and keep the session alive, or alternatively you can tweak the timeout value.

**Comment by vijayaa** [comment]
ping is enabled in strophe
