### ISSUE TITLE
XML stanza attributes: there is no 'quot' escape inside 'serialize' method

### ISSUE THREAD

**Issue by soulfly** [strophe/strophejs#205]
There is no 'quot' escape inside **serialize** method https://github.com/strophe/strophejs/blob/master/strophe.js#L1619

So I can't send character **"**  in attributes

Please add also

     .replace(/"/g,  "&quot;");

**Comment by jcbrand** [comment]
Please make a pull request for this.

**Comment by soulfly** [comment]
Here it is
https://github.com/strophe/strophejs/pull/206
