### ISSUE TITLE
History Messages with Strophejs

### ISSUE THREAD

**Issue by xerest** [strophe/strophejs#210]
Hi,

How to get history messages with strophejs, to make chat history?

**Comment by jcbrand** [comment]
Depends on what kind of chat, private or MUC, and also on what your XMPP server supports.

Take a look at [XEP-0313](http://xmpp.org/extensions/xep-0313.html) and the strophe plugin for it:  https://github.com/strophe/strophejs-plugins/tree/master/mam

**Comment by xerest** [comment]
Thank you very much @jcbrand
