### ISSUE TITLE
Getting 504 gateway timeout error

### ISSUE THREAD

**Issue by vijayaa** [strophe/strophejs#212]
the following request is getting timedout frequently
<body rid='57993057' xmlns='http://jabber.org/protocol/httpbind' sid='1db840cbfd20e3922f594cc2017421a1858cca7a'><a xmlns='urn:xmpp:sm:3' h='9'/></body>

Console log show 
 No 'Access-Control-Allow-Origin' header is present on the requested resource.

i am using ejabberd server with haproxy.

**Comment by jcbrand** [comment]
Reopen this ticket if you can show that this is due to a bug in strophe.js. Otherwise, please use other channels for tech support.

**Comment by vijayaa** [comment]
i don't know exactly whether it is a strophe.js error, or HAProxy error. Need your help
