### ISSUE TITLE
Add a function to move the Strophe.Builder pointer back to the root node.

### ISSUE THREAD

**Issue by cburschka** [strophe/strophejs#214]
After constructing a particularly deep stanza structure, repeatedly calling up() is inconvenient and somewhat prone to bugs if you add more levels later.

Something like this would help:

```
function reset() {
   this.node = this.nodeTree;
}
```

**Comment by jcbrand** [comment]
Good suggestion, however I don't think `reset` is the right verb, since that implies (to me at least) reverting to a previous or original state.

What about `root()`? That makes it more clear that you're back to the root of the tree.

**Comment by cburschka** [comment]
Yeah, that seems like a better name.

**Comment by cburschka** [comment]
That seems like a better name, yeah.
