### ISSUE TITLE
chinese usernames still not working

### ISSUE THREAD

**Issue by hinesmr** [strophe/strophejs#215]
Good evening,

Using version `1.2.9`, the unicode handling issues don't seem to have been completely worked out yet. While I do see that commit https://github.com/strophe/strophejs/commit/243f67752d8da03508bfca34443318e7c174845b was submitted for #147 , it still doesn't appear to be working. It's pretty clear from the log below that the usernames are not being "un" quoted properly, resulting in log messages like these:

`
error: Got answer to IQ from wrong jid:%e8%bf%98%e5%9c%a8%e5%88%86%e6%9e%90@172.17.0.1
Expected jid: null
`

I naively tried commenting out this check, and it appears to work. I was able to add a buddy and start chatting.

I have a list of PRs that I need to submit, and I don't mind adding this to the list, but just commenting out that check seems like the wrong thing to do =)

The corresponding XML attempted to get the roster like this:

`<body rid="1935522" sid="d1429daa38956330fe0d99b3e72ddff74361ca2b"><iq type="get" id="56d750bd-ed22-4738-9f3a-2e703d87e3f3:roster"><query/></iq></body>`

Followed by:
`
<body xmlns="http://jabber.org/protocol/httpbind"><iq xmlns="jabber:client" from="%e8%bf%98%e5%9c%a8%e5%88%86%e6%9e%90@172.17.0.1" to="%e8%bf%98%e5%9c%a8%e5%88%86%e6%9e%90@172.17.0.1/4676880791477773314574061" id="628bc5d1-cf66-41d7-9aff-02d81df76f9c:roster" type="result"><query xmlns="jabber:iq:roster"/></iq></body>
`

Then, later Strophe mostly stops with `Removing Strophe handlers due to uncaught exception`.

**Comment by hinesmr** [comment]
I forgot to mention, this is with version `1.2.9`.

**Comment by jcbrand** [comment]
This appears to be unrelated to Chinese usernames. Instead it's related to #172.

Basically the bug appeared because you sent a stanza without a `to` attribute.

Removing the check is actually fine and should have been done earlier. I was waiting for the PR promised in #172.

I've gone ahead and removed it now. It should be working fine now, please let me know if you run into issues.

**Comment by hinesmr** [comment]
Thank you!
