### ISSUE TITLE
Get inactivity attribute from Session Creation Response

### ISSUE THREAD

**Issue by sualko** [strophe/strophejs#216]
I want to get the inactivity attribute from the [session creation response](https://xmpp.org/extensions/xep-0124.html#session-response) (bosh). I would add a property to the BOSH prototype (similar as ``wait``) and set it in [bosh.js#L392](https://github.com/strophe/strophejs/blob/master/src/bosh.js#L392). Any thoughts? Interested in a pr?

**Comment by jcbrand** [comment]
Sure, please make a PR.
