### ISSUE TITLE
Register user from web client using locally hosted openfire 

### ISSUE THREAD

**Issue by anomepani** [strophe/strophejs#22]
when I try to register from web client  using locally hosted openfire I got registration failed without any error notification or error stanza .
What is the reason behind this registration failed?
I have response of message below:

SENT: &lt;body rid='2426896877' xmlns='http://jabber.org/protocol/httpbind' to='localhost' xml:lang='en' wait='60' hold='1' content='text/xml; charset=utf-8' ver='1.6' xmpp:version='1.0' xmlns:xmpp='urn:xmpp:xbosh'/>
RECV: &lt;body xmlns='http://jabber.org/protocol/httpbind' xmlns:stream='http://etherx.jabber.org/streams' authid='99f5151b' sid='99f5151b' secure='true' requests='2' inactivity='30' polling='5' wait='60' hold='1' ack='2426896877' maxpause='300' ver='1.6'>&lt;stream:features>&lt;mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>&lt;mechanism>DIGEST-MD5</mechanism>&lt;mechanism>JIVE-SHAREDSECRET</mechanism>&lt;mechanism>PLAIN</mechanism>&lt;mechanism>ANONYMOUS</mechanism>&lt;mechanism>CRAM-MD5</mechanism></mechanisms>&lt;compression xmlns='http://jabber.org/features/compress'><method>zlib</method></compression>&lt;bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/>&lt;session xmlns='urn:ietf:params:xml:ns:xmpp-session'/>&lt;/stream:features>&lt;/body>

**Comment by jcbrand** [comment]
AFAICT the response given doesn't indicate failed registration.  The server is responding, saying which auth mechanisms it supports. Will close due to inaction.
