### ISSUE TITLE
Using webpack still requires shimming

### ISSUE THREAD

**Issue by robertjustjones** [strophe/strophejs#220]
Even with the fix of #166  and #199 in v1.2.8, I had to use shimming to get webpack to work.

Note, I'm using this npm module (with the ".js" ) to get v1.2.9.
```
npm install --save strophe.js
npm install --save-dev exports-loader
```

Here's the require magic that works for me. Hopefully it helps others and leads to a clue about how to fix.
```
let Strophe = require("exports?Strophe!strophe.js");
```

**Comment by danyim** [comment]
@robertjustjones I'm also running into a similar issue pairing Strophe with Webpack. How would you use your solution in a Webpack config? Would `let Strophe = ...` go into a rule's loader?

**Comment by jcbrand** [comment]
Should no longer be an issue, the `main` property is set in `package.json` and Strophe uses webpack itself.
