### ISSUE TITLE
Can't get connect status when using strophe in webview(Android webview)

### ISSUE THREAD

**Issue by Soo000** [strophe/strophejs#222]
Hello everyone,

I am using strophe in my html5 page can connect to openfire server, could also can send and received message. but when I using webview (Android Controller), can not get connected status, the code as below:

```
var _conn = new Strophe.Connection(    serverAddress    );
_conn.connect(jid, password, function(status) {
    if (status === Strophe.Status.CONNECTED) {
       alert("ok");
    }
}
```

Does somebody use strophe in webview, please give me some help, Thank you very much !

**Comment by sualko** [comment]
Since there was nobody responding for 6 month, I close this issue.
