### ISSUE TITLE
How to get Chat History of a MUC-Light Room.

### ISSUE THREAD

**Issue by himanshusehgal** [strophe/strophejs#226]
Hi,
I am currently struggling to get Chat Histroy of a MUCLight Room using Strophe.js. I dont want to use the direct MUC plugin. I have used the below approaches:-

Sending the below IQ, but no return in the callback:-
```
<iq type='set' id='mamget1' to='coven@muclight.shakespeare.lit'>
    <query xmlns='urn:xmpp:mam:1' queryid='f27' />
</iq>
```
Sending the below presence but Handler not receiving anything:-
```
<presence from="jid" id="9855" to="roomJID" xmlns="jabber:client">
<x xmlns="http://jabber.org/protocol/muc">
<history maxstanzas="20"/>
</x>
</presence>
```
Please tell the correct approach, i.e the correct IQ to send to the server to retrieve the chat history.
Thanks in advance.

**Comment by sualko** [comment]
Since this is a general xmpp question, I close this issue. Maybe a better place to ask such thinks would be stackoverflow.
