### ISSUE TITLE
Allow _idleTimeout to have a configurable time value

### ISSUE THREAD

**Issue by PaquitoSoft** [strophe/strophejs#228]
Hi!

Regarding the function **_idleTimeout**, there's a fixed value of 100 to wait before executing it:
```
// Call onIdle callback every 1/10th of a second
// XXX: setTimeout should be called only with function expressions (23974bc1)
this._idleTimeout = setTimeout(function() {
    this._onIdle();
}.bind(this), 100);
```

When we start a session with a server, there are a lot messages going back and forward and we would like to lower that value to improve perceived speed for our users.

Thanks.

**Comment by jcbrand** [comment]
You can make it a configurable setting that's passed into `new Strophe.Connection`.

A pull request would be welcome.
