### ISSUE TITLE
Websocket connection failing on latest chrome V56.0.2924

### ISSUE THREAD

**Issue by naveenkd26** [strophe/strophejs#229]
We are using Strophe library to make a websocket connection to MongooseIM server and started observing that the connection is failing with latest version of chrome  V56.0.2924, however the ws connection is good when we use Chrome V55.0.2883/safari/mozilla/IE.

Error we are seeing: WebSocket connection to 'wss://xxx.yyyyyyyyy.com/ws-xmpp' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED

I did debug and found the error object thrown by browser WebSocket object, but that doesn't give me any useful information.

Would someone be able to help me on this.?

Thank you.

**Comment by jcbrand** [comment]
Paste the error traceback and any other debug info you have here.

**Comment by naveenkumard26** [comment]
#### Below are the screenshots of the error object catptured WebSocket errorhandler
-------
>     _onError: function(error) {
        Strophe.error("Websocket error " + error);
        this._conn._changeConnectStatus(Strophe.Status.CONNFAIL, "The WebSocket connection could not be established or was disconnected.");
        this._disconnect();
    },
>
-------
![websocketerror_1](https://cloud.githubusercontent.com/assets/10440617/23034650/209eb148-f442-11e6-83a7-6e9b2c4c89b9.png)
continuation 
![websocketerror_2](https://cloud.githubusercontent.com/assets/10440617/23034681/33737da8-f442-11e6-9242-9188dd492b60.png)


Thank you for looking into this.

**Comment by jcbrand** [comment]
Could it be a TLS certificate issue? What happens when you use a non-TLS websocket connection?

**Comment by naveenkumard26** [comment]
Is there a option in strophe to have initiate a non-TLS websocket connection.?

Another thing I noticed is I am seeing 0 requests headers on the ws connection through chrome, but I see headers for the same connection in Mozilla

Chrome
![chrome](https://cloud.githubusercontent.com/assets/10440617/23038438/a4060448-f44f-11e6-8777-7b29e61dd541.png)

Mozilla
![mozilla](https://cloud.githubusercontent.com/assets/10440617/23038445/a802cbda-f44f-11e6-9a0f-e4faf8afb40d.png)

Does strophe manages these headers by any chance or does the browser takes care of this.?

**Comment by jcbrand** [comment]
For non-TLS, use `ws://` instead of `wss://`

**Comment by naveenkumard26** [comment]
got it, I already tried, no luck :-(

**Comment by naveenkd26** [comment]
We figured it out, the issue got fixed with the latest version of cowboy websocket module. Turns out that the latest version of chrome has brought in changes strengthening the security which is not supported by the old verision of cowboy module. We cam close this issue. Thanks!
