### ISSUE TITLE
strophe with haproxy cors error

### ISSUE THREAD

**Issue by vijayaa** [strophe/strophejs#230]
we using strophe.js with ejabberd server http-bind interface for chat. If strophe directly access the ejabberd http-bind url it works fine. But if go via haproxy we are getting CORS error. Can you please help how to solve this issue

**Comment by sualko** [comment]
I don't know haproxy, but probably this proxy does not set the required CORS headers. Maybe this link helps you: http://johntdyer.com/haproxy/2015/03/05/dynamic-access-control-allow-origin-header-in-haproxy.html

**Comment by vijayaa** [comment]
i have tried this link. But not working

**Comment by sualko** [comment]
It was meant as hint, not as solution. First you should understand what [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) means and then try to fix it in your proxy application.

**Comment by jcbrand** [comment]
A question like this is better suited for StackOverflow.

**Comment by vijayaa** [comment]
the issue is _onIdle request sent by strophe with request payload  <body rid='3104305551' xmlns='http://jabber.org/protocol/httpbind' sid='1ae975cfb1d1227c86ba4ae32e4ef366ab955792'/> 
sometimes rid is repeating if we configure via haproxy and there is a delay in ejabberd response, and haproxy is returning 504 error . Not able to understand why rid is repeating when we configure via haproxy

**Comment by jcbrand** [comment]
How does a repeating rid fit to a CORS error?
