### ISSUE TITLE
Webpack import is broken since v1.2.13

### ISSUE THREAD

**Issue by merildev** [strophe/strophejs#233]
I installed strophejs as a normal dependency using "npm install strophe.js --save" in my project. It used to work smoothly until v1.2.13 where I get a undefined error on the object "Strophe" in a plugin (muc).

I use strophejs with Webpack and I simply do a "import strophe from 'strophe.js'".

Do you know if something changed on this recently?

**Comment by jcbrand** [comment]
Please post the full error traceback here.

**Comment by merildev** [comment]
I get a:
"Uncaught ReferenceError: Strophe is not defined"

Full error:
![screenshot from 2017-02-28 09-45-39](https://cloud.githubusercontent.com/assets/5734722/23400132/cc0e7d7c-fd9a-11e6-8da7-eccd4adbebb6.png)

**Comment by jcbrand** [comment]
The `Strophe` object is set on the `window` (called root) here: https://github.com/strophe/strophejs/blob/master/strophe.js#L29

So it should be defined. Can you perhaps put a breakpoint there and see whether `Strophe` is properly defined and what `root` is?

What's new about 1.2.13 is that it's now an almond.js build and that Strophe is wrapped as a AMD module, although it can still be used as a non-AMD module (i.e. by setting globals).

Now that I'm writing this... perhaps you're loading it now as an AMD module, in which case `Strophe` is not being set on `window` as the MUC plugin expects. Perhaps you can check whether that's the case?

**Comment by jcbrand** [comment]
Refs https://github.com/strophe/strophejs-plugins/issues/80

**Comment by IL55** [comment]
I have the same problem: we use webpack + babel and I have error message
`Uncaught ReferenceError: Strophe is not defined`
I tried to define `window.Strophe` myself
i.e. 
```
import Strophe from 'strophe.js/strophe';
window.Strophe = Strophe;
import StropheMuc from 'strophejs-plugins/muc/strophe.muc';
```
But it didn't help

So for now I returned to one version back to `1.2.12`, i.e. in package.json
```
    "strophe.js": "1.2.12",
    "strophejs-plugins": "^0.0.7",
```

**Comment by iceyu07** [comment]
use new window.Strophe instead of newStrophe

**Comment by devilankur18** [comment]
As of 1.2.16 this is working 

```
import { Strophe } from 'strophe.js';
```
