### ISSUE TITLE
Log is a noop

### ISSUE THREAD

**Issue by blackChef** [strophe/strophejs#244]
Strophe captures errors inside itself silently, which makes it very hard to debug. 
I look up the code, and find this line:

> log: function (level, msg) {
        return;
    },
    https://github.com/strophe/strophejs/blob/master/src/core.js#L833

Inside strophe, `warn`, `error`, `fatal` all use this `log`, which obviously is a noop. I don't understand the intention here.

**Comment by sualko** [comment]
I think it is quite clear from the [documentation](http://strophe.im/strophejs/doc/1.2.9/files/strophe-js.html#Strophe.log).

**Comment by blackChef** [comment]
@sualko  Thanks for quick reply. Since it's not like a well known pattern for library consumers, I would strongly suggest a getting start section in documentation.

**Comment by sualko** [comment]
@jcbrand would this be something for the wiki?

**Comment by jcbrand** [comment]
@sualko There is no wiki.

The intent of the `log` method is explained in a docstring above the source code that @blackChef actually linked to (and from that docstring the docs are generated).

If we want to make it more visible, the README can be updated to have a "logging" section.

**Comment by sualko** [comment]
> There is no wiki

There it is: https://github.com/strophe/strophejs/wiki

**Comment by jcbrand** [comment]
@sualko It's empty, which to me comes down to the same thing.
