### ISSUE TITLE
item-not-found error caused by long term request

### ISSUE THREAD

**Issue by petrovy4** [strophe/strophejs#25]
If the first request (not an empty polling request) from queue hangs (does not get response immediately because of request size, network delay, whatever), then it makes possible to send as many subsequent requests from queue as possible till the first request gets response at last. This, in turn, is causing session drop with item-not-found error (http status 404).

This is caused by calling ```_processRequest()``` directly from ```_onIdle()``` instead of calling ```_throttledRequestHandler()``` (here is fix):

```Diff
3572c3572
<             this._throttledRequestHandler();
---
>             this._processRequest(this._requests.length - 1);
```

**Comment by jcbrand** [comment]
I took a look at this ticket and at the code and the change looks sane.

The line in question is [here](https://github.com/strophe/strophejs/blob/84bad355b026d0c2eddae1f4757b1e3ad0b28a53/strophe.js#L4258).

```
this._requests.push(
        new Strophe.Request(body.tree()
                        this._onRequestStateChange.bind(
                                 this, this._conn._dataRecv.bind(this._conn)),
                        body.tree().getAttribute("rid")));
this._processRequest(this._requests.length - 1);
```

The last line should apparently be replaced with `this._throttledRequestHandler()`

`this._requests.length` can be either 1 or 2.

In the situation where the bug arises, there would be two requests. The first one which is hanging and then a  new request to be made.

If you call `this._throttleRequestHandler`, then the first request will be processed first (via `this._processRequest`) and then the second, granted that it's not outside of the window (the max allowed spread between RID numbers).

See [here](https://github.com/strophe/strophejs/blob/84bad355b026d0c2eddae1f4757b1e3ad0b28a53/strophe.js#L4629)

```
if (this._requests.length > 0) {
    this._processRequest(0);
}

if (this._requests.length > 1 &&  Math.abs(this._requests[0].rid -  this._requests[1].rid) < this.window) {
    this._processRequest(1);
}
```

This is different to how things were done up to now, i.e. the 2nd request was processed and the 1st one ignored. Hence the bug.

I've tested this fix with converse.js and everything looks in order.

I'll push out the fix now. If anyone knows of any reason why this fix is not a good idea, please let me know.
