### ISSUE TITLE
Any plan to publish 1.2.5+ on npm?

### ISSUE THREAD

**Issue by marcofanch** [strophe/strophejs#253]
We are using strophejs through npm in our project.
Until recently we need the support of cookies (withCredentials), we found that the latest versions were not published.

So I wonder why strophejs was not published since 1.2.4.
Do you have any plan to publish the "missing" versions?

Thanks in advance.

**Comment by sualko** [comment]
You probably use the Strophe package, but it was renamed to [Strophe.js](https://www.npmjs.com/package/strophe.js).

**Comment by marcofanch** [comment]
Oops, my mistake, didn't aware.
Thanks!
