### ISSUE TITLE
Node.js require(strophe) issue

### ISSUE THREAD

**Issue by jonator** [strophe/strophejs#256]
When I use
`var strophe = require("strophe.js")`

The package is not set in the global scope requiring me to do:
`var Strophe = strophe.Strophe;`
so that Strophe doesn't go undefined.

The problem:
When I want to use a plugin (mam), the strophe.js require scope makes Strophe unable to define Strophe within "strophejs-plugin-mam"

How can I correctly import strophe to use on node.js?

**Comment by jcbrand** [comment]
Some time ago (about 2 years ago IIRC) Strophe was updated to be a UMD module. Some plugins however (like strophe-plugin-mam) expect Strophe to be loaded the old-school way with a <script> tag and for it to set `Strophe` on the global scope.

Strophe still does this if `require` is not used, so strophe-plugin-mam works in those cases.
But in your case I think this expectation of strophe-plugin-mam is causing issues, so I think *it* needs to be updated/fixed.

However, what complicates matters further is that you're using Node.js, which uses CommonJS for module loading, not AMD/UMD. I'm not sure how it is that Strophe works at all there, my Node.js knowledge is limited. Strophe.js is intended to be used as a front-end/browser library, with Node.js support being a dim afterthought.

If it can be made to work well on Node, that's of course a plus, but I'm personally not going to spend time and energy on that. Pull requests are of course welcome in that regards.

You might want to take a look at [node-xmpp](https://github.com/node-xmpp/node-xmpp).

**Comment by sualko** [comment]
> Some plugins however expect Strophe to be loaded the old-school way

This means there are other plugins which doesn't expect Strophe on the global scope. Can you name one? Because then I can start updating others.

**Comment by jcbrand** [comment]
> This means there are other plugins which doesn't expect Strophe on the global scope

Pretty much all plugins that are *not* written as UMD modules expect Strophe on the global scope, which works fine if you're not loading Strophe and the plugins as AMD modules, but as soon as you do, then those plugins break.

**Comment by sualko** [comment]
Ok, I found (strophe.pubsub.js)[https://github.com/strophe/strophejs-plugin-pubsub/blob/master/strophe.pubsub.js#L19] as example.

I also found an [node/amd/browser example](https://github.com/umdjs/umd/blob/master/templates/returnExports.js) which maybe could also solve #233. Any thoughts on this?

**Comment by jcbrand** [comment]
Concerning #233, I think it's basically the same issue as here. In other words, the MUC plugin expects a global `Strophe` but I think they have webpack configured to load Strophe via AMD which means the global is not there.

So a fix there would be to update the MUC plugin to be a UMD module (I mentioned this in the ticket), similarly as a fix here would be to update the MAM plugin.

That browser example you linked to looks promising as it appears to address all three cases (old-school, AMD and CommonJS). I'm still not really sure how `require("strophe.js")` currently works with Node when we don't have explicit CommonJS support.

Then there's of course the option of ES2015 modules. I wonder if it's not a better approach to rather just add Babel and then update Strophe.js to use ES2015 modules and syntax.

This would allow modern Javascript libraries to import modules directly, while we could still create a build of Strophe that is in UMD format (webpack can do this AFAIK).

Downside is that this doesn't necessarily solve the issue of plugins expecting a global `Strophe` obj. :)

**Comment by omichelsen** [comment]
I have started work packaging all the Strophe plugins to UMD modules as we need it for almost all platforms (webpack, Node.js, React Native etc.).

I have created PRs for a couple already (e.g. https://github.com/strophe/strophejs-plugin-disco/pull/1). If we can agree on this format I'd be happy to continue adding this packaging to the remaining plugins.

**Comment by jcbrand** [comment]
Awesome! I'm happy with the approach.
