### ISSUE TITLE
register a new account

### ISSUE THREAD

**Issue by xiaoxinba** [strophe/strophejs#258]
when i use strophe.register.js register a account to ejabberd, result :
 `<error code='403' type='auth'><forbidden xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Denied by ACL</text></error>`

help me ???

**Comment by jcbrand** [comment]
Not relevant to this issue tracker.
