### ISSUE TITLE
One-line bugfix: websocket plugin sends invalid data to the xmlOutput listener

### ISSUE THREAD

**Issue by Gilead** [strophe/strophejs#259]
https://github.com/strophe/strophejs/blob/87714a9804a2ed6e84d5086fda9d51c4778d2737/src/websocket.js#L293

This line in the _disconnect function should be:

```this._conn.xmlOutput(close.tree());```

For example, the stream management plugin currently chokes when it's fed a builder it doesn't expect.

**Comment by jcbrand** [comment]
Looks like you're right. Please create a pull request for it.
