### ISSUE TITLE
Strophe onClose() not firing as I would expect it.

### ISSUE THREAD

**Issue by GDehnke-Turpin** [strophe/strophejs#261]
So, I am implementing strophe into a simple chat application, I have everything wired up and its working great, just as I expected it. But, it has one issue that I have noticed, and that is, the _onClose() binded event for the websockets does not fire off when I literally take out the Ethernet cable of my PC to kill all connection.  I know Chrome has some sort of 60 second timeout, and FireFox has the ping/pong approach, but for some darn reason, I cannot get the _onClose() to fire when I try to kill all "internet" connections to the client when I yank out my cat6 cable. 

Has anyone else ran into this network issue? 

Any help would be appreciated.

**Comment by rj33** [comment]
Generally speaking cutting a physical connection doesn't cut the logical connection, as this behaviour allows the operating system to keep connections up in the face of short term connectivity issues between the endpoints.

On most operating systems, until you put something on the wire you'll not start to get notified of a problem with the connection. You'll probably need to implement your own application level ping/pong (via XMPP's Ping extension or some other mechanism) to detected "I've just ripped out my ethernet cable" events in a timely manner.
