### ISSUE TITLE
Offline Message Callback in StropeJS

### ISSUE THREAD

**Issue by npadhy** [strophe/strophejs#262]
What is the Callback for receiving offline messages from openfire?

I have enabled offline message in openfire server setting. 
Enabled Below Setting
  | Always Store - Always store messages, even if the max storage size has been exceeded.
    Per-user offline message storage limit:  100000.00 KB

If the user is online, then I am able to receive the message from Strophe Js msg receiver Callback. But if user offline then online back then unable to receive offline messages from existing Strophe Js msg receiver Callback.
Is there any other callback/Strophe Plugin to fetch offline messages?

Any help appreciated.

**Comment by jcbrand** [comment]
Double check whether the offline messages are stored as per [XEP-0313 Message Archive Management](https://xmpp.org/extensions/xep-0313.html) and if so, then you'll probably want to use this plugin (core strophe doesn't support it): https://github.com/strophe/strophejs-plugin-mam

**Comment by sualko** [comment]
Offline messages are just messages with a delayed delivery, so you should be able to use the same handler as for "normal" messages. Please check  if those messages arrive and if you already registered your message handler at this time.
