### ISSUE TITLE
Module bundling

### ISSUE THREAD

**Issue by saeedseyfi** [strophe/strophejs#263]
Hi,

Due to #224 I started requiring `strophe.js` but I get an error in building my js (using browserify):
`Error: Cannot find module 'strophe' from '/node_modules/strophe.js'`

It seems you're requiring `strophe` in  `strophe.js` :/
```
...
require(["strophe-polyfill"]);
    /* jshint ignore:start */
    //The modules for your project will be inlined above
    //this snippet. Ask almond to synchronously require the
    //module value for 'main' here and return it as the
    //value to use for the public API for the built file.
    return require('strophe');
}));
/* jshint ignore:end */
...
```

**Comment by jcbrand** [comment]
If you want to create a bundle containing strophe, then include the individual files in the `src` directory, instead of the `strophe.js` bundle.

That said, the `strophe` module which is `require`d is defined just above the code snippet you pasted.

See here: https://github.com/strophe/strophejs/blob/ea459e987cc166b33a33efa99cac9b02beb12a98/strophe.js#L6324

IIRC, this isn't done manually by anyone, but by r.js and almond, the build tools.

**Comment by saeedseyfi** [comment]
@jcbrand thanks for your response.
In this way which file should I `require`? `wrapper.js`?

Is there any fork of strophe that support browserify?
If not please let me know, I can add browserify support to strophe in a pull request.

**Comment by jcbrand** [comment]
@saeedseyfi What would you need to add in order to have browserify support? The modules are already in UMD format, which should work with browserify.

**Comment by saeedseyfi** [comment]
@jcbrand 
- As I mentioned above, I could not require strophe like `require('strophe.js')` and I got the error.
- Strophe and strophe/wrapper export nothing (`module.exports`) and we must use `window.Strophe` that is not the best way when we're using RequireJs/Browserify/... .

So it's not working normally with browserify.

I think it should work if I export `root` so I can access `Strophe`/`$iq`/... like this:
```
var strophe = require('strophe.js');
var Strophe = strophe.Strophe;
var $iq = strophe.$iq;
```

**Comment by jcbrand** [comment]
> As I mentioned above, I could not require strophe like require('strophe.js') and I got the error.

Yes, and I replied that you should include the individual files in `./core/` not the bundle.

How would you call `module.exports` without breaking compatibility with non-browserify setups?

**Comment by saeedseyfi** [comment]
@jcbrand I tried to keep both browserify and non-browserify support but I couldn't. I created the [browserify version](https://github.com/saeedseyfi/strophejs.browserify) for my own use.
Now I have the same problem with srophejs plugins :((

**Comment by jcbrand** [comment]
Almond is only used in the build file. If you instead use the individual files in the `./src` directory then almond is not included.

**Comment by saeedseyfi** [comment]
@jcbrand I added browserify support in #266, please review.
