### ISSUE TITLE
_OnError pulling down current websocket connection when errors arrive on previously closed websocket.

### ISSUE THREAD

**Issue by rj33** [strophe/strophejs#268]
I've been tracking an issue I've had with trying to implement disconnecting/reconnecting after a failure to respond to ping's (when using websockets to ejabberd).  I'd disconnect after ping failure, then connect again and this would initially work, but the reconnected socket would then be disconnected one more time shortly after connection, and I'd have to reconnect again. 

So doing the following:

Start application
Turning off wireless
Wait a few seconds
Turning wireless back on

Would produce the following sequence:
- Ping fails after wireless turned off 
- Manual call to disconnect.
- Disconnect state correctly notified.
- Application attempts to connect again.
- Connect succeeds
- Error received, causing Strophe's default _onError listener to disconnect the connection again.
- Disconnected state reached
- Application attempts to connect again
- Connection succeeds, and this time stays connected.

The error raised in _onError that triggers the problem is:
WebSocket connection to 'wss://example.com/websocket' failed: Data frame received after close
This is on Chrome, from what I can gather , other browsers may not raise this, and Chrome may only raise it with the devtools open, although that didn't seem to be required for me.

It turns out that what is happening here is the websocket onError handler which is routed to the strophe _onError function is still connected to the old socket. When the network is brought back up, ejabberd appears to try to send something down the old socket, which Chrome detects, and sends an error to the still connected error handler, this then brings down the newly created connection as _onError treats the error as fatal and starts another disconnect cycle.

There appears to be two ways of fixing this, one is to add a check at the top of the _onError function that checks to see if this.socket == error.currentTarget and return without taking any action if that is not the case. this.socket may be null here depending on how soon after
_closeSocket() was called.

The other option is to change _closeSocket() to look like this:
```javascript
    _closeSocket: function () {
        if (this.socket) { try {
            this.socket.onerror = null;
            this.socket.close();
        } catch (e) {} }
        this.socket = null;
    },
```

Where this.socket.onerror = null; has been added which stops the error notifications on the no longer relevant socket from getting delivered to _onError. I think this one seems the better fix, but I'm no expert on Strophe websocket handling.

**Comment by jcbrand** [comment]
Thanks for the detailed report.

I agree with you that the second option of deregistering the `onerror` event handler is the better fix.

Would you mind making a pull request?

**Comment by rj33** [comment]
Made a pull request.

**Comment by jcbrand** [comment]
Thanks!
