### ISSUE TITLE
Populate element ...

### ISSUE THREAD

**Issue by satanasov** [strophe/strophejs#27]
Hello guys.

I have a noob question - I'm working on ban list admin tool. Can someone tell me how is the response from the iq request parsed, as I need to populate the list. I've managed to create the iq request and to recieve the list of baned users ... but how and more precisly where can I populate the table?

**Comment by jcbrand** [comment]
@satanasov I guess you eventually figured this out, would you care to post the solution here? Thanks.

**Comment by jcbrand** [comment]
I think what you were looking for is this: https://github.com/strophe/strophejs/blob/master/src/core.js#L1954

**Comment by satanasov** [comment]
This was so long ago that I have forgotten how I did it.
