### ISSUE TITLE
Is there any way to deregister a user?

### ISSUE THREAD

**Issue by sunojvijayan** [strophe/strophejs#272]
Hi, I am trying to deregister a user from ejabbered. Is it possible from Strophe?

**Comment by jcbrand** [comment]
Perhaps if the XMPP server supports it as a Ad-Hoc command https://xmpp.org/extensions/xep-0050.html

However, I'm not aware that Ejabberd does support it and I'm not aware of any other way to do it via the protocol.

Generally this is done on the server itself (via admin panel or CLI).
