### ISSUE TITLE
How to work with stropheJS in reactJS app

### ISSUE THREAD

**Issue by lt1030** [strophe/strophejs#273]
I am trying to connect to a xmpp server using StropheJS library but can't figure out the right way to integrate it in my reactJS app.
The code is like this:

import { Strophe } from 'strophe.js';

componentWillMount() {

    this.setState({
      conn: new Strophe.Connection('http://120.55.161.211:7070/http-bind/')
    });

  }

componentDidMount () {

    const { ERROR, CONNECTING, CONNFAIL, AUTHENTICATING, AUTHFAIL, CONNECTED, DISCONNECTED, ATTACHED, CONNTIMEOUT} = Strophe.Status;

    this.state.conn.connect('test-01@test', '123456', (status) => {
      switch(status) {
        case ERROR:
          console.log('ERROR');
          break;
        case CONNECTING:
          console.log('CONNECTING');
          break;
        case CONNFAIL:
          console.log('CONNFAIL');
          break
        case AUTHENTICATING:
          console.log('AUTHENTICATING');
          break
        case AUTHFAIL:
          console.log('AUTHFAIL');
          break
        case CONNFAIL:
          console.log('CONNFAIL');
          break
        case CONNECTED:
          console.log('CONNECTED');
          break
        case DISCONNECTED:
          console.log('DISCONNECTED');
          break
        case ATTACHED:
          console.log('ATTACHED');
          break
        case CONNTIMEOUT:
          console.log('CONNTIMEOUT');
          break
        default:
          console.log('default');
          break;
      }
    });
}

The result only shows 'CONNECTING',
I don't know what happened?

**Comment by lt1030** [comment]
If use MockJS in react, the MockXmlHttpRequest will replace XmlHttpRequest, so the real request not work.

**Comment by sharifxu** [comment]
i've come around to having the same issue, what to do?, not a clue :/

though i've got my own server running in a VM with XMPP in prosody, also bypassed the CORS issue using proxy method [https://create-react-app.dev/docs/proxying-api-requests-in-development/#configuring-the-proxy-manually](here), this worked in a similar fashion to the CORS bypass chrome extensions, so it rules out being a CORS issue.

any ideas anyone? i'm believing its something to be configured for BOSH in the XMPP server.

**Comment by sharifxu** [comment]
nevermind, i've manage to figure out my issue. 

it was my server settings, as I was not using BOSH over a secured protocol (in local development), i've had to just disabled the settings which force encrypted  connections, also removed SSL settings.
