### ISSUE TITLE
Retrive Chat History 

### ISSUE THREAD

**Issue by pratikshivlab** [strophe/strophejs#279]
Hello, how to write below query in strophejs

`<iq type='get' id='pk1'>
       <list xmlns='urn:xmpp:archive'
               with='test@localhost'>
        <set xmlns='http://jabber.org/protocol/rsm'>
            <max>30</max>
        </set>
      </list>
   </iq>`

is it used for load chat history  ?

**Comment by jcbrand** [comment]
Take a look at the MAM plugin: https://github.com/strophe/strophejs-plugin-mam
