### ISSUE TITLE
Get users presence or how to check perticular user is online or not.

### ISSUE THREAD

**Issue by Veerbhadra277** [strophe/strophejs#280]
Hi,

I am using strophejs web client with ejabberd xmpp server, and i am using chat application only for one to one communication, let say I logged in as user1 and want to chat with user2, in this scenario I do know whether user2 is online or offline.

Being User1 how do I know other users to which I am chating are online/offline,

Thanks in advance !

-Veer

**Comment by jcbrand** [comment]
Sorry but there isn't enough manpower around here to answer support questions such as this one.

Get yourself a copy of [Professional XMPP](http://professionalxmpp.com) and read it.

**Comment by Princejain21** [comment]
hey
can anyone help to get those user list with whom we have chatted earlier. i'm using strophe client and xmpp server.

Thanks in advance !
