### ISSUE TITLE
Problem connecting to a clustered XMPP server

### ISSUE THREAD

**Issue by jigarzon** [strophe/strophejs#286]
When connecting to a clustered Tigase XMPP Server with bosh, Strophe connects directly to the load balancer instead of the assignated node.
With another client, for example PSI, it first connects to the server and after the first response that includes the host to use, it starts to connect to that server.

But strophe seams to ignore the host data of the first stanza and continues connecting to the loadbalancer.

**Comment by jcbrand** [comment]
Can you post the stanza which indicates the host that strophe needs to connect to? Or perhaps link to the relevant XEP (and the relevant example in the XEP)?

**Comment by jigarzon** [comment]
Sorry @jcbrand it was a mistake from my side. The load balancing should be transparent, I thougth PSI was taking the host attribute of the first stanza, but I discovered it was not the case.
Its a problem with bosh and balancing, the loadbalancer has to be smart enough to deliver that connection always to the same node, and at least in amazon, the loadbalancer hasnt that inteligence.
