### ISSUE TITLE
Use strophe library in angular2

### ISSUE THREAD

**Issue by mantukhannaonly** [strophe/strophejs#287]
Hi,

I am developing chat application using strophe library and openfire server in Angular 2. Is there any NPM package available for strophe in Angular 2 ?

Thanks,
Sanjeev

**Comment by jcbrand** [comment]
Not that I'm aware of.

**Comment by mantukhannaonly** [comment]
Thanks!!. 
I am using websocket connection using strophe library on openfire server.  Getting issue on net disconnection. Disconnection is not executing on net disconnection.  It is working fine in http connection.
