### ISSUE TITLE
Load Strophe in React Native - Unable to resolve module `strophe`

### ISSUE THREAD

**Issue by flavio-dev** [strophe/strophejs#289]
Hello, I would like to require strophe.js into my React Native code.

I created a WebView in order to get a window context. Then I create the window.document that way:
```
import xmlDom from 'xmldom'
...
window.document = new xmlDom.DOMParser().parseFromString('<xml></xml>', 'text/xml')
```
so at that point in my code I have everything required for the Strophe to be picked up. What I want to do is:
```
const Strophe = require('strophe.js')
```
and then potentially a 
```
window.Strophe = Strophe
```
if required.

The `require('strophe.js')` triggers a 
```
error: bundling failed: Error: Unable to resolve module `strophe` from `/blabla..../node_modules/strophe.js/strophe.js`: Module does not exist in the module map
```

But why? Anyone else having a similar problem?

**Comment by karthikeayan** [comment]
may be you need this

```
window.DOMParser = require('xmldom').DOMParser;
window.document = new DOMParser().parseFromString("<?xml version='1.0'?>", 'text/xml');
import './lib/strophe.js'
const Strophe = window.Strophe;
```

**Comment by karthikeayan** [comment]
```
window.DOMParser = require('xmldom').DOMParser;
window.document = new DOMParser().parseFromString("<?xml version='1.0'?>", 'text/xml');
import './lib/strophe.js'
const Strophe = window.Strophe;
```

works for me

**Comment by akshgods** [comment]
@karthikeayan  and @flavio-dev  i wanted to do same , as new b in react native, i'm not getting how to integrate it correctly to work.
 can you share code ,any repository of yours .

**i added this lines:**
import React, { Component } from 'react';
import { Text, View } from 'react-native';
import xmlDom from 'xmldom';
window.DOMParser = require('xmldom').DOMParser;
window.document = new DOMParser().parseFromString("", 'text/xml');
import '../library/strophe';
const Strophe = window.Strophe;

**at build time im getting this error:**
Loading dependency graph, done.
error: bundling failed: Error: E:\react\octacat\library\strophe.js:6395:0: calls to require expect exactly 1 string literal argument, but this was found: require(["strophe-polyfill"]).

**Comment by sualko** [comment]
In my typescript setup (with webpack) I use the following:

```
import * as StropheLib from 'strophe.js'

export let $iq: (attrs?: any) => Strophe.Builder = StropheLib.$iq;
export let $build: (name: string, attrs?: any) => Strophe.Builder = StropheLib.$build;
export let $msg: (attrs?: any) => Strophe.Builder = StropheLib.$msg;
export let $pres: (attrs?: any) => Strophe.Builder = StropheLib.$pres;
export let Strophe = StropheLib.Strophe;
export let NS = StropheLib.Strophe.NS;
export let Status: Status = StropheLib.Strophe.Status;
```

Maybe it's helpful for you.

**Comment by karthikeayan** [comment]
```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
window.DOMParser = require('xmldom').DOMParser;
window.document = new DOMParser().parseFromString("<?xml version='1.0'?>", 'text/xml');
import './lib/strophe.js'
const Strophe = window.Strophe;
```

**Comment by filipef101** [comment]
Regarding this and #115 

This is my end result of loading Strophe in react native, should work for other pure js enviroments.

Also, to use typescript with muc I had to copy the muc.d.ts from there to my types folder as it was not recognizing the connection.muc type

```ts
// strophe hacks
window.DOMParser = require('xmldom').DOMParser;
(window as any).document = new DOMParser().parseFromString("<?xml version='1.0'?>", 'text/xml')
import { decode, encode } from 'base-64'
if (!(global as any).btoa) {
  (global as any).btoa = encode
}
if (!(global as any).atob) {
  (global as any).atob = decode
}

import * as StropheLib from 'strophe.js'
export let $iq = StropheLib.$iq
export let $build = StropheLib.$build
export let $msg = StropheLib.$msg
export let $pres = StropheLib.$pres
export let Strophe = StropheLib.Strophe
export let NS = StropheLib.Strophe.NS
export let Status = StropheLib.Strophe.Status
```
