### ISSUE TITLE
AMD Support

### ISSUE THREAD

**Issue by lboynton** [strophe/strophejs#29]
I created a pull request in the old repository for AMD support (https://github.com/metajack/strophejs/pull/99). Is this something that people are interested in? I can rebase my changes on the current master if so and submit a PR.

**Comment by jcbrand** [comment]
I tried to rebase @lboynton's changes but found it easier to rather just add AMD support from scratch. My changes are now in the [amd-merge](https://github.com/strophe/strophejs/tree/amd-merge) branch.

I've tested both the AMD and non-AMD usecases with converse.js and all looks fine. All tests also pass.

After @Gordin has released version 1.1.4 I'll merge that branch with master.

**Comment by Gordin** [comment]
@jcbrand If this does not break compatibility with anything I'd like to just include this in the next release. Is there any reason not to do this?

**Comment by jcbrand** [comment]
@Gordin Suits me fine if we include it in the next release. It's still backwards compatible and my main reason for waiting was just to be conservative.

**Comment by jcbrand** [comment]
@Gordin I've submitted a pull request. Please merge if you're happy with it.

**Comment by isfarax** [comment]
Hi Guys,

This is great stuff. Thank you so much. I shall check it out, good idea to release it with the new version 1.1.4.

**Comment by Gordin** [comment]
This is now included in the current 1.2.0 release.
