### ISSUE TITLE
XEPs support page with version for main and plugins

### ISSUE THREAD

**Issue by Neustradamus** [strophe/strophejs#292]
It is possible to have a XEPs support page with version for strophejs and strophejs-plugins?
RFCs in more of course.

Examples:
- https://metronome.im/supported-xeps-list
- https://trac.gajim.org/wiki/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by jcbrand** [comment]
Strophe.js implements the core XMPP RFCS and no XEPs except for the BOSH and Websocket support. This is already mentioned in the README.

The plugins are listed here: https://github.com/strophe/strophejs-plugins

**Comment by Neustradamus** [comment]
RFCs up-to-date?
Version of XEPs are not here: https://github.com/strophe/strophejs-plugins

**Comment by Neustradamus** [comment]
Note: It is not possible to create issues on https://github.com/strophe/strophejs-plugins.
Can you reopen this ticket?
