### ISSUE TITLE
XEP-0387: XMPP Compliance Suites 2018

### ISSUE THREAD

**Issue by Neustradamus** [strophe/strophejs#293]
Please add support of https://xmpp.org/extensions/xep-0387.html

**Comment by jcbrand** [comment]
Out of scope for strophe.js, which only implements the core spec.

**Comment by Neustradamus** [comment]
But it is not noted what RFCs :)

**Comment by jcbrand** [comment]
You're welcome to make a PR which adds the RFCs, there are only two.

**Comment by Neustradamus** [comment]
- https://tools.ietf.org/html/rfc3920 -> https://tools.ietf.org/html/rfc6120 -> https://tools.ietf.org/html/rfc7590
- https://tools.ietf.org/html/rfc3921 -> https://tools.ietf.org/html/rfc6121
- https://tools.ietf.org/html/rfc6122 -> https://tools.ietf.org/html/rfc7622
- https://tools.ietf.org/html/rfc7395
- https://tools.ietf.org/html/rfc7590
...
