### ISSUE TITLE
Strophe.Builder doesn't result in namespaceURI being set

### ISSUE THREAD

**Issue by bbaldino** [strophe/strophejs#294]
If you create a presence message like so:

```
const pres = $pres({
    to: 'tojid',
    from: 'fromjid'
})
.c('x', { xmlns: 'http://jabber.org/protocol/muc#user' })
    .c('item', {
        jid: 'jid-attr',
        affiliation: 'affiliation-attr',
        role: 'role-attr'
    })
    .up()
.up()
.tree();
```
The following search will fail:
```
pres.getElementsByTagNameNS('http://jabber.org/protocol/muc#user', 'x')[0];
```
because `getElementsByTagNameNS` (and similar namespace searches) search via `namespaceURI`,  which is a read-only variable calculated from the node's creation (see [here](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS)).

I think this could be as simple as adding a check for the `xmlns` attribute and changing the call to `createElement` [here](https://github.com/strophe/strophejs/blob/3ae1a43a7afb7e839c6a2272fc24f9dc60441805/src/core.js#L446) to instead use `createElementNS`, but I haven't had a chance to actually verify that.  I will take a shot at opening a PR when I get a chance, but wanted to at least file this.

**Comment by jcbrand** [comment]
Thanks for the info. Best approach would be to write a test that fails currently and then passes with your proposed change. Such a PR would be very welcome!

**Comment by bbaldino** [comment]
Thanks @jcbrand, working on that now but `make check` doesn't seem to be running the tests, am I missing something there?

```
[bbaldino@CLI-4759 strophejs (master)]$ make check
./node_modules/.bin/jshint --config jshintrc src/*.js
./node_modules/.bin/phantomjs node_modules/qunit-phantomjs-runner/runner-list.js tests/index.html
[bbaldino@CLI-4759 strophejs (master)]$
```
I added a test which does `equal(1, 2)` and nothing failed.  I also tried adding `equal(1, 2)` to an existing test, but that didn't show any failure either.

**Comment by jcbrand** [comment]
Oh, looks like it was a PhantomJS issue. I updated to the latest version of PhantomJS and the associated test-runner and now the tests run again.

Can you please check again?

**Comment by bbaldino** [comment]
I ran into an issue there:
```
npm ERR! notarget No compatible version found: phantomjs-prebuilt@2.1.1
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.1.16, 2.1.15, 2.1.14, 2.1.13, 2.1.12, 2.1.12-alpha, 2.1.11, 2.1.11-alpha.1, 2.1.11-alpha, 2.1.10, 2.1.9, 2.1.8, 2.1.7, 2.1.6, 2.1.5, 2.1.4, 2.1.3, 2.1.2
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'strophe.js'
npm ERR! notarget
```
I guessed that maybe you meant `2.1.11`, so I changed the dependency to that and then things worked.

**Comment by jcbrand** [comment]
I completely removed phantomjs last night (in favour of Chromium embedded). Are you sure you're using the latest code?

**Comment by bbaldino** [comment]
Oh, I guess I didn't.  But now I get:
```
[bbaldino@CLI-4759 strophejs (master)]$ make check
npm install
touch stamp-npm
./node_modules/.bin/jshint --config jshintrc src/*.js
LOG_CR_VERBOSITY=INFO ./node_modules/.bin/run-headless-chromium --no-sandbox http://localhost:8080/tests/
Xvfb not found. Please install xvfb before trying again.
make: *** [check] Error 255
```

**Comment by jcbrand** [comment]
As a workaround... you can simply run `make serve` and then open http://localhost:8080/tests/ in your browser.
