### ISSUE TITLE
how can i reconnect when the network offline change to online?

### ISSUE THREAD

**Issue by DaiHuaXieHuaKai** [strophe/strophejs#295]
how can i reconnect when the network offline change to online?And the connect status is disconnected when the network is offline.

**Comment by jcbrand** [comment]
You want to register a listener for when the connection status changes, you do this when you create a new Strophe.Connection, for example like here:

https://github.com/conversejs/converse.js/blob/61b32fd786f21e9ed89c932a3c8639c3b94764f0/src/converse-core.js#L1722

Then, once Strophe has disconnected, you can handle that and decide whether to try and reconnect again or not. This is how converse.js does it:

https://github.com/conversejs/converse.js/blob/61b32fd786f21e9ed89c932a3c8639c3b94764f0/src/converse-core.js#L497
