### ISSUE TITLE
Capture requests

### ISSUE THREAD

**Issue by jigarzon** [strophe/strophejs#296]
Hi I need to capture outgoing and incoming request, as the initial auth message slightly changes on my server.
I tryied to use a custom plugin and a handler. But none of these seem to work to process sent messages, they work fine for capturing received messages.
How would be the right procedure to do this?

Sorry if this is not an issue, I asked on the mailing list but no one has even read my message.
Thanks

**Comment by jcbrand** [comment]
You can monkey patch Strophe.Connection.send

**Comment by jigarzon** [comment]
Thanks a lot @jcbrand jcbrand, I was using a fork but it was very slow to create deploys and package strophe in a dynamic way, using the github dependency in package.json, etc.... 
With monkey patching it got faster. Thanks!
