### ISSUE TITLE
cannot use stropheJS with typescript

### ISSUE THREAD

**Issue by lifeanddeath** [strophe/strophejs#298]
Hello I want to use this library in my project, in order to do it, I installed following packages,

`npm install --save strophe.js`
`npm install --save @type/strophe`
and then I import the typing with ,
`import {Strophe} from "strophe";` in my ts file.
But when I compile my typescript file,I get the followin error.

> Error: Cannot find module 'strophe'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ahmet/Documents/MasterProject/LocationBasedChatApp/out/index.js:3:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

I've been trying to solve this since forever, any help will be greatly appreciated!

**Comment by jcbrand** [comment]
I know that @sualko has been using Strophe.js with TypeScript, perhaps he can help.

Looks like he made a wrapper for it here:
https://github.com/jsxc/jsxc/blob/refactoring/src/vendor/Strophe.ts

**Comment by jcbrand** [comment]
Refs #223

**Comment by sualko** [comment]
`import * as Strophe from 'strophe.js'` should work, but it will still not find the declaration file. I tried to solve this by myself, but had no luck yet and have currently no time to look into this in more detail.

**Comment by rvleyden** [comment]
We are using it in a ionic/angluar (typescript) project. We declare it in a provider :

import {Strophe} from 'strophe.js';

import {$pres} from 'strophe.js';
import {$iq} from 'strophe.js';
import {$msg} from 'strophe.js';
import {$build} from 'strophe.js';

declare var Strophe: any;

export class ...
private connection: Strophe.Connection;

etc..

We put the Strophe.js file in the assets directory and included it in the index.html in de head after the Cordova.js script inclusion.

Hope this will help you

**Comment by iAakashTomar** [comment]
download the strophe.js zip file via http://strophe.im/strophejs, extract and copy strophe.js and paste it  into your project then navigate to index.html and add the following command:-
`  <script src="your_path/strophe.js"></script>
`

I hope this will help. if dint then tell me

**Comment by StoneCypher** [comment]
The problem you're facing is because there are two distinct projects, `strophe` (deprecated) and `strophe.js` (current).  The reason is that someone else wanted `strophe` on `npm` before the author did, and published the work for them; later, the author took over under the new name.

You're using the types from the current project, but you're using the deprecated project.  Note the difference where one says `.js` and the other does not.  These genuinely do not line up.

Also, because it's been so long, the type file should be removed and reinstalled.

What you should do:

```
npm uninstall --save-dev @types/strophe.js strophe
npm install --save-dev @types/strophe.js strophe.js
```

Then change your `import` to have `.js` accordingly
