### ISSUE TITLE
'no-auth-mech' error. Server did not offer a supported authentication mechanism 

### ISSUE THREAD

**Issue by cryomi** [strophe/strophejs#299]
Hi, using [Version 1.2.15 - 2018-05-21](https://github.com/strophe/strophejs/releases/tag/v1.2.15) I get this error 60/100 login tries. 

but reverting to [Version 1.2.13 - 2017-02-25](https://github.com/strophe/strophejs/releases/tag/v1.2.13) makes login work 100/100.

Successful request/response:
`<body rid="2443939266" xmlns="http://jabber.org/protocol/httpbind" to="server.name" xml:lang="en" wait="60" hold="1" content="text/xml; charset=utf-8" ver="1.6" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh"/>`

`<body xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" xmlns:stream="http://etherx.jabber.org/streams" xmpp:version="1.0" authid="16101207082423124058" sid="51815c89542a95903b4f580a4e843c376390c6a1" wait="60" ver="1.11" polling="2" inactivity="30" hold="1" xmpp:restartlogic="true" requests="2" secure="true" maxpause="120" from="server.name"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms></stream:features></body>`

Unsuccessful request/response:
`<body rid="81635347" xmlns="http://jabber.org/protocol/httpbind" to="server.name" xml:lang="en" wait="60" hold="1" content="text/xml; charset=utf-8" ver="1.6" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh"/>`

`<body xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" xmlns:stream="http://etherx.jabber.org/streams" xmpp:version="1.0" authid="10970073916523766431" sid="7da88d91b5b9d93cdefa8ddb84e04fdbafe0f524" wait="60" ver="1.11" polling="2" inactivity="30" hold="1" xmpp:restartlogic="true" requests="2" secure="true" maxpause="120" from="server.name"/>`

**Comment by jcbrand** [comment]
In the unsuccessful case the XMPP server is not advertising any SASL authentication mechanisms, which is also what the error message is saying. Not much that Strophe.js can do in that case. I don't see anything here that indicates that this problem is due to a difference between versions 1.2.13 and 1.2.15.

The order in which Strophe.js prioritizes SASL auth mechanisms has changed in the latest release, but I don't see how that plays a role if the XMPP server doesn't advertise any SASL auth mechanisms.

The spec defines 3 cases where the XMPP server might not advertise SASL auth mechs (with only two being possibe in this case). See https://tools.ietf.org/html/rfc6120#section-6.4.1

I think the log output you've pasted is not enough to get the full picture. Check also the log output of your XMPP server to see whether it says anything during this exchange.

**Comment by cryomi** [comment]
I have read your link, but anyway it is how it is working for me. The possible cause that TLS/SASL order.

I just checked v.1.2.14 is alsow working stable.

I am not sure what I might provide for you, I created this log
```
converse-authorization.js:603 converse.bosh_service_url:  https://server.bosh.name/http-bind
converse-authorization.js:778 connect
converse-core.js:684 0 _throttledRequestHandler called with 1 requests
converse-core.js:684 0 request id 1.0 posting
converse-core.js:684 0 request id 1.0 state changed to 1
converse-core.js:684 <body rid=​"3076885705" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" to=​"server.name" xml:lang=​"en" wait=​"60" hold=​"1" content=​"text/​xml;​ charset=utf-8" ver=​"1.6" xmpp:version=​"1.0" xmlns:xmpp=​"urn:​xmpp:​xbosh">​</body>​
converse-core.js:684 0 request id 1.1 state changed to 2
converse-core.js:684 0 request id 1.1 state changed to 3
converse-core.js:684 0 request id 1.1 state changed to 4
converse-core.js:684 0 removing request
converse-core.js:684 0 _throttledRequestHandler called with 0 requests
converse-core.js:684 0 request id 1 should now be removed
converse-core.js:684 0 request id 1.1 got 200
converse-core.js:684 1 _connect_cb was called
converse-core.js:684 <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" xmlns:xmpp=​"urn:​xmpp:​xbosh" xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams" xmpp:version=​"1.0" authid=​"11610735865741913031" sid=​"e04ab5961ab9ee31d752b893a86ba49a9df1e408" wait=​"60" ver=​"1.11" polling=​"2" inactivity=​"30" hold=​"1" xmpp:restartlogic=​"true" requests=​"2" secure=​"true" maxpause=​"120" from=​"server.name">​</body>​
converse-core.js:678 ERROR: Server did not offer a supported authentication mechanism
converse-core.js:906 2 "no-auth-mech" undefined
converse-core.js:684 onConnectStatusChangedError: CONNFAIL, no-auth-mech.
converse-core.js:815 reconnect
converse-core.js:684 Attempting to reconnect in 3 seconds
converse-core.js:684 1 _doDisconnect was called
converse-core.js:906 7 "reconnect" undefined
converse-core.js:684 1 Disconnect was called because: reconnect
converse-core.js:684 1 Disconnect was called before Strophe connected to the server
converse-core.js:684 1 _doDisconnect was called
converse-authorization.js:603 converse.bosh_service_url:  https://server.bosh.name/http-bind
converse-authorization.js:778 connect
converse-core.js:684 0 _throttledRequestHandler called with 1 requests
converse-core.js:684 0 request id 2.0 posting
converse-core.js:684 0 request id 2.0 state changed to 1
converse-core.js:684 <body rid=​"490470539" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" to=​"server.name" xml:lang=​"en" wait=​"60" hold=​"1" content=​"text/​xml;​ charset=utf-8" ver=​"1.6" xmpp:version=​"1.0" xmlns:xmpp=​"urn:​xmpp:​xbosh">​</body>​
converse-core.js:684 0 request id 2.1 state changed to 2
converse-core.js:684 0 request id 2.1 state changed to 3
converse-core.js:684 0 request id 2.1 state changed to 4
converse-core.js:684 0 removing request
converse-core.js:684 0 _throttledRequestHandler called with 0 requests
converse-core.js:684 0 request id 2 should now be removed
converse-core.js:684 0 request id 2.1 got 200
converse-core.js:684 1 _connect_cb was called
converse-core.js:684 <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" xmlns:xmpp=​"urn:​xmpp:​xbosh" xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams" xmpp:version=​"1.0" authid=​"12310237386921699293" sid=​"8938aa3cc28e378023e1a93eaff9d433b8c86394" wait=​"60" ver=​"1.11" polling=​"2" inactivity=​"30" hold=​"1" xmpp:restartlogic=​"true" requests=​"2" secure=​"true" maxpause=​"120" from=​"server.name">​</body>​
converse-core.js:678 ERROR: Server did not offer a supported authentication mechanism
converse-core.js:906 2 "no-auth-mech" undefined
```

Maybe you may request any details?

**Comment by cryomi** [comment]
Seems TLS/SASL order issue.
I request DNS resolve for JID part after '@' and get '_xmpp-client._tcp.' value to build BOSH server name (no TLS init ), then request auth features which fails due to https://tools.ietf.org/html/rfc6120#section-6.4.1 'TLS negotiation needs to happen before SASL can be offered'.

I checked diff v.1.2.14/v.1.2.15. Seems while "no-auth-mech" library sent Request again https://github.com/strophe/strophejs/commit/c3b7e8619347ef2b800a3f4943fe64fce6540af1#diff-7edacb52cd3a634d2c5ead393d817a25L5314 and replaced with https://github.com/strophe/strophejs/commit/c3b7e8619347ef2b800a3f4943fe64fce6540af1#diff-7edacb52cd3a634d2c5ead393d817a25R3851 and there no be fix for problem I described?

**Comment by jcbrand** [comment]
Here's the commit where the relevant change was made: https://github.com/strophe/strophejs/commit/ea459e987cc166b33a33efa99cac9b02beb12a98

The commit message explains the reason. Before that change was made, it wasn't possible to communicate to the user why the client couldn't connect, because Strophe.js would just send another poll-request and then there would be no disconnection event, the connection would be in limbo.

In your case it seems the additional poll-request somehow lets a TLS session be set up where before it wasn't set up. What I don't understand is why is this extra poll-request necessary for you and why don't you have TLS set up initially (as you should if you're using HTTPS)?

**Comment by jcbrand** [comment]
What does your server logs say?

**Comment by cryomi** [comment]
Request:
```
 2018-06-19 16:08:20.624 [debug] <0.17038.16>@ejabberd_bosh:wait_for_session:353 got request:
** RequestID: 1026681255
** Request: {body,<<>>,[{'xmpp:version',<<"1.0">>},{ver,<<"1.6">>},{<<"content">>,<<"text/xml; charset=utf-8">>},{hold,1},{wait,60},{<<"xml:lang">>,<<"en">>},{to,<<"OUR_SERVER">>},{rid,1026681255},{<<"xmlns:x
mpp">>,<<"urn:xmpp:xbosh">>}],[],211}
** From: {<0.17037.16>,#Ref<0.0.4718594.97685>}
** State: {state,<<"OUR_SERVER">>,<<"55e54c8d071819b17d5361b9c82661156f6bf1fe">>,{{[],[]},0,unlimited},{{[{xmlstreamstart,<<"stream:stream">>,[{<<"id">>,<<"16934718734172606062">>},{<<"version">>,<<"1.0">>},{
<<"xml:lang">>,<<"en">>},{<<"xmlns:stream">>,<<"http://etherx.jabber.org/streams">>},{<<"from">>,<<"OUR_SERVER">>},{<<"xmlns">>,<<"jabber:client">>}]}],[]},1,unlimited},none,<0.17039.16>,<<"1.0">>,#Ref<0.0.47
18594.97682>,undefined,300,30,0,<<>>,undefined,unlimited,{0,nil},{0,nil},{{[],[]},0,1000},{{86,57,255,94},58962},1}
```

Response:
```
 2018-06-19 16:08:20.624 [debug] <0.17038.16>@ejabberd_bosh:do_reply:722 send reply:
** RequestID: 1026681255
** Reply: {body,<<>>,[{sid,<<"55e54c8d071819b17d5361b9c82661156f6bf1fe">>},{wait,60},{ver,<<"1.11">>},{polling,2},{inactivity,30},{hold,1},{'xmpp:restartlogic',true},{requests,2},{secure,true},{maxpause,120},{'xmlns:xmpp',<<"urn:xmpp:xbosh">>},{'xmlns:stream',<<"http://etherx.jabber.org/streams">>},{from,<<"OUR_SERVER">>}],[{xmlstreamstart,<<"stream:stream">>,[{<<"id">>,<<"16934718734172606062">>},{<<"version">>,<<"1.0">>},{<<"xml:lang">>,<<"en">>},{<<"xmlns:stream">>,<<"http://etherx.jabber.org/streams">>},{<<"from">>,<<"OUR_SERVER">>},{<<"xmlns">>,<<"jabber:client">>}]}],0}
** To: {<0.17037.16>,#Ref<0.0.4718594.97685>}
** State: {state,<<"OUR_SERVER">>,<<"55e54c8d071819b17d5361b9c82661156f6bf1fe">>,{{[],[]},0,unlimited},{{[],[]},0,unlimited},none,<0.17039.16>,<<"1.0">>,#Ref<0.0.4718594.97686>,undefined,60,30,1026681255,<<>>,undefined,unlimited,{0,nil},{0,nil},{{[],[]},0,1000},{{86,57,255,94},58962},2}
```

**Comment by jcbrand** [comment]
Ok, looking at the [XMPP over BOSH XEP](https://xmpp.org/extensions/xep-0206.html), I see the following sentence:

> If no <stream:features/> element is included in the connection manager's session creation response, then the client SHOULD send empty request elements until it receives a response containing a <stream:features/> element.

Which indicates that the previous behavior is what should be done. I won't be able to revert this week, but I'll try to get to it ASAP.

**Comment by cryomi** [comment]
Thanks a lot, I will close this issue after your commit.
