### ISSUE TITLE
Strphe js with openfire Duplicate user session

### ISSUE THREAD

**Issue by pratik-aileensoul** [strophe/strophejs#302]
Hello,
I am use strophes js  and openfire 4.2 for chat.
I got issue when i am login when user name and password server create session for that user and than  reload/refresh page server again create new session for that user.
Help me for the issue.

**Comment by pratik-aileensoul** [comment]
I am use strophes js and openfire 4.2 for chat.
Create custom chat module using strophes js and when user comes on chat page user will automatically login and on server side in openfire admin >> sessions >>client sessions here single session for that user.
Issue is that when i reload/refresh chat page on server side there are multiple session for single user due to multiple session when user send message it will send twice.

**Comment by sualko** [comment]
> Sorry, your issue is not clear to me

Code would be helpful, but as far as I understand you just login twice (in your code).

**Comment by pratik-aileensoul** [comment]
> Code would be helpful, but as far as I understand you just login twice (in your code).

Right.

how to prevent one user to login multiple times ?

**Comment by sualko** [comment]
> how to prevent one user to login multiple times?

Check if a connection exists, if not login. Without any code, I can only give you this general advice.

**Comment by pratik-aileensoul** [comment]
[chat.docx](https://github.com/strophe/strophejs/files/2201383/chat.docx)
My code is here
