### ISSUE TITLE
sendIq fail in large data payload

### ISSUE THREAD

**Issue by doit-ceo** [strophe/strophejs#303]
We need to send large pocket, strophi fail at randomly for anything larger than 1.0 MB , we set the timeout to large number (120000)
We first see 3 of those and the connection drops !

`
strophe.js:formatted:5115 OPTIONS http://domain:7070/http-bind/ 0 ()

`

The root error is at. 
strophe.js 

`

            if (req.sends > 1) {
                // Using a cube of the retry number creates a nicely
                // expanding retry window
                var backoff = Math.min(Math.floor(Strophe.TIMEOUT * this.wait),
                                       Math.pow(req.sends, 3)) * 1000;
                setTimeout(function() {
                    // XXX: setTimeout should be called only with function expressions (23974bc1)
                    sendFunc();
                }, backoff);
            } else {
                sendFunc();
            }

`
I'm not sure what is this, is it for reconnection ? at the time the page send this large pocket , for sure the whole connection will be utilize for this large pocket and the above code will fail. 
![selection_134](https://user-images.githubusercontent.com/8027780/42850081-ba5e8118-8a2e-11e8-858c-5a187c270577.png)
![selection_133](https://user-images.githubusercontent.com/8027780/42849950-2214d5ba-8a2e-11e8-804a-c8ea5d21f3ce.png)

**Comment by sualko** [comment]
I don't know why the connection is canceled, but you should try to increase the [wait and hold value](http://strophe.im/strophejs/doc/1.2.15/files/strophe-js.html#Strophe.Connection.connect) and make sure that the server is accepting those. Do you have any entries in your server log?
