### ISSUE TITLE
How to use "attach" in Stropejs ?

### ISSUE THREAD

**Issue by pratik-aileensoul** [strophe/strophejs#304]
How to use "attach" in Stropejs ?

`$(document).bind('connect', function (ev, data) {
   var conn = new Strophe.Connection('http://127.0.0.1:7070/http-bind/', {sync: true});
    conn.flush();  
    conn.disconnect();

    if(rid == "" && sid == "")
    {
        conn.connect(data.jid, data.password, function (status) {        
            rid = conn.rid;
            sid = conn.sid;
            // console.log(Strophe.Status);
            if (status === Strophe.Status.CONNECTED) {
                login_jid = data.jid;
                set_rsid();
                $(document).trigger('connected');
            } else if (status === Strophe.Status.DISCONNECTED) {
                $(document).trigger('disconnected');
            }
        });
    }
    else
    {
       conn.attach(data.jid, sid, parseInt(rid,10)+1, function (status) {
            console.log(status);
            $(document).trigger('connected');
         },null);
    }    

    Gab.connection = conn;
});`

when first time comes on the page user will auto login with no issue but when user comes second times on this page it give error like image:
![oferror](https://user-images.githubusercontent.com/38644515/42941559-c4be5e1a-8b7a-11e8-9748-278d0a6d7f39.jpg)

**Comment by sualko** [comment]
Is this the follow up from #302? Maybe http://strophe.im/strophejs/doc/1.2.15/files/strophe-js.html#Strophe.Connection.restore is interesting for you. As a general advice, if you like to get help from people who do this in there free time, please take time to format your issue accordingly.
