### ISSUE TITLE
WebSocket connection to 'wss://server:5281/xmpp-websocket' failed: WebSocket opening handshake was canceled _connect 

### ISSUE THREAD

**Issue by vavadiyahiren** [strophe/strophejs#305]
Hello,

I am trying to use wss websocket with storphe js but i am contiusoly getting handshake error.

I am trying to use external scheme and password less login with certificate verify so does it possible to do it with storphe js or any demo available.

Could anyone help to understand this handshake error?
![screenshot from 2018-08-12 14-39-28](https://user-images.githubusercontent.com/5488223/44000448-92f31652-9e3d-11e8-8ee0-b29e18ff720e.png)

i have reffred this demo but we are failing to integrate with the ionic platform.

https://opkode.com/blog/strophe_converse_sasl_external/

Thanks,
Hiren vavadiya

**Comment by jcbrand** [comment]
You'll need to dig for more debug output. Check the network tab of your browser console for any info on that error, also use the non-minified version of Strophe, enable the debugger where the error occurs and look at the error object in more detail. It might give more information as to what's going on.

Also check the log output of the XMPP server which you're trying to connect to, that might give you more information.
