### ISSUE TITLE
mismatching authzid and authcid for PLAIN SASL

### ISSUE THREAD

**Issue by jelmer** [strophe/strophejs#307]
I'm using converse.js with a prosody server, and am having trouble logging in.

Other clients work fine with various SASL mechanisms, including PLAIN.

Looking at the PLAIN SASL string that Converse is sending, it seems
like it is sending the correct username and password but the authcid
and authzid are different. The authzid includes the domain name, the
authcid does not.

Because the strings don't exactly match, my server seems to think this
is an impersonation attempt and rejects the login.

The authcid argument to connect() in Strophe appears to be optional (
https://github.com/strophe/strophejs/blob/a95625ea9876a56c20c6179d993f8712f9e4cfc3/src/core.js#L1815
) but defaults to something different than the authzid. Is there any reason strophe tries to explicitly set it to something else?

**Comment by jcbrand** [comment]
This might be a Converse bug. Did you set a default server domain in the configuration settings, or something like that?

**Comment by jelmer** [comment]
I do have a default domain set, but even if I unset it or specify a full jid this problem occurs.

Is it correct that the default value for authcid is different from just the default value for authzid? It seems that if there is no impersonation going on (i.e. no authcid specified), the values for authcid and authzid should be the same, but they would be set to different values:

authzid to getBareJidFromJid
authcid to getNodeFromJid

**Comment by jcbrand** [comment]
> Is it correct that the default value for authcid is different from just the default value for authzid?

This is how it's been in Strophe since probably about a decade. I couldn't find any definitive answer (either way) in any protocol spec however.
