### ISSUE TITLE
Connection is disappearing  ,install by npm

### ISSUE THREAD

**Issue by GetHere** [strophe/strophejs#308]
install : npm install strophe.js --save
link    : let Strophe = require("strophe.js");

however,I can't connect my server,and then I console.log(Strophe,Strophe.Connection).
the result is following:
![image](https://user-images.githubusercontent.com/22868882/46185011-c7901d00-c30a-11e8-92b3-827990925975.png)

**Comment by jcbrand** [comment]
Sorry but there's not enough info here in order to help you.
