### ISSUE TITLE
Strophe.Connection is not a constructor

### ISSUE THREAD

**Issue by GrreyWang** [strophe/strophejs#315]
I import strophe.js via <script>

```
<script src='./dist/strophe.js'></script>
```

But when I load the page, the js code:

```javascript
connection = new Strophe.Connection(BOSH_SERVICE);
```

will throw an error tell me that the `Strophe.Connection` is not a Constructor

**Comment by jcbrand** [comment]
What version are you using?

This have been fixed already. https://github.com/strophe/strophejs/commit/12f07b46f2fc4d1f42ccfd337a2551a9f33690b6

**Comment by shreeshkatyayan** [comment]
The current release is flagged at 1.3.0 as marked on [official page](http://strophe.im/strophejs/). 
Should we assume that 1.3.1 is signed-off for production use?

**Comment by jcbrand** [comment]
Yes.

**Comment by GrreyWang** [comment]
@jcbrand I use 1.3.1 now.

**Comment by shreeshkatyayan** [comment]
@mods can please accordingly update [homepage](http://strophe.im/strophejs/)
