### ISSUE TITLE
I have the same issue as #134, addHandler did not catch the message but I can see the messsage xml from network dev tool

### ISSUE THREAD

**Issue by lake2** [strophe/strophejs#319]
I have the same issue as #134, addHandler did not catch the message but I can see messsage xml from dev network tool, and remove the last three null don't work.

**Comment by sualko** [comment]
Can you post a code snippet to reproduce the issue? Because Strophe is used in many big projects without problems.

**Comment by lake2** [comment]
I have solved the problem by myself.
Any see this can slove the problem by https://stackoverflow.com/questions/2912530/is-it-right-that-strophe-addhandler-reads-only-first-node-from-response
