### ISSUE TITLE
Disable disconnect retry 

### ISSUE THREAD

**Issue by yuanchieh-cheng** [strophe/strophejs#326]
Is there anyway to disable auto retry when disconnect because I would like to handle retry mechanism on my own.  
I try to set maxRetries to 0 but seems not working.  

```
Strophe.Strophe.maxRetries = 0;
const connection = new Strophe.Strophe.Connection(payload.server, {});
connection.maxRetries = 0;
```

**Comment by jcbrand** [comment]
I would expect setting `connection.maxRetries = 0` to work.

You're welcome to make a pull request that modifies the Strophe.Connection constructor to take an additional option to set the numbre of retries.
