### ISSUE TITLE
Use non-minified version of source code as "main" entrypoint in package.json

### ISSUE THREAD

**Issue by LeartS** [strophe/strophejs#327]
I'm the one who made the [packaging PR](https://github.com/strophe/strophejs/pull/322) so it's my fault :grimacing: 

I was an absolute novice in NPM packaging, and still am not an expert by far, but I think that the the correct way is to use the non-minified version of the library as the main "entrypoint".

* Users in node and backend environments will use the non-minified version, making it easier to debug with any tool (e.g. VSCode debugger)
* Users in browsers environment that use a bundler like webpack, can choose in their own webpack config to set the level and options of minification to use. For example if keep comments or not, if change variable names, etc; or even if don't use minification at all. They are not forced to use strophejs choices for minification
* Users in browsers environment that do not use a bundler will include the file "manually" with a script tag linking to node_modules (if using NPM) anyway, so they can choose to use the minified version or not indipendently of the `main` key in package.json

There is also the possibility of using an "unpkg" key to have the module be distributed by [unpkg cdn](https://unpkg.com/#workflow) for a no-fuss "installation" on frontend.

https://hackernoon.com/how-to-publish-your-package-on-npm-7fc1f5aae600

**Comment by jcbrand** [comment]
I agree, PR welcome :)

**Comment by LeartS** [comment]
Ok I can do it. Do you also want the [unpkg integration](https://unpkg.com/#workflow) of prefer to skip it?

**Comment by jcbrand** [comment]
Sure, looks like it'll add value for people.

**Comment by jcbrand** [comment]
Looks to me like this was done?

Closing.
