### ISSUE TITLE
Calling Strophe.Connection.sendIQ() second time before first call returns?

### ISSUE THREAD

**Issue by vkelman** [strophe/strophejs#330]
It's probably not a bug but a necessary feature, but...
I use CandyJs, which is a shell over Strophe.
I need to search ejabberd users on more than one field of vCard:
A user would type in _search_term_ and Strophe would send request to search for _search_term_ in each of specified vCard fields. Results of search requests  would be then combined using logical OR.

It turned out, the second call of Strophe.Connection.sendIQ() doesn't actually call ejabberd ( unless the first call already returned (and called callback function)? ).

Why is it implemented this way?

I suppose, the solution would  be to to initiate second search request from within callback function?
Would it be enough or is it add a delay before each subsequent call? What delay?

**Comment by jcbrand** [comment]
I'm not aware of anything in Strophe that prevents multiple IQ stanzas to be sent out in parallel.

Are you sure this is a Strophe issue and not due to Candy?

Can you point to the code in question?

**Comment by vkelman** [comment]
@jcbrand 

Actually, it's a little bit different than I described. I'll update the initial text.
1. I'm sure that it is interaction between Strophe and ejabberd which is responsible. Candy directly uses Strophe.Builder and Strophe.Connection  functions to send requests.
2. Here's my code:

```
			$.each(_options.searchFields, function (propertyName, value) {
				console.log('searchField=' + propertyName + '\n');
				var iq = $iq(
						{
							type: 'set',
							id: 'search2',
							to: _options.searchDomain
						}).c('query', { xmlns: 'jabber:iq:search' })
					.c('x', { xmlns: 'jabber:x:data', type: 'submit' });

				iq
					.c('field', { type: "hidden", var: "FORM_TYPE" })
					.c('value', "jabber:iq:search")
					.up()
					.up();

				iq
					.c('field', { var: propertyName })
					.c('value', value === null ? searchText : value)
					.up()
					.up();

				_connection.sendIQ(iq, self.onSearchResult, self.onSearchError, 3000);
				console.log('iq.toString() = ' + iq.toString() + '\n');
			});

```
As you see, inside a loop on each iteration I'm building XML using Strophe.Builder and then immediately send request using Strophe.connection's  sendIQ() method.

I tried it with **two** loop iterations:
```
_options.searchFields: {
			email: null
			,last: null
		} 

```
But in Chrome F12 window I see only **one** request with combined data:
```
<body rid='1931970050' xmlns='http://jabber.org/protocol/httpbind' sid='7564ec1adddd2cce69860ca2250e456ad3284f3f'>
  <iq type='set' id='search2' to='vjud.planetrisk.com' xmlns='jabber:client'>
    <query xmlns='jabber:iq:search'>
      <x xmlns='jabber:x:data' type='submit'>
        <field type='hidden' var='FORM_TYPE'><value>jabber:iq:search</value></field>
        <field var='email'><value>UnclassifiedFouoLes</value></field>
      </x>
    </query>
  </iq>
  <iq type='set' id='search2' to='vjud.planetrisk.com' xmlns='jabber:client'>
    <query xmlns='jabber:iq:search'>
      <x xmlns='jabber:x:data' type='submit'>
        <field type='hidden' var='FORM_TYPE'><value>jabber:iq:search</value></field>
        <field var='last'><value>UnclassifiedFouoLes</value></field>
      </x>
    </query>
  </iq>
</body>
```
It looks like **Strophe combines two requests together before sending them**.  Or could it be that Chrome F12 mislead us?

For that combined request ejabberd searches **only** for the first requested field ('email' in my case).  That's not what I need.

Overall, if _options.searchFields has only one field, I see in F12 window **two** requests sent to ejabberd. First has search stanza, the second, which follows immediately, is empty.
In case _options.searchFields has two or more field, I see **three** requests sent to ejabberd. The first has that combined search stanza shown above, two others are empty. Why is that?

Right now both search stanzas above have id='search2'  Do I need by any chance to increment it on each loop iteration?

**Comment by jcbrand** [comment]
Yes, for efficiency Strophe bundles multiple stanzas per request and then sends the request out as soon as it becomes idle.

If you want to force the stanza to be sent out immediately you can call [flush](http://strophe.im/strophejs/doc/1.3.0/files/strophe-js.html#Strophe.Connection.flush).
