### ISSUE TITLE
Strophe with react.JS

### ISSUE THREAD

**Issue by mailtosagar** [strophe/strophejs#334]
Hi, 
I am a newB to the strophe and react both. I am working on some chat application with ejabberd as backend.
Basically I have downloaded the code and its working if i work with strophe in a chat.js and linking that js in my HTML file. I am able to use plugins in my chat.js also just by linking them to my HTML page. 

I have placed all my code in a directory named "strophe" .

in my app.js i am using the line 
import { Strophe } from './strophe/strophejs-1.3.2/dist/strophe.js'

var conn = new Strophe.Connection('http://localhost:5280/http-bind');

console.log("conn in App.js: ",conn);

but i am unable to understand how to use the plugins in react 
The line
conn.roster.get(friendList) 
is giving me errors and it's driving me nuts.
Please help.

**Comment by jcbrand** [comment]
This issue tracker is meant for bug reports and I don't think its the right place to ask for integration support. Try StackOverflow.

**Comment by jcbrand** [comment]
This issue tracker is meant for bug reports and I don't think its the right place to ask for integration support. Try StackOverflow.

**Comment by mailtosagar** [comment]
Hi,

Well it is not actually an integration support question. May be it's a bug or something i am missing in between.

I am able to use strophe object in react using 
"window.Strophe"
but I am not able to use strophe.roster.get() method even after i have linked strophe.roster.js .

this may be helpful in understanding my issue.
https://stackoverflow.com/questions/41090689/working-with-strophejs-library-in-reactjs-app

Why is that??
