### ISSUE TITLE
Unable to get presence via type attribute

### ISSUE THREAD

**Issue by ashebby** [strophe/strophejs#338]
I am working on a react app integreated with strophe & Openfire as xmpp server through HTTP Binding.

I want to access presense of a user, I do this by:

    const $pres = attrs => { return new window.Strophe.Builder("presence", attrs); }
    ...
    conn.addHandler(this.on_presence, null, "presence");
    conn.send($pres())
    ...
    on_presence = (presence) => {
        const from = presence.attributes.from
        const type = presence.attributes.type
        ...
    }

I am able to see 'from attribute, but there is no 'type' attribute:
<img width="226" alt="Screen Shot 2019-07-29 at 10 29 23" src="https://user-images.githubusercontent.com/10660012/62040953-77b40800-b1f2-11e9-9fa9-f8b48a2c6918.png">

**Comment by jcbrand** [comment]
A presence stanza without a `type` attribute is allowed and "signals that the relevant entity is
   available for communication".

https://tools.ietf.org/html/rfc6121#section-4.7.1
