### ISSUE TITLE
XEP-0384: OMEMO Encryption

### ISSUE THREAD

**Issue by Neustradamus** [strophe/strophejs#342]
Can you add OMEMO Encryption support?
- https://conversations.im/omemo/
- https://xmpp.org/extensions/xep-0384.html

**Comment by jcbrand** [comment]
This is out of scope for the core library

**Comment by Neustradamus** [comment]
It is possible to add OMEMO in this org?
- https://github.com/Shokodemon/strophe-omemo

**Comment by jcbrand** [comment]
That's up to the author of that plugin, not us.
