### ISSUE TITLE
Strophe JS Plugin Creation Request

### ISSUE THREAD

**Issue by ArunMuthu-NS** [strophe/strophejs#343]
Hi team,

I'm currently working with MongooseIM XMPP server. I'm using Strophe.js for my client and MongooseIM provides default implementation of inbox https://mongooseim.readthedocs.io/en/latest/modules/mod_inbox/ . 
I'm planning to create a plugin for that feature. I need a repository to fork and work on the plugins.

Can anyone help me out ?

**Comment by jcbrand** [comment]
Currently each plugin is in its own repo inside this organisation. You can take a look inside this GitHub org.

All plugins have been voluntarily created and offered to this org, there is no dedicated team for plugins.
