### ISSUE TITLE
SyntaxError: Unexpected token '*'. import call expects exactly one argument.

### ISSUE THREAD

**Issue by Kendokai** [strophe/strophejs#345]
Is there any script missing? I got this error. just downloaded then loaded script.
![image](https://user-images.githubusercontent.com/8243358/79588511-3a840300-80fe-11ea-8824-15b26a5de20d.png)

**Comment by sualko** [comment]
Please download the [latest release](https://github.com/strophe/strophejs/releases) and use the appropriate file inside the dist folder. In your case it should probably be `dist/strophe.min.js`.
