### ISSUE TITLE
Referencing undefined property

### ISSUE THREAD

**Issue by shinwan2** [strophe/strophejs#352]
Hi, I was reading through the code to understand how it works and I found this code
https://github.com/strophe/strophejs/blob/f4e37218a66a728e5aa19bf45b79616c8c721dec/src/bosh.js#L631 and I couldn't find `disconnecting` property elsewhere in the file. 
Shouldn't it be using `this._conn.disconnecting`?

**Comment by jcbrand** [comment]
Hi, looks like you're right!

Would you mind making a small PR to fix this?

**Comment by jcbrand** [comment]
Nevermind, I made the change.
