### ISSUE TITLE
Tests don't seem to pass, make with default target returns error.

### ISSUE THREAD

**Issue by daidoji** [strophe/strophejs#353]
Sorry, new to the project so maybe there's a good reason for this, but the tests don't seem to pass upon checkout right now.  Am I doing something wrong or is there some context I don't know about? 

To replicate:
1. Checkout repo.
2. run `make check`

My log output is below.

```
daidoji@i7laptop:~/guild/client/strophejs$ make check
./node_modules/.bin/eslint src/
LOG_CR_VERBOSITY=INFO ./node_modules/.bin/run-headless-chromium --no-sandbox http://localhost:8080/tests/
Starting Chromium...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Applications/Chromium.app/Contents/MacOS/Chromium ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
make: *** [Makefile:71: check] Error 1

daidoji@i7laptop:~/guild/client/strophejs$ make
Building Strophe documentation...
cp: cannot stat 'dist/strophe.umd.js': No such file or directory
make: *** [Makefile:41: doc] Error 1

```

**Comment by jcbrand** [comment]
> cp: cannot stat 'dist/strophe.umd.js': No such file or directory

Looks like there is a file missing. Try `make dist` first.

**Comment by daidoji** [comment]
Oh sorry, I figured out what it was.  I don't have naturaldocs installed thats where it was blowing up.  Maybe list that and mono as a dependency on the README.  You can close or leave this issue open.
