### ISSUE TITLE
`Strophe.getDomainFromJid` throws error when `Strophe.getBareJidFromJid` returns `null`

### ISSUE THREAD

**Issue by afuggini** [strophe/strophejs#358]
I came across an error in this function: https://github.com/strophe/strophejs/blob/4812cfbe0c44dddc5b8adf210524f17b44ff989b/src/core.js#L673-L682

When `Strophe.getBareJidFromJid(jid);` returns `null`, the next line attempts an `indexOf` on it, which results in an error. In fact the entire rest of the function assumes a string.

**Comment by jcbrand** [comment]
What value did you pass in to the function to make this happen?

**Comment by jcbrand** [comment]
An empty string is not a valid JID, so it's understandable that it breaks.

We could throw a more descriptive error here, but the fact that an empty string gets passed in means that something should be fixed higher up in the code that calls `getDomainFromJid`.
