### ISSUE TITLE
WebSocket connection failed: Data frame received after close

### ISSUE THREAD

**Issue by vlyamzin** [strophe/strophejs#359]
Hello.

There is a bug in the disconnecting process from the WebSocket. It is reproducible only in Chrome and happens in `_disconnect()` method in `src/websocket.js`. 
![2020-08-12_11-06](https://user-images.githubusercontent.com/6349826/89992167-949c6b80-dc8d-11ea-982c-08ee282d5c66.png)

Look like `<close>` message is being sent **after** Strophe closes the socket in `_doDisconnect()`. 
https://github.com/strophe/strophejs/blob/c4a94e59877c06dc2395f4ccbd26f3fee67a4c9f/src/websocket.js#L288-L304

The quick solution for me was to wrap `_doDisconnect()` in setTimeout.
``` javascript
_disconnect: function (pres) {
        ...
            try {
                this.socket.send(closeString);
            } catch (e) {
                Strophe.info("Couldn't send <close /> tag.");
            }
        }
        setTimeout(() => this._conn._doDisconnect(), 0);
    },
```
This code works fine in the latest Chrome, Firefox & Safari. Don't have IE and Edge, but it should work there too. 
Maybe it's already fixed in the future versions, otherwise, I could create a PR. Just let me know. Thanks

**Comment by jcbrand** [comment]
I looked at the current code, and it's still the same, so a PR would be appreciated, thanks.
