### ISSUE TITLE
Entry expried in xmpp.org software listinging

### ISSUE THREAD

**Issue by Zash** [strophe/strophejs#362]
The [entry for Strophe.js](https://github.com/xsf/xmpp.org/blob/3b92790029d97f7953ae58de0e711705bf113da9/data/libraries.json#L537-L545) in the [listing on xmpp.org](https://xmpp.org/software/libraries.html) has expired and it would be great if [someone associated with the project could renew it](https://xmpp.org/2017/03/new-xmpp-software-listing-rules/). Thanks.

**Comment by jcbrand** [comment]
Done: https://github.com/xsf/xmpp.org/pull/799
