### ISSUE TITLE
Unable to publish custom message to Openfire

### ISSUE THREAD

**Issue by mkj-git** [strophe/strophejs#364]
I want to publish following message to a node:

    $('#send').click(function () {

                var ms = $iq({ type: 'set', to: 'pubsub.xyz.com', from: fromJid})
                .c('pubsub', { xmlns: 'http://jabber.org/protocol/pubsub' })
                .c('publish', {node: "testNode"})
                .c('item')
                .c('x', {xmlns:  "jabber:x:data",
                         type: "result"})
                .c('field', {"var": "color"})
                .c('value').t('red');      

        connection.sendIQ(
                ms,
                function(e) {
                    console.log("Publis success");
                }, function(e) {
                    console.log("Publis err::" +e);
                });        
    });    

It is able to publish the message but empty `item`:

`<message xmlns="jabber:client" from="pubsub.opbl-5cg933380j.internal.operative.com" to="hello@opbl-5cg933380j.internal.operative.com" id="jMdVQ6Dc"><event xmlns="http://jabber.org/protocol/pubsub#event"><items node="testNode"><item id="0682c2b8-8020-4fce-b0c7-9b726700192f40"/></items></event><headers xmlns="http://jabber.org/protocol/shim"><header name="SubID">P9b5tl1gtUB03gr4cBdAJq7o7BF9yVnwBgrYVlYa</header></headers></message>`

**Comment by jcbrand** [comment]
This issue tracker is for bug reports, not for support. Try asking on something like StackOverflow.
