### ISSUE TITLE
XEP-0142: Workgroup Queues

### ISSUE THREAD

**Issue by albertusgeyser** [strophe/strophejs#365]
Good Day

Is there any way to implement XEP-0142: Workgroup Queues in strophejs?
want to use strophejs to implement website live chat for support group.

Hope anyone out there to shed light.

Thank You

Albertus Geyser

**Comment by jcbrand** [comment]
Strophe is probably too low-level to make it a good place to implement XEP-0142.

There is a XEP-0142 community plugin for Converse.js which you can try out:
https://github.com/conversejs/community-plugins/tree/master/packages/fastpath
