### ISSUE TITLE
Uncaught InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable.   in IE / Chrome

### ISSUE THREAD

**Issue by allan-simon** [strophe/strophejs#37]
We use strophe.js in our application, after some minutes in Chrome/IE (not in Firefox) when the application try to reconnect , strophe.js throw the following exception 

     Uncaught InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable. 

according to SO http://stackoverflow.com/questions/17182816/ajax-php-javascript-error-when-using-post-method  it seems the solution is to add 

                    req.xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');

just after the `req.xhr.open`  (line 2247)

**Comment by jcbrand** [comment]
Hi @allan-simon, any feedback on this?

**Comment by allan-simon** [comment]
hello, I'm going to close it, we've change a lot of things in our code base since and we're not experiencing the issue anymore with a clean last release of strophe.js
