### ISSUE TITLE
responseXML parser error 

### ISSUE THREAD

**Issue by herbertgaoo** [strophe/strophejs#370]
I got the info `Got responseText but no responseXML; attempting to parse it with DOMParser...` when I use strophe.js with Vue , 
`new DOMParser().parseFromString(this.xhr.responseText, 'application/xml').documentElement;` It was actually successful parse, but `node.querySelector('parsererror')` throw a exception, so I replace it with `node.tagName === "parsererror"` and it works.

**Comment by jcbrand** [comment]
> but node.querySelector('parsererror') throw a exception

What kind of exception? Would you make a PR with your change?
