### ISSUE TITLE
How to achieve the same user name two browsers kick each other

### ISSUE THREAD

**Issue by liuqibo** [strophe/strophejs#373]
The same user name is logged in in the first browser and then logged in in the second browser. At this point, the first browser receives the response with the conflict flag, but it is not caught in the state monitoring method. So I changed the code :

```
_onRequestStateChange: function _onRequestStateChange(func, req) {
            if (req.abort) {
                req.abort = false;
                return;
            }

            if (req.xhr.readyState !== 4) {
                return;
            }
            
            var errorStr = '';
            if (req.xhr.response){
                var responseContent = req.xhr.response;
                if(responseContent.indexOf("conflict") != -1){
                    errorStr = 'conflict';
                    this._conn._changeConnectStatus(Strophe$1.Status.DISCONNECTING, null);
                    this._conn._doDisconnect(errorStr);
                    return;
                }
            }
            .....
}
```

so that the first browser gets kicked.But the second browser received an error when logging in.

request:
`<body rid="1004068922" sid="66dwmahjnu" xmlns="http://jabber.org/protocol/httpbind"><iq id="_session_auth_2" type="set" xmlns="jabber:client"><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></iq></body>`

response:
`<presence type="unavailable" from="xxx" to="xxx" xmlns="jabber:client"/>`

Help me. Thanks

**Comment by jcbrand** [comment]
Sounds like you're trying to use the same session in both browsers. I don't think that makes any sense, and you should instead establish a completely new session in the other browser.

**Comment by liuqibo** [comment]
In the other browser is a new session, with the RID and SID both new.But the Openfire log shows an invalid SID.

**Comment by jcbrand** [comment]
Then you need to investigate why Openfire says the SID is invalid. Sounds to me like you're re-using an existing session (SID = Session ID).

Doesn't sound like there's any issue with regards to Strophe here.
