### ISSUE TITLE
How to correctly import strophe.js plugin in node.js

### ISSUE THREAD

**Issue by raphael10-collab** [strophe/strophejs#376]
import '../../../lib/strophejs/strophe.disco.js';
    
    let [conn, setConn] = React.useState(new Strophe.Connection("...");
    conn.connect("","");
    conn.disco.info("");
    
    I get the error: " Cannot read property 'info' of undefined"

- node: v14.17.0
- OS: Ubuntu 20.04

**Comment by jcbrand** [comment]
This issue tracker is used for bug reports and feature requests, not for support requests.

You can try the mailing list: http://groups.google.com/group/strophe
