### ISSUE TITLE
Stanza parsed incorrectly in React Native environment

### ISSUE THREAD

**Issue by abdulrahman-fullstack** [strophe/strophejs#387]
The XML stanza from the server was parsed incorrectly. In the strophe source code I found you are using `xmldom` to parse XML stanzas, but it is incorrectly parsing the XML string.

I tried to parse the below sample XML using both `xmldom` & `@xmldom/xmldom` packages. It parsed incorrectly in `xmldom` but parsed properly in `@xmldom/xmldom`. And they are not maintaining the `xmldom` as they mentioned in [this link](https://www.npmjs.com/package/@xmldom/xmldom)

```html
<history><chat><message_time>1611750297538106</message_time><user>911234567890</user><status>0</status><broadcastid ></broadcastid ><broadcast_msgid ></broadcast_msgid ><time>2021-01-27 07:24:57</time><message >h+D4fMcIXtcNbUmxU+MjsxnlsdkjndckjncskJJslkdndsjcnJohei7JDwLH67qKyp9jZaBkBIGdjirzrU9aw2kFjY772FmdbrTxA0uXEWziEOjt5WeA/HwJi/hYtSgCFQSSpBQ5IWDBSnRsGymNmHWGBpGDb1Ds656g4xf3frbytUIA1aPzzVLRlPsIgOjsdnckjsdnckjdnscIOhsjshsE+O/0TPGpZC+U6JzAN/BkZ96yEytlBPUNk96sA8TRcngEiqYcXGqhibQ==</message ><msgid>154433a0-4253-44a8-855b-15b38673f297</msgid><recallstatus>0</recallstatus><favouritestatus >0</favouritestatus ><favouriteby >0</favouriteby ></chat><chat><message_time>1611750297051451</message_time><user>919876543210</user><status>0</status><broadcastid ></broadcastid ><broadcast_msgid ></broadcast_msgid ><time>2021-01-27 07:24:57</time><message >26yG6S9NC6uOrFrbmYc19xEv5uH4HxtHG3ndsclknsssdcsdjbEYYjnbcsdkUUacmncnbaEWYERcbI13TWdugdlSYCEJunwDUHySHxFKTwV1ESu/lxz0rXxnyFIR40csG44mriM4Mr1m7jjw4uitxIwU/dnVuI/DQv55Qca2KU5Ln94+cZcUv/ZPjGzEA4nCAdUjr5PIfAJ+8rF2EnkJJaYTpv7K/zsVf2nP++d28piCQ6rBmuHbVWJWQ==</message ><msgid>ac434970-c8e7-4ac5-bcb0-992aa91571a8</msgid><recallstatus>0</recallstatus><favouritestatus >0</favouritestatus ><favouriteby >0</favouriteby ></chat><chat><message_time>1611750254279345</message_time><user>919988009988</user><status>0</status><broadcastid ></broadcastid ><broadcast_msgid ></broadcast_msgid ><time>2021-01-27 07:24:14</time><message >JPhNDYep9LscHo/JM2NpEyEMj4JFycM33xhpSBzHFjNIRhY8E9pqgPLB5nsHQepRn2i/IeuCm5r4XPq9/LlhvR1UQNaJnG7hHRFSivutI6jCdkcjnskdjcndJJKJdkcndcndjncjksncljasjJJskjs2399LKLalsnkjasnfw82maEwtLPo0PbvAm6q5vnbQcBhSCuqXipCtCRfs+mwvLom+GYhECJnSB5SBQfCUjQzYOn7c3cyi/ijb6CHa7bYR+bscWVR6qQauavhNQ==</message ><msgid>4673e1d6-7a0d-4025-ad2d-9f9fef62749f</msgid><recallstatus>0</recallstatus><favouritestatus >0</favouritestatus ><favouriteby >0</favouriteby ></chat></history>
```

and I could not even configure other DOMParser as strophe is using `xmldom` package's DOMParser

can anyone pls help me to fix the issue

**Comment by abdulrahman-fullstack** [comment]
And it will be helpful if strophe is returning the raw XML string along with the parsed XML data in the **sendIQ** callback

**Comment by jcbrand** [comment]
Strophe is now using `@xmldom/xmldom`.

See here: https://github.com/strophe/strophejs/blob/9da72c07c645dd54c67d4749ccb8f32998cad870/package.json#L84

> And it will be helpful if strophe is returning the raw XML string along with the parsed XML data in the sendIQ callback

Not sure about `@xmldom/xmldom` but in the browser the stanza is of type Element, and so you can call `outerHTML` to get the raw text.

**Comment by abdulrahman-fullstack** [comment]
> Strophe is now using `@xmldom/xmldom`.
> 
> See here:
> 
> https://github.com/strophe/strophejs/blob/9da72c07c645dd54c67d4749ccb8f32998cad870/package.json#L84
> 
> > And it will be helpful if strophe is returning the raw XML string along with the parsed XML data in the sendIQ callback
> 
> Not sure about `@xmldom/xmldom` but in the browser the stanza is of type Element, and so you can call `outerHTML` to get the raw text.


Yes its been changed in `package.json`. But still in code it is not updated. Please check the below lines
https://github.com/strophe/strophejs/blob/488d70ed65a1fd7530113f8e9ae5fb8903f25680/src/shims.js#L54
https://github.com/strophe/strophejs/blob/488d70ed65a1fd7530113f8e9ae5fb8903f25680/src/shims.js#L105

**Comment by abdulrahman-fullstack** [comment]
Sorry @jcbrand, i think it is updated and merged

https://github.com/strophe/strophejs/pull/389


Thank you for your support

**Comment by jcbrand** [comment]
No worries @abdulrahman-fullstack 👍
