### ISSUE TITLE
Incorrect require xmldom in strophejs/src/shims.js

### ISSUE THREAD

**Issue by NewEraCracker** [strophe/strophejs#388]
The following commit has changed the xmldom package name from xmldom to @xmldom/xmldom
https://github.com/strophe/strophejs/commit/f61dbe53b2c64fa49cc915c33c9307cf4f756597#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R82

However this file (current master as I write this message) still mentions the package by its old name
https://github.com/strophe/strophejs/blob/488d70ed65a1fd7530113f8e9ae5fb8903f25680/src/shims.js#L54

**Comment by atomic-tang** [comment]
@jcbrand the package '@xmldom/xmldom' needs to be used instead of 'xmldom'. I've tried building my project with version 0.7.5 for '@xmldom/xmldom' and Strophe.js version 1.4.3 and I am getting a 'Module not found' error. Installing 'xmldom' resolves the issue but the latest version is 0.6.0.

**Comment by abdulrahman-fullstack** [comment]
@NewEraCracker  In the `shims.js` file, below line also needs to be updated to **'@xmldom/xmldom'**

https://github.com/strophe/strophejs/blob/488d70ed65a1fd7530113f8e9ae5fb8903f25680/src/shims.js#L105

So that it will be completely independent of 'xmldom' package

**Comment by NewEraCracker** [comment]
@jcbrand Hello. Can you please do a new release to npm with the fix when it is convenient. Thanks.

**Comment by jcbrand** [comment]
Strophe 1.4.4 (with this fix) has been released.
