### ISSUE TITLE
Strophe.js getting disconnected after 30sec upon connecting.

### ISSUE THREAD

**Issue by Vida-Subhash** [strophe/strophejs#453]
Hello everyone.

I'm using Strophe.js for group chat. after connecting to Strophe.js it's automatically disconnecting from ejjbred server.
here is code for connection.
login(jid, pass) {
    this.connection = new Strophe.Connection(this.BOSH_SERVICE, {
      keepalive: true,
    });
    this.connection.connect(jid, pass, (status) => {
      this.onConnect(status);
    });
  }

**Comment by jcbrand** [comment]
Sorry, this issue tracker is for bug reports and feature requests and not general support.

You can try the mailing list http://groups.google.com/group/strophe, or StackOverflow.
