### ISSUE TITLE
addHandler issue with register plugin

### ISSUE THREAD

**Issue by isfarax** [strophe/strophejs#50]
Hi,

I'm using Strophe.js AMD with the Register plugin (works perfect so far) and I have noticed that the addHandler method/function does not get fired until the connection status becomes CONNECTED?

I can understand why you would have it firing up AFTER being connected, but I think in the case of registration, it would be useful to have this method fire up at any given stage (i.e. before being connected) so that you can analyse the server response more accurately and better instead of relying on the CONNECTION status.

Quite frustrating when you realise that you have to work with the RAW OUTPUT instead of the addHandler method.

Please see the register plugin page where it shows you how to deal with server response (which is now the right way to do IMO): https://github.com/metajack/strophejs-plugins/tree/master/register

If anybody else has encountered this issue, please comment and share your thoughts and solutions.

Farax

**Comment by jcbrand** [comment]
Looks like this is resolved. Closing.
