### ISSUE TITLE
[Feature] Have a "real" ESM support

### ISSUE THREAD

**Issue by Bricklou** [strophe/strophejs#513]
Hi !

This could be interesting to have a proper and clean ESM import system. This way, the module doesn't need to rely on a `global` object.

in example, all imports could be like this:
```ts
import { Strophe } from 'strophe.js';
import { RSM } from 'strophejs-plugin-rsm';
import { Ping } from 'strophejs-plugin-ping';

Strophe.register([RSM, Ping])
// or
Strophe.register(RSM)
Strophe.register(Ping)
// or
Strophe.init({
    plugins: [RSM, Ping]
})
```

Is this possible to implement this system ?

**Comment by jcbrand** [comment]
It's already possible to use ESM imports:

https://github.com/conversejs/converse.js/blob/fbe86e5af87e98e3967bd5dde73cc9cfa17e61e9/src/headless/core.js#L22

**Comment by Bricklou** [comment]
For the main module, not for plugins which still use the Strophe instance declared globally

**Comment by jcbrand** [comment]
This repo is specifically for Strophe.js, not for the plugins.

The plugins are largely unmaintained and abandoned.
