### ISSUE TITLE
Broken dependencies in React

### ISSUE THREAD

**Issue by ghost** [strophe/strophejs#524]
Howdy y'all!

I'm trying to use strophe.js in a React project, but when I import it, it gives a bunch of errors like this:

`ERROR in ./node_modules/strophe.js/node_modules/ws/lib/permessage-deflate.js 3:13-28

Module not found: Error: Can't resolve 'zlib' in '/home/wfisher/Projects/kai-xmpp/node_modules/strophe.js/node_modules/ws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
	- install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "zlib": false }`

I'm not really sure how to fix this.

**Comment by gwfisher** [comment]
I'm just using `import { Strophe } from 'strophe.js`

I have it installed from npm. I just tried the way you suggested and it did not work

**Comment by jcbrand** [comment]
Converse.js uses the way I commented above and it gets used in React projects, so I'm not sure what the issue is.

Are you using Browserify?

**Comment by gwfisher** [comment]
Nope. I'm not using browserify. I'll create a blank hello world project and see if maybe I screwed something up and report back.

**Comment by jcbrand** [comment]
Perhaps also try the latest commit of Strophe instead of the latest release.

In package.json:
```
  "strophe.js": "strophe/strophejs#ad3c8b5db11b030268f95e4041ea15aed14319d9",
```

Are you using NPM or Yarn? With yarn, it's necessary to force it to clear the cache first

```
yarn cache clean strophe.js
yarn install
```
