### ISSUE TITLE
iq 'from' attributes are not checked everywhere

### ISSUE THREAD

**Issue by xnyhps** [strophe/strophejs#56]
I've been looking into XMPP implementations and whether they verify the source of iq replies. See http://mail.jabber.org/pipermail/jdev/2014-January/089824.html and http://mail.jabber.org/pipermail/jdev/2014-January/089838.html for more discussion.

The `sendIQ` function in https://github.com/strophe/strophejs/blob/master/src/core.js#L1938 does not verify whether the `from` on an incoming iq packet matches the `to` from the outgoing packet. This means for example that a roster reply is not checked to actually originate from the user's server. An attacker can, if timed right, spoof the roster for a user by making sure their fake reply reaches strophe before the real reply does. This can also lead to spoofing of vcards, intercepting file transfers, etc.

I have verified that calling `connection.roster.get(function (roster) ... )` does indeed cause the callback to be called even when the origin is not the user's server.

**Comment by jcbrand** [comment]
This appears to be fixed in 42340f59f5375b3781c9874a871b69c434901223

Closing.
