### ISSUE TITLE
XEP-0237 is Obsolete, It is preferable to use it in production system, If not then is there any alternate available?

### ISSUE THREAD

**Issue by YogiDhingani27** [strophe/strophejs#585]
Available strophe plugin supports XEP-0237. Its is marked as Obsolete but the author and updated with datatracker.ietf.org/doc/html/rfc6121 As the current roster plugin for strophe.js is using Obsolete version is it preferable to use it in production?

**Comment by jcbrand** [comment]
I think the functionality is largely the same. Ideally someone would update the plugin to use RFC6121. It doubt it's much work.

This issue tracker is only for strophe.js, not for the plugins. So I'm closing this ticket.

**Comment by YogiDhingani27** [comment]
Is there any alternate available for XEP-0237? Can i use XEP-0237 in production system?

**Comment by YogiDhingani27** [comment]
Is there any way  in xmpp to prepare seperate roster/contact list based on some unique entity but have same jid?

**Comment by jcbrand** [comment]
> Is there any alternate available for XEP-0237? Can i use XEP-0237 in production system?

XEP-02137 is obsolete because its functionality is now included in the core protocol (via RFC6121), so *all* XMPP servers should support roster versioning.

> Is there any way in xmpp to prepare seperate roster/contact list based on some unique entity but have same jid?

I'm not sure what you really mean, but perhaps you want to look at PubSub or PEP.
You can create your own private PEP node and publish your contacts there.
https://xmpp.org/extensions/xep-0163.html

**Comment by YogiDhingani27** [comment]
I have requirement as per below:

Our system has one user which can create multiple enterprises and each enterprise can have a individual chat functionality. 

For example: I logged in as a user A and have two enterprises Enterprise Alpha and Beta. Suppose user A which is logged in as a Enterprise Alpha chat with Some other User B (Gamma enterprise). now this chat is not visible to User A when user A switches the enterprise from Alpha to Beta.   

I want to separate the chat module enterprise vise.
