### ISSUE TITLE
XEPs support page

### ISSUE THREAD

**Issue by Neustradamus** [strophe/strophejs#59]
It will be a good idea if there was a page with actual XEPs supported (with versions) by strophejs.

Example:

https://prosody.im/doc/xeplist

http://www.process-one.net/en/ejabberd/protocols/
http://www.ejabberd.im/protocols

https://trac.gajim.org/wiki/GajimXEPSupport

https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by jcbrand** [comment]
@Neustradamus Are you going to make that page? :)

**Comment by jcbrand** [comment]
Nice idea, but I don't see the point in bloating the issue tracker if no-one is interested in doing it.

**Comment by Neustradamus** [comment]
@jcbrand: Can you reopen this ticket because it is not specified.
