### ISSUE TITLE
strophe > 1.5.0 no longer works in React Native

### ISSUE THREAD

**Issue by saghul** [strophe/strophejs#606]
(following from https://github.com/strophe/strophejs/pull/465#issuecomment-1523262643)

With the SCRAM refactor and Strophe now relying on the WebCrypto API, there is no good path for RN. All the polyfills seem unmaintained or downright sketchy (like proxying calls through a WebView).

IMHO having fallback implementations as previously would be desirable for environments without the WebCrypto API available.

**Comment by Neustradamus** [comment]
To follow

**Comment by jcbrand** [comment]
It doesn't look feasible to me to go back to a state where we don't use WebCrypto.

We now support SASL SCRAM with SHA-256, SHA-384 and SHA-512 and for these we need WebCrypto.

Previously Strophe included its own implementation of SHA-1, but we don't have implementations for the other hashing algorithms and its not desirable to have to maintain our own versions of them only for React Native support.

Looks like this is an issue in Matrix-land as well:
https://github.com/matrix-org/matrix-js-sdk/issues/2789

Ultimately, I think if you want to continue using newer versions of Strophe on React Native, you'll have to hold your nose and choose a 3rd party library.

For example either https://github.com/webview-crypto/react-native-webview-crypto or https://github.com/crypto-browserify/crypto-browserify

The webview hack from `react-native-webview-crypto` isn't pretty, but it works and is for example used by GUN, which is a large project. https://github.com/amark/gun

**Comment by saghul** [comment]
Well, that's disappointing. Yes there is support for new stuff now, but backwards compatibility was broken with no major version bump.

- https://github.com/browserify/crypto-browserify hasn't been touched in 5 years
- The webview hack is not viable really

I think the only option would be to create a WebCrypto polyfill using https://github.com/margelo/react-native-quick-crypto but that is not something that can be done easily or quickly.
