### ISSUE TITLE
Punjab and Openfire

### ISSUE THREAD

**Issue by majimboo** [strophe/strophejs#63]
I am using strophe for the web and punjab and openfire for the server.

My strophejs version is master from source. I've been experiencing weird occurrences for session binding. If I send a message and reload the session suddenly gets dropped. When I just keep refreshing no message sent, All goes well.

I also noticed that the rid keep increment correctly but there are also times that it goes back to the first rid. I have put the initial rid and sid on a cookie, then I use those data on my javascript code.

It is just weird that sometimes it works well, and sometimes it does not. Or maybe I do not understand pre-binding very well. It pre-binding done like authenticate together with the web login then store the rid,sid and jid in cookie. That cookie will be reused by the strophe on each page reload? Or do I have to prebind every page refresh?

Another weird thing is that strophe sends multiple messages when I send one message and reload the page immediately after sending. It sends like 2 or 3 dupes and the RID's are all the same.  After that I lost connection.

But when I view the page (without sending anything) and keep on reloading it, everything works well. Still keeps sending dupes, but also not getting disconnected.

**Comment by jcbrand** [comment]
> Yes, I have been trying to save the rid to the local storage. Using storejs too. Another issue I am facing is I get disconnected after awhile which means I should be sending pings to the server so it will keep me alive?

You can try to implement [XEP 0199](http://xmpp.org/extensions/xep-0199.html) for this.

> Each page reload disconnects me from the server. I have had success in remembering the rid on the 
> storage but the problem was the rid should be deleted from the local storage if my session gets killed. But > doing that will also delete the storage when I reload because it is also considered a disconnect.

This is an implementation issue on your side and not relevant to strophe.js.

> I have been focusing on addressing the first issue. But my 3rd issue seems being replicated somewhere, I > have been searching and other people are having the same problem. Most of my code is from the
> examples. I only modified the handlers which can be seen here.

There's nothing we can do about that unless you can somehow show that this is a bug in strophe.js or if you can provide enough details (code, logs, debug output etc.) for someone to figure out what's going on.

Closing this ticket due to inaction. You can open it again if the problem persists and you have relevant debugging info.
