### ISSUE TITLE
attach() for websockets?

### ISSUE THREAD

**Issue by siadat** [strophe/strophejs#66]
Is this possible to I attach Strophe to a an existing session via websockets?

I need this to auto-login users that are already logged in an app.

**Comment by Gordin** [comment]
The xmpp-over-websocket RFC does not specify an equivalent to "attach" in BOSH, so probably not.

**Comment by jcbrand** [comment]
Looks like it would be possible to do something similar with XEP-0198 Stream Management. Specifically the "[stream resumption](http://xmpp.org/extensions/xep-0198.html#resumption)" part.

**Comment by jcbrand** [comment]
@Gordin What do you do to maintain sessions across page reloads? Do you log the user in from scratch every time?
