### ISSUE TITLE
bind 

### ISSUE THREAD

**Issue by mattkanwisher** [strophe/strophejs#68]
XMPP Resource bind, doesn't allow other elements to be returned, and it assumes that bind is immediately returned which makes the server have to do a synchronous response for bind, which is not correct. It means that offline messages can't be flushed at that point in time. 

<bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><resource>EM</resource></bind></iq>

**Comment by jcbrand** [comment]
@mattkanwisher Can you point out in the code where the problem lies or provide a way in which someone can test or replicate this issue?

**Comment by jcbrand** [comment]
Closing due to inaction.

**Comment by mattkanwisher** [comment]
meh you wait 8 months to respond to an issue, lose any examples

**Comment by jcbrand** [comment]
I didn't wait 8 months because this isn't my repo, I'm volunteering here.
