### ISSUE TITLE
Error with Builder.up depending on context

### ISSUE THREAD

**Issue by H-L** [strophe/strophejs#711]
Hello,

I encountered an error using Strophe in Workers, compiled as a dependency. It appears that the method `Builder.up()` is using `this.node = this.node.parentElement;` but in this particular context, `node.parentElement` does not exists.

I patched it locally, replacing it by `node.parentNode` and it seems to work.

I don't know if it would have side effects to change it directly.

Let me know if you need a PR.

Best regards

**Comment by jcbrand** [comment]
Hi, I would appreciate a PR, thanks. I think for backwards compatibility, the code could use `parentElement` if it's available and fall back to using `parentNode` if not.
