### ISSUE TITLE
Cannot find module 'strophe.js' when using in an Angular project

### ISSUE THREAD

**Issue by DanyUP** [strophe/strophejs#713]
I'm trying to integrate Strophe.js in an Angular 18 project (Typescript 5.4.2, Node 22.3.0) but I get a compilation error:
`TS2307: Cannot find module 'strophe.js' or its corresponding type declarations.`

Everything seems ok, I installed the strophe.js package at version 3.0.0 and I can see the strophe.js folder inside node_modules folder (I can even see the typescript typings!), but I can't make it compile.

Here is a repo to reproduce the problem: https://github.com/DanyUP/angular-strophe

Am I missing something?

**Comment by DanyUP** [comment]
I don't know if it may help (I don't even know if it's fully correct) but adding these 2 lines to package.json of strophe.js make it works:
```
  "exports": {
    "node": {
      "import": "./dist/strophe.esm.js",
      "require": "./dist/strophe.common.js"
    },
    "default": "./dist/strophe.umd.js", // Added this
    "types": "./src/types/index.d.ts"    // and this
  },
```

**Comment by johnnybaida** [comment]
+1

**Comment by jcbrand** [comment]
Thanks for the bug report and fix @DanyUP. I've made the necessary change.
