### ISSUE TITLE
Type error on import in typescript project

### ISSUE THREAD

**Issue by genericFJS** [strophe/strophejs#726]
When I try to import the package in my node/typescript project, I get an error:
![image](https://github.com/user-attachments/assets/327871a0-0148-4abd-a02a-da0106b6940a)
If I explicitly add the "types" to the "exports" in the stroph.js "package.json", everything works:
```json
  "exports": {
    "node": {
      "import": "./dist/strophe.esm.js",
      "require": "./dist/strophe.common.js"
    },
    "types": "./src/types/index.d.ts"
  },
```
Could this fix be included, please?

**Comment by genericFJS** [comment]
My bad: I just had a look at the package.json in the master branch and it already is included: https://github.com/strophe/strophejs/blob/0abfc1cfb6a6073508c4258eebc75f619c3b8241/package.json#L50
Follow up question: Could this update be pushed to npm, please?

**Comment by jcbrand** [comment]
Done :+1:
