### ISSUE TITLE
connection.pause() not working.

### ISSUE THREAD

**Issue by fpsColton** [strophe/strophejs#79]
Hi all,

I'm writing my own js XMPP client with strophe.js and I believe I've come across an issue with the .pause() function of connection. 

I've implemented a mechanism to store the current session and re-attach between page loads, and while I've got this working well, from time to time something would cause my session to be removed (causing my attach to fail). Well, I took a closer look at what is happening, and I've found the cause of my intermittent problem: shortly after calling connection.pause() I can see traffic from strophe (as seen from a connection.xmlOutput function override). If I debug the events which occur during 'onunload', or 'onbeforeunload', what happens is:
0. User interaction causes onUnload or onBeforeUnload to fire (user navigates away from current page)
1. Strophe Connection is paused with .pause()
2. Session variables are stored (SID, last used RID, etc)
3. Strophe unexpectedly sends a stanza with the same RID as a previous stanza 
4. Most of the time, the re-sent stanza does not have any impact and the 'onUnload/onBeforeUnload' function completes, session is stored, the next page is reloaded and strophe attaches as expected.
But SOMETIMES the re-sent stanza from strophe will 404 (perhaps the browser is cancelling the pending request due to the 'onUnload' event?), then my onConnect callback get's called with a status parameter indicating that strophe is disconnecting, and then disconnected. (Since I had code in here which cleared my session when strophe disconnects, this caused my attachment to fail when the next page loads)

Since discovering this re-sent stanza (and the intermittent 404 + disconnect) I've put some code in place so that whenever the connection disconnects, I check to see if I've called .pause() on it, and if so, let it disconnect happen but don't clear my session. Now even if the re-sent stanza 404's, by the time the next page is loading, my SID/RID are still in the session, and I'm able to attach (It's working well now :)).

Question is, why is strophe still doing stuff after calling .pause() ?

**Comment by jcbrand** [comment]
Looks fixed. Closing due to inaction.
