### ISSUE TITLE
this.error on _hitError is NaN and not able to increment

### ISSUE THREAD

**Issue by anulals** [strophe/strophejs#82]
try to connect with out network to get this issue. In this case this.errors is NaN  and not able to increment.

 /** PrivateFunction: _hitError 
     *  _Private_ function to handle the error count.
    *  My update follows , line number 4139
  */
    _hitError: function (reqStatus)
    {
	if(typeof this.errors != 'number')
		this.errors = 0;
        this.errors++;

**Comment by jcbrand** [comment]
Looking at the code, `this.errors` is only ever set to 0 or incremented. There's no reason why it should or could be NaN.

Can you check if this is still a problem with latest strophe.js?

Closing this ticket. Please reopen if you can still replicate the problem with the newest strophe.js
