### ISSUE TITLE
 _onDisconnectTimeout Not working properly

### ISSUE THREAD

**Issue by anulals** [strophe/strophejs#83]
On line 4497 in the verson 1.1.3 

have an empty _onDisconnectTimeout function, this one prevents from disconnecting when there is no network connection, comment this line and it will get disconnected when there is no network

 /** PrivateFunction: _onDisconnectTimeout
     *  _Private_ timeout handler for handling non-graceful disconnection.
     *
     *  This does nothing for WebSockets
     */
   // _onDisconnectTimeout: function () {},

**Comment by jcbrand** [comment]
@anulals Can you explain why it "prevents from disconnecting when there is no network connection" ?

**Comment by jcbrand** [comment]
Closing due to inaction.
