### ISSUE TITLE
bug espace pile insufisant in IE10

### ISSUE THREAD

**Issue by issmail** [strophe/strophejs#84]
in IE10  function serialise  cause inlimited loupe 
for (i = 0; i < elem.attributes.length; i++) { //here console of IE display message  espace pile insufisant

```
           if(elem.attributes[i].nodeName != "_realname") {
             result += " " + elem.attributes[i].nodeName.toLowerCase() +
            "='" + elem.attributes[i].value
                .replace(/&/g, "&amp;")
                   .replace(/\'/g, "&apos;")
                   .replace(/>/g, "&gt;")
                   .replace(/</g, "&lt;") + "'";
           }
```

in firefox  no problem
excuse me for my bad english

**Comment by rj33** [comment]
This sounds like a bug handling the global flag with &, it seems it might be replacing & with &amp then looking over the entire string again for & and then continually looping on that attempt. 
Does IE10 fail with just "sdfsdf&sdfsdf".replace(/&/g,"&amp;");  ? If not can you capture the string that it is going into an infinite loop on?

**Comment by jcbrand** [comment]
I want to add [Saucelabs](https://saucelabs.com) integration for Strophe.js (it's free for FOSS projects) which will allow us to automatically test Strophe on multiple browsers.

That should highlight issues like the one above and also the one in #69.
