### ISSUE TITLE
Support for acks

### ISSUE THREAD

**Issue by giladbeeri** [strophe/strophejs#85]
When sending a message, it would be very helpful to know it was successfully sent.
One approach is to implement XEP-0198 (and the server should return acks), but it will also be nice if I will be able to pass a callback which will be called after a successful or failed attempt to send a message (failure is more important). The callback should be called with parameters that identify the stanza.

**Comment by jcbrand** [comment]
Like @allan-simon mentioned, this should rather be implemented as a plugin.
