### ISSUE TITLE
Add strophe to npm *or* add package.json to the release tarball

### ISSUE THREAD

**Issue by vcarel** [strophe/strophejs#87]
I'm using webmake (which is an alternative to browserify) to build my JS app. It uses NPM to gather all the dependencies.

There are 3 ways to declare a dependency in npm: 
1/ as npm module, which Strophe is not,
2/ as a github URL, which is apparently excluded since it needs to commit the built strophe.js file into the repo (and that's not recommended by the github team),
3/ as a tarball URL, which only needs to add the package.json to the tarball.

From my perspective, I believe the option 3 is the easiest way, since it only needs to touch the gruntfile.
Thanks a lot :-)

**Comment by jcbrand** [comment]
Seems like @flosse added Strophe.js to NPM.

https://www.npmjs.com/package/strophe
