### ISSUE TITLE
connection not established using openfire

### ISSUE THREAD

**Issue by qualitybits** [strophe/strophejs#88]
i am making a connection of `Strophe` with with `Openfire` but its return with error 

    POST http://frank:7070/http-bind/ 500 (Task org.jivesoftware.openfire.http.HttpSessionManager$HttpPacketSender@12f0fd rejected from java.util.concurrent.ThreadPoolExecutor@a74704[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 30]) strophe.js:4435

    POST http://frank:7070/http-bind/ 500 (Task org.jivesoftware.openfire.http.HttpSessionManager$HttpPacketSender@1d400eb rejected from java.util.concurrent.ThreadPoolExecutor@a74704[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 30])

see the screen shot of [Chrome Console][1]  and [Firefox's firbug][2]

this is the connection file.

    function con (username,password) {
    	// body...
    // creating connection
    var conn = new Strophe.Connection("http://frank:7070/http-bind/");
    
    // starting a connection to example.com
    conn.connect(username, password, function my_callback(status) {
    
    	
    if (status === Strophe.Status.CONNECTED) {
    alert('connection established');
    }
    else
    {
    	alert("invalid login detail");
    }
    
    });
    };
    
    // disconnecting
    //conn.disconnect();
    $(document).ready(function(e){
    	$('#sub').click(function(e){
    		var username = $('#username').val();
    		var password = $('#password').val();
    			con(username,password);
    
    	});
    });

  [1]: http://prntscr.com/4qram1
  [2]: http://prntscr.com/4qrb5j

**Comment by jcbrand** [comment]
The error message is this:

```
Task org.jivesoftware.openfire.http.HttpSessionManager$HttpPacketSender@1d400eb rejected from java.util.concurrent.ThreadPoolExecutor@a74704
```

This is a problem with your OpenFire setup. The Java `ThreadPoolExecutor` is rejecting `HttpPacketSender` from the OpenFire `HttpSessionManager`.

Reasons why it might be rejecting tasks are explained here: http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html
