### ISSUE TITLE
Email adress as user names are not handled

### ISSUE THREAD

**Issue by ernestochaves** [strophe/strophejs#91]
Hello. 

In my xmpp server, some user names are email address. I thought I could escape them so strophe could correctly parse the host and other components. For instance, some@some.com would end up being some\\40come.com@xmpphost. But nowhere within the connect method the user name is unescaped. 

I saw you had an unescape method within your code that I tryed to change, but I cannot quite get the parts to fit together. I tryed this

``` javascript
    // parse jid for domain
    this.domain = Strophe.getDomainFromJid(jid);
    //Set the escaped jid at the end so the others wont get affected
    this.jid = Strophe.unescapeNode(jid);     
```

**Comment by allan-simon** [comment]
can it be solved by splitting only once "@"  starting from the end ?

**Comment by jcbrand** [comment]
I've used Strophe with email addresses in JIDs successfully before. This is about 4 years ago, so perhaps a bug was introduced in the meantime, I don't know. Would be good to add some tests for this.
