### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by hunan-rostomyan** [strophe/strophejs#96]
![screen shot 2014-12-28 at 4 31 43 pm](https://cloud.githubusercontent.com/assets/5122980/5565412/0d18e62a-8eaf-11e4-93ce-1da442b48073.png)

I apologize if this isn't the right place for reporting such insignificant things. I found no contact info on the homepage.

**Comment by jcbrand** [comment]
Fixed in the README of this project and also in strophe.im (which is the repo for the website).

I don't know how the strophe.im site gets updated however...
