### ISSUE TITLE
punjab HttpbParse sometimes time out script

### ISSUE THREAD

**Issue by goors** [strophe/strophejs#98]
In your python example you have something like
<pre>
from punjab.httpb import HttpbParse
parser = HttpbParse(True)
data = response.read()
return parser.parse(data)
</pre>

This part: return parser.parse(data) takes forever sometimes. Sometimes it just times out .
When I do print response.read() xml stream is printed.

Do you know maybe how to solve this?
Maybe to use some other parser?

**Comment by twonds** [comment]
Hello,

Just checking but do you happen to do a print response.read() and then a
data = response.read() ? It would be best to print data after the read.

How do you run this example? What is the time of forever? What is the
timeout?

Also, what version of twisted?

**Comment by goors** [comment]
Well it looks like DNS timeout. But again I am not sure since print response.read() gives me server response. This part parser.parse(data) is sometimes executed and sometimes not.

Do you have same problem maybe?
I switch this python part with php at the end, but I do not really like to mix programing languages on same project. Do you have some email so I can send you user/password/jabber server?

I am running script from command line.

**Comment by twonds** [comment]
tofu@thetofu.com email or xmpp

**Comment by goors** [comment]
I just send you jabber invitation.

**Comment by jcbrand** [comment]
Can this ticket be closed? Doesn't appear to have anything to do with strophe.js specifically.

**Comment by twonds** [comment]
Yes, it can be closed. I can't close it. :)
